### ISSUE TITLE
Affichage par heures ? , Ecran dernier 7 jours

### ISSUE THREAD

**Issue by disquette38** [guillaumezin/DomoticzLinky#102]
Je suis actuellement en version du plugin 2.3.2, mais je n'ai plus l'affichage de ma consommation par heures dans le premier graph.
Voici mon paramétrage:
![Screenshot_515](https://user-images.githubusercontent.com/16446911/97811221-3f16a000-1c79-11eb-9a9c-842794b2ce80.png)

Résultat:
![Screenshot_516](https://user-images.githubusercontent.com/16446911/97811282-c401b980-1c79-11eb-8bfb-e5237a50718c.png)

Comment est-ce que je dois paramétrer pour de nouveau avoir l'affichage par heures ?

**Comment by guillaumezin** [comment]
Bonsoir,
Voyez-vous vos courbes par heures sur le site d'Enedis ? Avez-vous activer activé l'enregistrement et la collecte de la consommation horaire sur votre compte Enedis comme indiqué dans https://github.com/guillaumezin/DomoticzLinky#installation ?

**Comment by disquette38** [comment]
Bonsoir,
Oui bien sur, cela fonctionner depuis plus d'un an, et depuis les changement de cet été je n'ai plus l'affichage par heures.

**Comment by guillaumezin** [comment]
Bonjour,
Votre paramètre "Debug" est sur "Avancé", donc le plugin doit produire un fichier log dans un répertoire temporaire, le chemin du fichier est donné dans l'onglet "Status" des logs Domoticz. Voulez-vous bien m'envoyer ce fichier à mon adresse mail visible sur mon profil https://github.com/guillaumezin ?

**Comment by disquette38** [comment]
Bonjour,
Suite à nos échanges j'ai déactivé les deux options "Enregistrement de la consommation horaire" et "Collecte de la consommation horaire", puis tentative de réactivation ...
Pour l'instant seul  "Enregistrement de la consommation horaire" est valide, "Collecte de la consommation horaire" reste à "Demande en cours......" depuis hier au soir !

**Comment by disquette38** [comment]
C'est bon, j'ai maintenant pu réactiver la "Collecte de la consommation horaire"

![Screenshot_510](https://user-images.githubusercontent.com/16446911/98278778-5f0bd380-1f99-11eb-9b6d-a39cb01f1909.png)
Dans mon espace Enedis
![Screenshot_511](https://user-images.githubusercontent.com/16446911/98279001-ac884080-1f99-11eb-9fb1-9044e883d88a.png)
Et dans Domoticz
![Screenshot_516](https://user-images.githubusercontent.com/16446911/98279046-bb6ef300-1f99-11eb-8a65-ee832836e01d.png)

J'ai transmis par email mon log 

Merci pour le travail fourni pour le plugin !

**Comment by guillaumezin** [comment]
Bonjour,
J'ai analysé vos logs... Et ils ne contiennent pas d'anomalie expliquant votre problème, les données par heure sont récupérées et écrites dans la base de données. Pouvez-vous me dire si ça se produit toujours avec la dernière version ? Si c'est le cas, essayez de changer de thème, je vois que vous n'avez pas le même habillage que moi. Si toujours pas mieux, détruisez le dispositif, il sera recréé à la prochaine récupération.

**Comment by disquette38** [comment]
Bonjour,
J'ai mis en place une VM pour faire de nouveau un test, et là cela fonctionne correctement !. J'ai donc fait un export de toute mes données de chaque tables, puis  un import sur une nouvelle install, c'est maintenant en prod et **OK**  Effectivement je n'avais pas pensé au thème . Je clos ce ticket. Merci !
![Screenshot_542](https://user-images.githubusercontent.com/16446911/99666737-a8fdba80-2a6b-11eb-965d-e78f50872c3f.png)
