### ISSUE TITLE
PLugin devenu non fonctionnel ?

### ISSUE THREAD

**Issue by ricorico94** [guillaumezin/DomoticzLinky#103]
Bonjour,
J'utilisais le plugin depuis cet été, mais il ne fonctionne plus..
- problèmes apparus lors de redémarrages de Domoticz: à chaque fois, il  a fallu que je repasse par le lien d'activation - est-ce normal ?
- depuis environ 2 semaines, le lien d'activation ne fonctionne plus (je me connecte d'abord à Enedis, je colle le lien indiqué dan sle log de domoticz, une page s'ouvre avec une case pré-remplie du code, je valide.. et j'obtiens un message d'erreur:
`Demande de consentement de partage de données d'Enedis vers le plugin DomoticzLinky
server_error
lincs-internal-server-error`
(l'url de cette page est https://enedis.domoticz.russandol.pro/auth/redirect?code=500&error=server_error&error_description=lincs-internal-server-error )

Suis-je le seul à avoir ce problème ?
Je tourne nous Pi 3B +, avec domoticz 2020.2 et j'ai mis à jour à nouveau aujourd'hui le plugin.

Merci de votre aide,
Ricorico94

**Comment by 7h3Cub3** [comment]
J'ai eu le même soucis tout à l'heure il a fallu que je reinitialise la demande d'autorisation avec le menu deroulant du debug du plugin, par contre j'ai un soucis c'est que mon device a disparu, et quand j'essai de le remettre il revient jamais malgré une suppression/rajout et d'avoir activer la detection de nouvelles sondes, je sais pas quoi faire.

**Comment by ol-v-er** [comment]
Je rencontre le même problème ce matin (après installation du plugin hier soir où le serveur était indisponible) : 

![Capture d’écran 2020-11-03 à 09 06 27](https://user-images.githubusercontent.com/724538/97964832-b05d6c80-1db9-11eb-8eb8-f184b6cd8739.png)

**Comment by ol-v-er** [comment]
Au bout de 3 essais, c'est passé sans explications complémentaires (j'avais pourtant sorti le deboggueur cette fois-ci...)

![Capture d’écran 2020-11-03 à 09 50 24](https://user-images.githubusercontent.com/724538/97965074-13e79a00-1dba-11eb-9316-cef5fdbea191.png)
