### ISSUE TITLE
invalid, 2 fois les lignes de réglage

### ISSUE THREAD

**Issue by calou033** [guillaumezin/DomoticzLinky#104]
Bonjour,

J'ai installé la dernière version mais j'ai la mention invalid sur le device
![image](https://user-images.githubusercontent.com/36360621/98151076-eb51c400-1ecf-11eb-8814-6e3539e7b17f.png)
Dans la page de réglage du matériel les champs sont répétés 2 fois
![image](https://user-images.githubusercontent.com/36360621/98151377-5b604a00-1ed0-11eb-9a94-7bddb22c6b47.png)

Merci de votre aide ou commentaire
Félicitation pour ce plugin

**Comment by guillaumezin** [comment]
Bonjour,
Etez-vous certain de n'avoir qu'une fois le plugin dans le répertoire de plugins de Domoticz ? N'avez-vous pas une copie qui traîne ? D'autre part, baissez pour le moment le nombre de jours à récupérer pour les autres vues à 7. Avez-vous donné votre consentement pour la récupération des données comme indiqué dans le readme ?

**Comment by calou033** [comment]
Effectivement j'avais sauvegardé le dossier avec un autre nom. Cela résout le problème du doublement des lignes mais pas le reste:

Toujours cette erreur après ré-installation du plugin
2020-11-12 10:32:05.545 Error: (Linky) durant l'étape save de 2020-11-11 à 2020-11-12 - Données manquantes pour mettre à jour le tableau de bord

et donc:

![image](https://user-images.githubusercontent.com/36360621/98922970-5fddc180-24d3-11eb-9577-343ed2e218a1.png)

**Comment by guillaumezin** [comment]
Bonjour,

Et vos données sont visibles sur le site d'Enedis ? Avez-vous autorisé "Enregistrement de la consommation horaire" et "Collecte de la consommation horaire" comme indiqué dans https://github.com/guillaumezin/DomoticzLinky#installation ?

**Comment by guillaumezin** [comment]
Sans nouvelle, je clos.
