### ISSUE TITLE
 'onHeartbeat' failed 'TypeError':'combine() argument 2 must be datetime.time, not datetime.datetime'

### ISSUE THREAD

**Issue by JRCondat** [guillaumezin/DomoticzLinky#107]
2020-11-17 21:45:08.553 Error: (Enedis) 'onHeartbeat' failed 'TypeError':'combine() argument 2 must be datetime.time, not datetime.datetime'.
2020-11-17 21:45:08.553 Error: (Enedis) ----> Line 819 in '/home/pi/domoticz/plugins/DomoticzLinky/plugin.py', function onHeartbeat
2020-11-17 21:45:08.553 Error: (Enedis) ----> Line 765 in '/home/pi/domoticz/plugins/DomoticzLinky/plugin.py', function onHeartbeat

Activation du debug n'apporte rien de plus verbeux.
Données visibles sur le site d'Enedis.
Plug in à jour avec un git pull.

Domoticz sur Raspberry Pi 3B 
Version: 2020.2
Build Hash: b63341bc0
Compile Date: 2020-04-26 13:47:55
dzVents Version: 3.0.2
Python Version: 3.7.3 (default, Jul 25 2020, 13:03:44) [GCC 8.3.0]

**Comment by guillaumezin** [comment]
Bonsoir,
Etes-vous certain que la mise à jour est effective ? Je n'utilise plus la fonction combine(), qui pose tout un tas de problème, depuis un moment déjà...

**Comment by JRCondat** [comment]
Bon visiblement le git pull fonctionnait mais il a fallu que j'aille supprimer à la main en sudo le répertoire " __pycache__" pour que l'erreur disparaisse.

Second souci, plus d'erreur mais lors de l'autorisation d'accès de ton serveur à mes données Enedis, après avoir cliqué sur le bouton "Valider" du serveur Enedis, je suis redirigé vers ton serveur avec une erreur "server_error
lincs-internal-server-error"

Code d'enrôlement : XZDF-SNGA
URL de ton serveur : https://enedis.domoticz.russandol.pro/auth/redirect?code=500&error=server_error&error_description=lincs-internal-server-error

**Comment by guillaumezin** [comment]
Je viens de faire un essai, et l'infrastructure de consentement a l'air en panne, effectivement. Il faut que j'analyse si le problème est de mon côté ou du côté d'Enedis.

**Comment by guillaumezin** [comment]
@russandol-sarl peux-tu regarder stp ?

**Comment by guillaumezin** [comment]
Bonsoir,
Je viens de réessayer et la demande de consentement à l'air de refonctionner, voulez-vous réessayer ?

**Comment by JRCondat** [comment]
Malheureusement, pas mieux. Même erreur. J'ai désactivé le plugin puis réactivé, ça m'a proposé le code suivant : https://enedis.domoticz.russandol.pro/device?code=GFHF-CMBY
et à la fin de l'enrollement la même erreur 500.

**Comment by guillaumezin** [comment]
Bonjour,
Vous n'y arrivez toujours pas ?

**Comment by guillaumezin** [comment]
Sans nouvelle, je clos.

**Comment by JRCondat** [comment]
Désolé de ne pas avoir donné suite. Effectivement, j'ai pu m'appairer mais les résultats remontés sont complètement fantaisistes.
