### ISSUE TITLE
Problème de récupération des données Linky

### ISSUE THREAD

**Issue by BSD31** [guillaumezin/DomoticzLinky#11]
Bonjour et félicitations pour ce plugin.
Ceci dit, je n'arrive pas à le faire fonctionner, donc j'ai hâte d'y arriver...
J'ai un message d'erreur dans les LOG de Domoticz :

2019-03-29 10:54:43.719 Error: (Linky) Les données reçues ne sont pas du JSON : Expecting value: line 1 column 1 (char 0) durant l'étape getdatahours de 21/03/2019 à 29/03/2019

J'ai deux contrats chez Enedis (Un à Toulouse et l'autre à Perpignan).
Celui de Toulouse n'est pas en Linky mais en compteur électronique ancienne génération.
Celui de Perpignan est un Linky.
Les deux contrats sont accessibles sur le site https://particulier.edf.fr.

Mon Domoticz tourne sur un NAS Synology.

Comment le plugin peut-il choisir parmi l'un ou l'autre des deux contrats accessibles sur le même compte Enedis et le problème pourrait-il venir de là ?
 
Merci encore.
Bruno

[Log (Mon Linky).txt](https://github.com/guillaumezin/DomoticzLinky/files/3051430/Log.Mon.Linky.txt)
[MonIP_json.htm_type=graph&sensor=counter&idx=65&range=day.txt](https://github.com/guillaumezin/DomoticzLinky/files/3051441/MonIP_json.htm_type.graph.sensor.counter.idx.65.range.day.txt)
[MonIP_json.htm_type=graph&sensor=counter&idx=65&range=year.txt](https://github.com/guillaumezin/DomoticzLinky/files/3051442/MonIP_json.htm_type.graph.sensor.counter.idx.65.range.year.txt)
![Choix contrat](https://user-images.githubusercontent.com/11723095/55682169-f6c5bd80-592f-11e9-96f2-65915fe2d20a.png)
![Data Jours Enedis](https://user-images.githubusercontent.com/11723095/55682179-13fa8c00-5930-11e9-9ed0-8dca7b797403.png)
![Data Mois Enedis](https://user-images.githubusercontent.com/11723095/55682184-2d033d00-5930-11e9-8f47-92d2571f9f42.png)
[Mes-releves-elec (Depuis le site Enedis).xlsx](https://github.com/guillaumezin/DomoticzLinky/files/3051464/Mes-releves-elec.Depuis.le.site.Enedis.xlsx)

**Comment by guillaumezin** [comment]
Bonjour,

le plugin passe par le site d'Enedis pour récupérer les courbes. Arrivez-vous à visualiser les courbes sur le site d'Enedis plutôt que celui d'EDF ? Effectivement, si sur un même compte Enedis vous devez choisir entre 2 contrats, c'est un cas de figure que je n'ai pas envisagé ni testé avec le plugin.

**Comment by BSD31** [comment]
Bonsoir et merci de ce retour rapide.
Je n'avais pas fait le distinguo entre le compte EDF et un compte Enedis...
Je viens donc de créer un accès chez Enedis mais je recevrai mes codes par courrier...
Dès réception, je ne manquerai pas de faire les tests qui s'imposent pour le bon fonctionnement du plugin et vous tiendrai informé.
Merci encore

**Comment by guillaumezin** [comment]
D'accord, le plugin s'appuie sur Enedis, ça permet d'être indépendant du fournisseur. Je suis passé de Direct Energie à Ekwatteur et le plugin a continué à fonctionne de façon transparente. Je ferme le ticket. Si vous avez des problèmes à réception des codes, n'hésitez pas à continuer ce fil, je rouvrirai, ou à créer un nouveau ticket.

**Comment by BSD31** [comment]
11 jours depuis ma demande de création de mon compte et toujours pas de codes d'accès Enedis qui doivent arriver par la poste... ou à pieds !

**Comment by BSD31** [comment]
Toujours pas de codes par la poste alors j'ai appelé Enedis par téléphone et un monsieur charmant a activé mon compte en live !
Donc tous est disponible maintenant sur leur site. 
J'ai quand même des problèmes dans Domoticz.
En effet, les informations remontent bien avec le plugin mais j'ai des erreurs.
Mon abonnement date de moins d'un an (juin 2018).
Le problème vient-il de là ?
Merci de votre aide.

[Log - 2 (Mon Linky).txt](https://github.com/guillaumezin/DomoticzLinky/files/3122026/Log.-.2.Mon.Linky.txt)

![Data Jours Enedis](https://user-images.githubusercontent.com/11723095/56820210-926d8e00-684b-11e9-9e6d-c54e6fdfcd23.png)

**Comment by BSD31** [comment]
[Enedis - 3.xlsx](https://github.com/guillaumezin/DomoticzLinky/files/3122095/Enedis.-.3.xlsx)
[Enedis - 1.xlsx](https://github.com/guillaumezin/DomoticzLinky/files/3122096/Enedis.-.1.xlsx)
[Enedis - 2.xlsx](https://github.com/guillaumezin/DomoticzLinky/files/3122097/Enedis.-.2.xlsx)

**Comment by guillaumezin** [comment]
Je suis surpris, si vos courbes s'affichent sur le site d'Enedis, elles devraient pouvoir être récupérées par Domoticz. Votre fichier log semble incomplet (il me manque des messages entre 17h25 et 17h31), pouvez-vous essayer de recapturer un log plus complet ? Vous pouvez par exemple vous rendre dans Réglages / Matériel, cliquer sur le plugin et juste faire modifier, ça va relancer le processus.

**Comment by BSD31** [comment]
Merci de ce retour.
Voici un log qui me semble complet...

[Log - 3 (Mon Linky).txt](https://github.com/guillaumezin/DomoticzLinky/files/3125497/Log.-.3.Mon.Linky.txt)

**Comment by guillaumezin** [comment]
Grâce à vous, j'ai trouvé un erreur... dans l'affichage des erreurs. Ce sont en fait les anciennes données qui posent problème dans votre cas, le message d'erreur devrait être plus clair à partir de la version 1.1.8 du plugin. Le problème que vous rencontrez vient sans doute du fait que votre abonnement n'est pas vieux. Vous pouvez essayer de réduire le paramètre "Nombre de jours à récupérer pour les autres vues" pour faire disparaître les messages d'erreur inutiles

**Comment by BSD31** [comment]
Bonsoir.
Je suis heureux que mon problème permette de faire évoluer le plugin.
Je ne suis pas chez moi et ne peux intervenir en root sur mon NAS à distance.
Je ne pourrais donc tester la version 1.1.8 que ce WE
En attendant, j'ai réduit le nombre de jour collectés (50j, 100j, 150j, 200j, 250j et 300j) mais les erreurs sont toujours présentes en version 1.1.7
C'est pas grave, j'attends la version 1.1.8 et referais les tests.
Merci encore et bonne soirée
Bruno

**Comment by BSD31** [comment]
Bonjour Guillaume.

Nouvelle version 1.1.8 du plugin installée.
Nombre de jours récupérés corrigés (335j) car mon abonnement date de juin 2018.
Nombre de jour pour la vue par heure fixé à 1 pour visualiser les dernières 24h.
J'ai toujours un message d'erreur mais il semble plus cohérent au regard des dates qui posent problème.
     -> _Données manquantes durant l'étape getdatahours de 01/05/2019 à 03/05/2019._

Copies d'écran Enedis :
     -  le 01-05-2019 les données sont visibles
     -  le 02-05-2019 Les données sont invisibles
     -  le 03-05-2019 n'est pas accessible à l'heure où j'écris ces lignes.

Peut-on corriger ce problème ?

[Log - 4 (Mon Linky).txt.txt](https://github.com/guillaumezin/DomoticzLinky/files/3141151/Log.-.4.Mon.Linky.txt.txt)

![image](https://user-images.githubusercontent.com/11723095/57127549-0c909c00-6d91-11e9-8418-06390563fd3e.png)

![image](https://user-images.githubusercontent.com/11723095/57127563-174b3100-6d91-11e9-9354-b39da448789c.png)

D'autre part, je ne comprends pas l'affichage _'Jour'_ du rapport Domoticz.
En effet, j'ai paramétré le plugin à 1 jour pour la vue par heure.
Le titre du rapport journalier affiche 5 jours et non 24 heures : _'Utilisation Dernière 5 jours'_,
Bizarre non ?

![Screenshot Domoticz report](https://user-images.githubusercontent.com/11723095/57127710-888ae400-6d91-11e9-934c-cb03d31d6cfc.jpg)

Merci de vos lumières.
Bruno

**Comment by guillaumezin** [comment]
Je ne sais pas pourquoi vos données du 02/05 sont invisibles, mais ce n'est pas normal de la part d'Enedis et le plugin détecte le problème, d'où le message d'erreur, le plugin ne peut rien faire de plus.

Pour la vue à 5 jours, c'est un paramètre de Domoticz, pas du plugin : vous pouvez paramétrer le plugin pour récupérer jusqu'à 7 jours, mais vous avez intérêt à mettre une valeur cohérente avec la profondeur d'historique que Domoticz conserve et affiche (paramètre Log des capteurs qui se trouve dans Réglages / Paramètres / Historique des logs).

**Comment by BSD31** [comment]
Bonjour.
Après quelques jours de test et un appel chez Enedis pour soumettre le problème, tout est rentré dans l'ordre.
Félicitations et merci pour le support.

**Comment by guillaumezin** [comment]
Très bien, je ferme le fil alors.
