### ISSUE TITLE
Fonctionnement partiel

### ISSUE THREAD

**Issue by Iolorin** [guillaumezin/DomoticzLinky#110]
Bonjour,

Le plugin Linky fonctionne partiellement chez moi.
Il récupère des données et les affiches dans les vues graphiques, mais le capteur de mesure proprement dit reste rouge avec un message "Invalid".
Je pense que c'est lié, dans le log, j'obtiens ce message :
Status: Warning: Expecting svalue with at least 5 elements separated by semicolon, 0 elements received (""), notification not sent (Hardware: 10 - Linky, ID: XXXX, Unit: 1, Type: FA - P1 Smart Meter, SubType: 1 - Energy)

Je suis en Domoticz 2020.2 sous Raspberry Pi (Raspbian).

Des idées ?

Merci!

**Comment by Iolorin** [comment]
Bon, j'avais essayé plein de trucs avant de poster cette demande, et puis, hop, j'ai trouvé la solution :-)
Je n'avais juste pas configuré les affichages dans le dispositif Linky, donc il n'affichait rien, pardi !

**Comment by guillaumezin** [comment]
Bonsoir,
Je pense que ce n'est pas votre faute, j'ai supprimé dans les versions les plus récentes certaines configuration d'affichage, car trop gourmandes en bande passante. Si vous aviez une de ces anciennes configurations et que vous avez mis à jour le plugin, cela a pu aboutir à cette anomalie.
Merci de l'avoir signalé, si ça se reproduit, je saurai d'où ça vient.
Bonne soirée.
