### ISSUE TITLE
Le plugin ne récupére plus les données depuis plusieurs jours

### ISSUE THREAD

**Issue by jcsombret** [guillaumezin/DomoticzLinky#112]
Bonjour,

Depuis plusieurs jours toutes les tentatives de récupération échouent, dans les logs j'ai ce message surprenant !!

 Status: (Compteur EDF) Prochaine récupération complète de l'historique : 2021-05-06

Quelqu'un aurait-il une idée du problème ?

Par avance merci

joel

**Comment by guillaumezin** [comment]
Bonjour,
Le message n'est pas surprenant, pour ne pas surcharger les serveurs, le plugin ne fait une récupération complète que de temps en temps.
Pouvez-vous vous rendre dans les paramètres du plugin, mettre le paramètre "Debug" sur "Simple", dans les logs, vous aurez le chemin vers un fichier log produit dans un répertoire temporaire. Attendez quelques minutes que ce fichier se remplisse et vous me l'envoyer à mon adresse qui s'affiche sur mon profil github https://github.com/guillaumezin.

**Comment by jcsombret** [comment]
Bonjour,

Merci d'avoir pris le temps de vous intéresser à mon problème.
Néanmoins depuis quelques jours le plugin fonctionne bien, sans avoir compris ce qui a pu débloquer la situation, mais je vais m'en tenir là et ne pas vous encombrer d'un incident qui a été passager.

Encore merci

Cordialement

joel AYON
________________________________
De : Guillaume Zin <notifications@github.com>
Envoyé : vendredi 1 janvier 2021 16:01
À : guillaumezin/DomoticzLinky <DomoticzLinky@noreply.github.com>
Cc : jcsombret <mjc.clean@hotmail.fr>; Author <author@noreply.github.com>
Objet : Re: [guillaumezin/DomoticzLinky] Le plugin ne récupére plus les données depuis plusieurs jours (#112)


Bonjour,
Le message n'est pas surprenant, pour ne pas surcharger les serveurs, le plugin ne fait une récupération complète que de temps en temps.
Pouvez-vous vous rendre dans les paramètres du plugin, mettre le paramètre "Debug" sur "Simple", dans les logs, vous aurez le chemin vers un fichier log produit dans un répertoire temporaire. Attendez quelques minutes que ce fichier se remplisse et vous me l'envoyer à mon adresse qui s'affiche sur mon profil github https://github.com/guillaumezin.

**Comment by guillaumezin** [comment]
Ok, de mon côté le plugin est stable depuis plusieurs semaines, ce peut-être un problème passager avec l'infrastructure Enedis. Je clos.
