### ISSUE TITLE
Définition de "usage 1" et "usage 2"

### ISSUE THREAD

**Issue by Atreiide** [guillaumezin/DomoticzLinky#114]
Bonjour,

Merci pour ce plugin.

Pas vraiment une issue mais à quoi correspondent "usage 1" et "usage 2" au niveau des graph (logs)

**Comment by guillaumezin** [comment]
Bonsoir,

C'est dans le readme, c'est pour gérer le tarif heures pleines/heures creuses : https://github.com/guillaumezin/DomoticzLinky#heures-creuses

Bonne soirée.
