### ISSUE TITLE
Erreur Plugin Linky

### ISSUE THREAD

**Issue by Moulins58** [guillaumezin/DomoticzLinky#116]
Bonsoir,
Je me bats depuis un certain temps avec le plugin Linky. Il fonctionnait merveilleusement bien jusqu'au jour ou j'ai passé mon Domoticz sur un disque SSD . J'ai la dernière version de Domoticz et la dernière version du plugin.
Il démarre une fois a chaque coup que je relance Linky dans matériel.
Il me remonte bien les donnés et ensuite lors du rafraîchissement: plantage.
Dans les logs j'ai ce message d'erreur: 

_2021-01-25 18:52:17.219 Error: (Linky) durant l'étape : parseaccesstoken - Erreur status : 400 - code invalid_grant
2021-01-25 18:52:17.237 Error: (Linky) durant l'étape : parseaccesstoken - Le plugin va être arrêté. Relancez le en vous rendant dans Configuration/Matériel, en cliquant sur le plugin puis sur Modifier. Surveillez les logs pour obtenir le lien afin de renouveler le consentement pour la récupération des données auprès d'Enedis_

Si quelqu'un pouvait m'aider c'est un merveilleux outil.
Amicalement
HL
![Screenshot_Linky](https://user-images.githubusercontent.com/47673774/105747859-9d35e500-5f41-11eb-9dfc-9497939eb1a1.png)

**Comment by guillaumezin** [comment]
Bonsoir,
C'est étrange. Lors d'une récupération, le code d'autorisation reçu au consentement est sauvegardé dans la base de données de Domoticz pour être réutilisé le jour suivant. C'est comme si la sauvegarde n'était pas effective. Vous n'avez pas d'autres problèmes que ce plugin ? Est-ce que les droits sur domoticz.db sont bien restaurés ?
Sinon vous pouvez m'envoyer votre fichier log, comme expliqué dans https://github.com/guillaumezin/DomoticzLinky#les-probl%C3%A8mes-persistent, lors de l'obtention du consentement, et lors du plantage avec erreur 400, peut-être y verrais-je plus clair.
Bonne soirée.

**Comment by Moulins58** [comment]
Bonjour, et merci pour votre réponse rapide.
Comme je vous le disais, je suis dans la galère depuis le nouveau plugin et
en même temps j'ai installé Domoticz sur un disque SSD.

Votre réponse m'a interpellée et je me suis aperçue en fait que je
problème, je pense viens de mes remontées Enédis productions. Pourtant sur
Enédis ça semble fonctionner.
Mais là , pour le novice que je suis je ne trouve pas. Je vous joins le
fichier log d'hier soir.
Encore merci

*CordialementHenri LAUNAY                                              *
58 rue de Curette
44119 Grandchamp des Fontaines ça semble bien fonctionner
Tél: 0629428345



Le lun. 25 janv. 2021 à 20:45, Guillaume Zin <notifications@github.com> a
écrit :

**Comment by guillaumezin** [comment]
Bonjour,
Je n'ai pas reçu le fichier, s'il est trop gros, il ne passe pas par github, envoyez le moi directement à mon adresse mail visible sur https://github.com/guillaumezin

**Comment by guillaumezin** [comment]
Bonsoir,
J'ai bien reçu votre fichier log, il est hélas incomplet. Cependant, pouvez-vous essayer de réduire le paramètre "Nombre de jours à récupérer pour les autres vues" à 7 ? Si ca fonctionne vous pourrez augmenter progressivement ce paramètre. Quand votre historique sera enregistré dans la base de données de Domoticz, vous pourrez rebasculer ce paramètre à 7 pour ne pas faire exploser les quotas que me donne Enedis (et qui sont partagés avec tous les utilisateurs du plugin).

**Comment by Moulins58** [comment]
Je suis au nombre de jour à 7 depuis ce matin, d'ailleurs,  j'aurais du
vous envoyer ce log là.  Mais, c'est pareil. J'ai les données un fois et
c'est terminé.
Re bonne soirée.

Henri LAUNAY

Le mar. 26 janv. 2021 à 20:22, Guillaume Zin <notifications@github.com> a
écrit :

**Comment by Moulins58** [comment]
Re bonsoir, je pense que j'ai trouvé, pas la solution, mais la causse.
C'est bien la remonté de ma production qui ne veux pas remonter. J'ai coché
que la consommation sur le site Enedis et ça semble fonctionner.
Il faut savoir que mes données de production sont déjà partagées avec BDPV (
www.bdpv.fr). Je pensais que nous pouvions avoir plusieurs partages. Il
semble que non.
Confirmez moi si vous pouvez. Merci.
Bon nuit

Henri Launay
58, rue fe Curette
44119 Grandchamp des Fontaines
Tél: 06 29 42 83 45

Le mar. 26 janv. 2021 à 20:22, Guillaume Zin <notifications@github.com> a
écrit :

**Comment by guillaumezin** [comment]
Bonsoir,
On devrait pouvoir avoir plusieurs partages, mais ce n'est peut-être pas au point. Je vais poser la question à Enedis.
Je vous tiens au courant.

**Comment by Moulins58** [comment]
Merci, en tout cas,  la conso fonctionne
Bonne soirée


Henri LAUNAY

Le mer. 27 janv. 2021 à 20:51, Guillaume Zin <notifications@github.com> a
écrit :

**Comment by Moulins58** [comment]
Et encore Merci

Henri LAUNAY

Le mer. 27 janv. 2021 à 20:51, Guillaume Zin <notifications@github.com> a
écrit :

**Comment by guillaumezin** [comment]
Bonjour,
La question est ici : https://datahub-enedis.fr/data-connect/support/forum/topic/partage-de-la-production-vers-plusieurs-services-impossibles/ mais n'a toujours pas reçue de réponse.

**Comment by Moulins58** [comment]
Merci poour la copie. Bonne semaine.

Henri LAUNAY

Le dim. 7 mars 2021 à 16:45, Guillaume Zin <notifications@github.com> a
écrit :

**Comment by Moulins58** [comment]
Bonjour, et merci pour cette information. J'ai essayé ce mais le service
n'est pas disponible.

Je réessaye plus tart
Cordialement

*Henri LAUNAY                                              *
58 rue de Curette
44119 Grandchamp des Fontaines
Tél: 0629428345



Le mer. 6 oct. 2021 à 21:14, Guillaume Zin ***@***.***> a
écrit :

**Comment by guillaumezin** [comment]
Bonsoir,
Etes-vous toujours bloqué ?

**Comment by Moulins58** [comment]
Bonsoir,
Quand je relance le matériel LINKY, je n'ai pas l'erreur qui me permets de
me connecter a Enedis pour les autorisations.

Voici ce que j'ai dans les logs après avoir relancé Linky:
Paramètres / Historique des logs
2021-11-27 17:17:07.359 Status: Linky: (Linky) Initialized version 2.3.8,
author 'Barberousse'
2021-11-27 17:17:07.370 Status: Linky: (Linky) Log dans le fichier
/tmp/DomoticzLinky_2021_11_27_17_17_07_k6fgmg1q.log pour le matériel Linky
avec la version 2.3.8 du plugin
2021-11-27 17:17:08.462 Proxy: Error, reconnecting (Connection refused)
2021-11-27 17:17:09.464 RFXCOM: Temp + Humidity (Serre)
2021-11-27 17:17:10.069 RFXCOM: Temp + Humidity (Salle d'eau haut)
2021-11-27 17:17:10.248 RFXCOM: Temp (Eau chaude)
2021-11-27 17:17:11.606 RFXCOM: Temp (Unknown)
2021-11-27 17:17:14.428 RFXCOM: Temp (Chaudière)
2021-11-27 17:17:14.840 RFXCOM: Current/Energy (Electricité)
2021-11-27 17:17:16.102 Status: Linky: (Linky) Récupération des données
avec l'historique complet
2021-11-27 17:17:16.104 Status: Linky: (Linky) Traitement pour le point de
livraison 14258321188384
2021-11-27 17:17:19.438 RFXCOM: Wind (Moulins58_Vents)

Et j'ai toujours que le point de livraison, pas celui de production.

Bonne soirée. Cordialement.

*Henri LAUNAY                                              *
58 rue de Curette
44119 Grandchamp des Fontaines
Tél: 0629428345



Le jeu. 25 nov. 2021 à 20:58, Guillaume Zin ***@***.***> a
écrit :

**Comment by guillaumezin** [comment]
Bonsoir, je fais un peu de ménage, je clos ce ticket sans activité depuis longtemps.
