### ISSUE TITLE
erreur enedis?

### ISSUE THREAD

**Issue by dltrainou** [guillaumezin/DomoticzLinky#118]
Bonjour
Tout fonctionnait a merveille , mais depuis le 4/02 plus rien, j'ai été voir sur le site Enedis et les valeurs s’arrêtent aussi au 03/02 en heures et au 06/02 en jours? et ce, sur les 2 compteurs! (l'enregistrement données est bien activé chez Enedis)
Suis je le seul ou c'est général?? 
L'erreur ds le log domoticz linky est :
2021-02-07 09:04:30.352 Status: (linky) Récupération des données avec l'historique court
2021-02-07 09:04:30.352 Status: (linky) Traitement pour le point de livraison xxxxxxxxxx
2021-02-07 09:04:32.911 Status: (linky) Traitement pour le point de livraison yyyyyyyyyy
2021-02-07 09:04:32.046 Error: (linky) durant l'étape getdatahours de 2021-01-31 à 2021-02-07 - Pas de données disponibles, avez-vous associé un compteur à votre compte et demandé l'enregistrement et la collecte des données horaire sur le site d'Enedis (dans "Gérer l'accès à mes données") ?
2021-02-07 09:04:32.911 Error: (linky) durant l'étape save de 2021-02-06 à 2021-02-07 - Données manquantes pour mettre à jour le tableau de bord

**Comment by JmB11** [comment]
Bonjour.
Pareil pour moi : rien depuis le 4/02 !
Log :
2021-02-07 10:07:25.989 Status: Python Plugin System: (Consommation) Récupération des données avec l'historique court
2021-02-07 10:07:25.991 Status: Python Plugin System: (Consommation) Traitement pour le point de livraison xxxxxxxxxxxx
2021-02-07 10:08:27.028 Status: Python Plugin System: (Consommation) Prochaine connexion : 2021-02-08 08:11:13
2021-02-07 10:08:27.026 Error: Python Plugin System: (Consommation) durant l'étape save de 2021-02-06 à 2021-02-07 - Données manquantes pour mettre à jour le tableau de bord
Il semblerait que ça vienne de chez Enedis qui ne collecte/transmet plus de données depuis quelques jours...

PS : L'erreur provient du Plugin Linky configuré pour afficher : "Conso/Prod journée dernière" dans "Consommation à montrer sur le tableau de bord (affichage secondaire)", et comme il n'a aucune valeur pour la journée dernière, il écrit une erreur dans le Log.
Pour éviter l'erreur, Il suffit de modifier la config du plugin en passant sur "Conso/prod semaine en cours" par exemple.

**Comment by JmB11** [comment]
Re.

Ce soir, c'est reparti : le plugin a pu récupérer les stats chez Enedis depuis le 4/02 !?!
(Et les données apparaissent bien sur le site Enedis).

**Comment by dltrainou** [comment]
Ok merci ici aussi, c’est bon jusqu’à hier soir. Bonne soirée

 

De : JmB11 <notifications@github.com> 
Envoyé : dimanche 7 février 2021 18:06
À : guillaumezin/DomoticzLinky <DomoticzLinky@noreply.github.com>
Cc : dltrainou <dltrainou@free.fr>; Author <author@noreply.github.com>
Objet : Re: [guillaumezin/DomoticzLinky] erreur enedis? (#118)

 

Re.

Ce soir, c'est reparti : le plugin a pu récupérer les stats chez Enedis depuis le 4/02 !?!
(Et les données apparaissent bien sur le site Enedis).

**Comment by guillaumezin** [comment]
Et moi je n'ai rien changé au plugin, donc ce devait être un problème passager dans l'infrastructure Enedis.

Bonne soirée.

**Comment by guillaumezin** [comment]
Le problème n'est peut-être pas terminé, ça délire, je ne peux plus me connecter à mon compte développeur, il ne reconnaît pas mon compte...

**Comment by JmB11** [comment]
C'est Dimanche... Le jour de misa à jour des serveurs ;-)

**Comment by dltrainou** [comment]
Bonsoir

Est-ce que ça aurait un rapport avec « Datahub fait peau neuve »

C’était le mois dernier il me semble ?

Bonnes soirée

 

De : Guillaume Zin <notifications@github.com> 
Envoyé : dimanche 7 février 2021 19:50
À : guillaumezin/DomoticzLinky <DomoticzLinky@noreply.github.com>
Cc : dltrainou <dltrainou@free.fr>; Author <author@noreply.github.com>
Objet : Re: [guillaumezin/DomoticzLinky] erreur enedis? (#118)

 

Le problème n'est peut-être pas terminé, ça délire, je ne peux plus me connecter à mon compte développeur, il ne reconnaît pas mon compte...

**Comment by guillaumezin** [comment]
Non, le nouveau datahub est en place depuis un moment déjà (et beaucoup moins pratique, il faut faire 10 clics de plus pour arriver à la même information).

**Comment by guillaumezin** [comment]
J'ai regardé mes logs et j'ai aussi eu une "absence" d'Enedis le 06/02 et 07/02 qui s'est "corrigée" aujourd'hui vers 14h30.

**Comment by laoil72** [comment]
Salut, j'ai le même souci, j'ai fait une demande de code en cliquauant sur modifier dans domotic/materiel/config/linky.
Je reçois bien : https://enedis.domoticz.russandol.pro/device?code=XXXX-XXXX
Ca me renvoi un page 404 sur le site ENEDIS...

**Comment by guillaumezin** [comment]
Cf. #120

**Comment by Scrat95220** [comment]
Bonjour,
Toujours impossible pour moi de valider le consentement. Je valide bien le formulaire sur le site Enedis mais ensuite j'ai cette erreur :
![image](https://user-images.githubusercontent.com/33357657/108181335-0f948200-7108-11eb-9512-bdcfbc0eb8ce.png)

**Comment by guillaumezin** [comment]
N'hésitez pas à insister, certains utilisateurs ont passé l'erreur "server_error" après 5 ou 6 essais.

**Comment by guillaumezin** [comment]
Je clos le ticket, le problème qui se situait côté Enedis est résolu, si vous avez encore des erreurs, n'hésitez pas à insister. Si ça ne le fait toujours pas, vous pourrez toujours rouvrir un ticket.
