### ISSUE TITLE
Inscription enedis impossible

### ISSUE THREAD

**Issue by mlepannetier** [guillaumezin/DomoticzLinky#120]
Bonjour,

Depuis ce matin impossible de s'enregistrer sur le site d'Enedis, alors que mes credentials ont été réinitialisé.
Merci pour votre aide

![2021-02-12 09_46_59-Window](https://user-images.githubusercontent.com/9698870/107747436-b4cde580-6d17-11eb-9b0c-3027aac91f28.png)

**Comment by NicolasColin** [comment]
Bonjour, j'ai exactement le même problème ce jour.
Ca me semble être du côté d' ENEDIS.
Ma version de plugin est la 2.3.2

**Comment by airvb** [comment]
Bjr , tout pareil 
Initialized version 1.2.2, author 'Barberousse'

**Comment by tlarroque** [comment]
Même erreur pour moi. Effectivement cela semble venir d'Enedis.
plugin v2.3.5

**Comment by Bouledogus** [comment]
Comme vous tous, même problème depuis ce matin, le plugin génère une nouvelle demande d'autorisation auprès d'enedis mais celas aboutie vers une erreur 404.

**Comment by grrosminet** [comment]
Ici aussi ...:'(

**Comment by dltrainou** [comment]
ici itou!!! 
 Error: (linky) Connectez-vous à l'adresse https://enedis.domoticz.russandol.pro/device?code xxxxxx, qui envoie sur :
ERREUR 404
La page que vous recherchez n’existe pas.

**Comment by Ratamuse** [comment]
Tout pareil

**Comment by srill** [comment]
Idem

**Comment by JmB11** [comment]
Pareil :
Error: Python Plugin System: (Consommation) Connectez-vous à l'adresse https://enedis.domoticz.russandol.pro/device?code=XXXX-YYYY pour lancer la demande de consentement avec le code XXXX-YYYY
puis 404 derrière...

**Comment by DrMacabre** [comment]
La même.

**Comment by oredin** [comment]
Bonjour,

C'est un problème chez Enedis. Je viens de voir leur notification signalant que l'API Authorize est indisponible.

Il faut donc attendre qu'ils résolvent le problème chez eux.
Dès que j'ai un mail de rétablissement de leur part, je viendrais le signaler.

**Comment by r3z3** [comment]
Same problem here... une belle erreur `404 `

**Comment by guillaumezin** [comment]
![image](https://user-images.githubusercontent.com/541581/107808977-ba085000-6d6a-11eb-8965-41fab6e5cac1.png)

**Comment by gregouille27** [comment]
Merci @guillaumezin pour cette info.

**Comment by seawolffff** [comment]
Plus qu'à patiemment attendre....

**Comment by guillaumezin** [comment]
Et quand tout le monde va remettre sa collecte de données en même temps, ça va être violent pour les serveurs, donc il faut s'attendre à pleins d'erreurs de comm et des quotas qui explosent...

**Comment by dltrainou** [comment]
Bonjour, S’il faut se réenregistrer, on va pas le faire tous au même moment, ça va étaler un peu, non?

 

De : Guillaume Zin <notifications@github.com> 
Envoyé : samedi 13 février 2021 13:53
À : guillaumezin/DomoticzLinky <DomoticzLinky@noreply.github.com>
Cc : dltrainou <dltrainou@free.fr>; Comment <comment@noreply.github.com>
Objet : Re: [guillaumezin/DomoticzLinky] Inscription enedis impossible (#120)

 

Et quand tout le monde va remettre sa collecte de données en même temps, ça va être violent pour les serveurs, donc il faut s'attendre à pleins d'erreurs de comm et des quotas qui explosent...

**Comment by guillaumezin** [comment]
Oui, et le plugin de toute façon ré-étale de lui-même les connexions. Mais le plugin se sert un maximum des données qu'il a déjà en mémoire (cache) pour minimiser les requêtes, là tout le monde va repartir en même temps avec une mémoire vide...

**Comment by ProfBoc75** [comment]
Idem pour moi, même le reset password du site Enedis est à la ramasse, mon compte est vu comme non finalisé, alors que je m'en sers depuis 2018 ...

**Comment by JPGNT** [comment]
On est le 15/02 en fin de journée ... et ça marche pas! :) :)

**Comment by guillaumezin** [comment]
C'est pas ma fôôôôôôôte ;-)

**Comment by dltrainou** [comment]
on est le 16!!! a priori, il tiennent pas leur délai !!!!!!!!!!! o:(

**Comment by mlepannetier** [comment]
Un beau service informatique bien publique chez Enedis...

**Comment by DrMacabre** [comment]
Même l’accès au suivi sur leur site est planté aujourd’hui. De mieux en mieux 😁

**Comment by guillaumezin** [comment]
Ca a subtilement changé :

![image](https://user-images.githubusercontent.com/541581/108066780-1ebff500-7060-11eb-9268-b9e07b41e944.png)

**Comment by guillaumezin** [comment]
![image](https://user-images.githubusercontent.com/541581/108066923-52028400-7060-11eb-81cb-aaad6bc15553.png)

**Comment by Bouledogus** [comment]
Pas bon signe pour un rétablissement rapide :-(

**Comment by Bouledogus** [comment]
Tout semble refonctionner !

**Comment by oredin** [comment]
J'ai eu la notif d'Enedis concernant la remise en service de leur côté.

Maintenant, comme l'a signalé Guillaume, il est possible que le plugin remonte encore des erreurs le temps que tout le monde reprenne progressivement le cours normal de sa récupération de données !

**Comment by usky73** [comment]
reenregistre à l'instant.
le data sont revenus en quelques secondes

**Comment by oredin** [comment]
Petit complément d'infos : Les conssntements ont été supprimés côté Enedis. Il faut donc refaire l'étape de consentement pour pouvoir récupérer vos données.

**Comment by JmB11** [comment]
Reparti après nouveau consentement !

**Comment by guillaumezin** [comment]
Tout est rentré dans l'ordre, et comme déjà indiqué, il faut relancer la procédure de consentement.

**Comment by mlepannetier** [comment]
![image](https://user-images.githubusercontent.com/9698870/108182415-461ecc80-7109-11eb-91a4-f3297b16e793.png)

**Comment by guillaumezin** [comment]
N'hésitez pas à insister, certains utilisateurs ont passé l'erreur "server_error" après 5 ou 6 essais.
