### ISSUE TITLE
relever plusieurs compteur Linky

### ISSUE THREAD

**Issue by philippe27120** [guillaumezin/DomoticzLinky#121]
Bonsoir
Je ne sais pas comment adresser une question, ainsi je passe par ce forum.
Je  me demandai  s'il était possible de remonter plusieurs compteurs Linky, en effet je dois suivre la conso sur 2 logements.
il y a peut être déjà une procédure de publiée ?
merci pour votre attention
Philippe

**Comment by guillaumezin** [comment]
Bonjour,
C'est normalement possible : au moment où le plugin vous renvoie vers le site d'Enedis pour l'obtention du consentement, si vos deux compteurs apparaissent dans votre compte et que vous donnez votre consentement pour ces deux compteurs pour le plugin, ce dernier doit ensuite récupérer automatiquement les données pour ces deux compteurs.
Sinon, vous pouvez sous Domoticz ajouter un deuxième matériel Linky, et quand plugin vous renvoie vers le site d'Enedis pour l'obtention du consentement, vous ouvrez le compte lié au second compteur et donnez le consentement pour celui-ci.
Patientez quelques jours pour essayer, l'infrastructure Enedis est en panne.
Bonne journée.

**Comment by pascal69480** [comment]
Bonjour,
Il suffit de déclarer autant de dispositifs (matériel) qu'il existe de compteurs à relever et pour chacun d'eux effectuer la procédure d'enregistrement.

**Comment by philippe27120** [comment]
Merci pour votre réponse. J essaie. Bonne soirée.

Le lun. 15 févr. 2021 à 08:49, Guillaume Zin <notifications@github.com> a
écrit :

**Comment by guillaumezin** [comment]
Bonjour,
Y arrivez-vous ?

**Comment by philippe27120** [comment]
Bonsoir. Oui. Je m'y suis attelé seulement hier. Ça fonctionne bien, je
remonte les données de trois compteurs. Excusez, j'ai mis du temps à
reprendre le sujet. Le site Enedis était en dérangement et ça m'a découragé
un peu. En tout cas merci du conseil et de votre travail sur ces sujets.
Philippe

Le dim. 7 mars 2021 à 16:47, Guillaume Zin <notifications@github.com> a
écrit :
