### ISSUE TITLE
Pb récupération de données de l'année précédente

### ISSUE THREAD

**Issue by srill** [guillaumezin/DomoticzLinky#123]
Bonjour,
Suite à une mauvaise manip et pour repartir sur une base saine, j'ai supprimé puis réinstallé le plugin (2.3.5).
Tout fonctionne sauf la récupération des données antérieures au delà de Juin dernier. Impossible de pouvoir comparer ma conso avec celle de l'an dernier. dès que je mets un nombre de jours de récupération supérieur à 7 voici l'erreur que j'ai :

 Error: (Linky) durant l'étape getdatahours de 2020-06-21 à 2020-06-28 - Erreur status : 400 - code ADAM-ERR0126 - description : The requested period must be less than 7 days for an access to the load curve. - URI : https://bluecoder.enedis.fr/api-doc/consulter-souscrire

Est-ce normal ou ai-je encore fait des bêtises?
Je vous remercie d'avance
Srill

* Configuration:
  * Domoticz 2020.2
  * Raspbian buster
  * Raspberry Pi 3 B+

----------------------------------------------------------------

**Comment by DrMacabre** [comment]
Bizarre, suite au cafouillage d’enedis d’il y a 15 jours, j’ai aussi supprimé le plugin et remis à zero en demandant 730 jours de données mais c’est très bien passé. T’as bien mis 730 dans la dernière case ? « Nombre de jours pour les autres vues » c’est le maximum autorisé.

**Comment by srill** [comment]
Oui j'ai bien mis 730 mais j'ai cette erreur. Elle disparait quand je reviens en dessous de 7. je ne comprends pas non plus pourquoi il a récupéré les données jusqu’en Juin dernier et qu'il ne veut pas aller plus loin....

**Comment by guillaumezin** [comment]
Bonjour,
J'ai essayé d'augmenter mon nombre de jours (j'ai testé 60) et ça se passe bien.
Le problème ne se pose que pour la période de juin ? Si vous mettez 250 jours par exemple (pour récupérer depuis le 30/06/2020). Ca ressemble à un cafouillage dans leur base de données... Si ça persiste, envoyez moi votre log, comme indiqué dans https://github.com/guillaumezin/DomoticzLinky#les-probl%C3%A8mes-persistent et je verrai si je vois une autre cause possible, ou je remontrai le problème directement à Enedis.

**Comment by srill** [comment]
Bon ben pas de changement... 
Pour le log, désolé mais je suis pas très à l'aise avec Linux donc je trouve le fichier log avec Winscp mais je n'ai pas les droits pour le télécharger.  Pouvez vous me donner la manip pour le récupérer svp?

**Comment by guillaumezin** [comment]
Bonjour,
Connectez-vous par SSH (avec PuTTY par exemple), faites par exemple
`sudo cp /tmp/DomoticzLinky_2021_*.log ~`
`sudo chmod 666 ~/DomoticzLinky_2021_*.log`
Ensuite les fichiers logs devraient être lisibles et effaçables avec Winscp depuis votre répertoire home

**Comment by srill** [comment]
heu.... j'ai essayé la manip...ça fonctionne pas, je l'ai fait 3 fois en copiant vos instructions,je n'ai toujours pas les permissions...je peux donc pas vous envoyer le log

**Comment by guillaumezin** [comment]
Pouvez-vous copier les messages d'erreur que vous rencontrez et/ou poster des captures d'écran ?

**Comment by srill** [comment]
Voila mon soucis:
![Message erreur winscp](https://user-images.githubusercontent.com/23279123/111027676-0a1e1500-83f2-11eb-90ea-734e14af46c7.JPG)
Je ne sais pas si l'image va s'afficher car c'est la première fois que je le fais sur Github

**Comment by felixcharvin** [comment]
Bonjour,
je rencontre exactement le même message d'erreur à partir 150 jours.
Voici les logs:
```
2021-03-14 09:42:42.217 (Linky) Heures creuses désactivées
2021-03-14 09:42:42.217 (Linky) Consommation à montrer sur le tableau de bord mis à value_day / peak_day
2021-03-14 09:42:42.217 (Linky) Nombre de jours à récupérer pour la vue par heures mis à 5
2021-03-14 09:42:42.217 (Linky) Nombre de jours à récupérer pour les autres vues mis à 150
2021-03-14 09:42:42.217 (Linky) Nombre de jours à récupérer pour le calcul du pic mis à 1
2021-03-14 09:42:42.217 (Linky) Debug mis à 0
2021-03-14 09:42:42.223 (Linky) Si vous ne voyez pas assez de données dans la vue par heures, augmentez le paramètre Log des capteurs qui se trouve dans Réglages / Paramètres / Historique des logs
2021-03-14 09:42:42.038 Status: (Linky) Stopping threads.
2021-03-14 09:42:42.038 Status: (Linky) Stopped.
2021-03-14 09:42:42.038 Status: (Linky) Started.
2021-03-14 09:42:42.212 Status: (Linky) Entering work loop.
2021-03-14 09:42:42.213 Status: (Linky) Initialized version 2.3.5, author 'Barberousse'
2021-03-14 09:42:52.242 Status: (Linky) Récupération des données avec l'historique complet
2021-03-14 09:42:52.244 Status: (Linky) Traitement pour le point de livraison 19465846578186
2021-03-14 09:44:45.430 Error: (Linky) durant l'étape getdatahours de 2020-10-18 à 2020-10-25 - Erreur status : 400 - code ADAM-ERR0126 - description : The requested period must be less than 7 days for an access to the load curve. - URI : https://bluecoder.enedis.fr/api-doc/consulter-souscrire
2021-03-14 09:44:55.674 Status: (Linky) Traitement pour le point de livraison 19654992753909
2021-03-14 09:46:57.804 Status: (Linky) Prochaine récupération complète de l'historique : 2021-03-18
2021-03-14 09:46:57.805 Status: (Linky) Prochaine connexion : 2021-03-14 10:46:57
```

J'ai 2 compteurs un des compteurs est remonté jusqu'au 15 octobre et le second est remonté jusqu'au 27 octobre. Je pense que le 27 octobre correspond au moment où j'ai autorisé la collecte des données sur ce compteur.
Pour moi il n'y a pas vraiment de problème, j'ai augmenté le nombre de jours et j'ai pu récupérer mes données jusqu'au 22/07/2020 sur le premier compteur mais à cause du 2eme compteur j'ai le message d'erreur.

Domoticz 2020.2
Raspberry 3

**Comment by guillaumezin** [comment]
Bonsoir,
Si vous allez sur le site d'Enedis, arrivez-vous à avoir vos données avant le 22/07/2020 ? Si ce n'est pas le cas, le plugin ne saura effectivement pas les récupérer non plus.

**Comment by felixcharvin** [comment]
Bonsoir,
après vérification sur enedis sur mon premier compteur je peux remonter jusqu'au 22/07/2020 (celui la OK) par contre sur le 2eme je peux remonter jusqu'à Avril 2020 alors que sur domoticz ca bloque sur le 27 octobre 2020.
De plus depuis ce matin j'ai perdu mon graphique des dernières 24h sur mes 2 compteurs et je n'ai pas fait de modifs.
Pas non plus de message d'erreur dans les logs

**Comment by srill** [comment]
Bonsoir, après vérification sur Enedis, je peux consulter mes données bien plus loin que le 30 Juin de l'an dernier. Par contre je me suis aperçu que la récupération des données ne commence qu'a la date d'activation de la collecte de la consommation horaire...étrange non?
![Enregistrement données](https://user-images.githubusercontent.com/23279123/111353823-f094fb80-8685-11eb-9538-f184a352c47a.JPG)

**Comment by guillaumezin** [comment]
@srill vous décrivez le même comportement que @felixcharvin : les données ne semblent récupérables qu'à partir de la date d'activation de la collecte. Je trouve ça bizarre, je vais poser la question à Enedis.

D'autre part, dans la manip que je vous ai décrite, j'ai changé les propriétés du fichier, mais pas dans /tmp, il faut que vous alliez dans le répertoire /home/pi ou /home/utilisateurquivabien

**Comment by guillaumezin** [comment]
La question est ici si vous avez un compte développeur Enedis : https://datahub-enedis.fr/data-connect/support/forum/topic/donnees-inaccessibles-avant-date-de-collecte/#postid-266

**Comment by seawolffff** [comment]
Bonjour à tous!
Pareil chez moi, plus de données depuis 10 jours et la même erreur, même en mettant les périodes de récupération à 0...
J'ai tenté de resetter l'autorisation en vain.
Log:
2022-04-22 09:27:41.198 Error: Linky: (Linky) durant l'étape getdatahours de 2022-04-15 à 2022-04-22 - Erreur status : 400 - code ADAM-ERR0126 - description : The requested period must be less than 7 days for an access to the load curve. - URI : https://bluecoder.enedis.fr/api-doc/consulter-souscrire

**Comment by seawolffff** [comment]
Bonjour, est  ce quelqu'un a réussi à récupérer à nouveau ses données?

**Comment by guillaumezin** [comment]
De mon côté ça fonctionne sans soucis. Avez-vous également de la production (panneaux solaires par exemple) ? Partagez-vous vos données également avec une autre application que Domoticz ?

**Comment by felixcharvin** [comment]
Pour moi tout est ok de mon coté, graph des 24h et panneaux solaires

**Comment by seawolffff** [comment]
J'ai en effet des panneaux solaires, tout est OK de leur côté. Je n'ai pas d'autres appli qui tourne sauf si on compte mon fournisseur d'électricité mais je n'en ai pas changé depuis décembre.
Quoi que je fasse j'ai toujours cette erreur Adam, même si je mets la récolte des données sur seulement 24h.
________________________________

**Comment by guillaumezin** [comment]
Bonsoir, je fais un peu de ménage, je clos ce ticket sans activité depuis longtemps.
