### ISSUE TITLE
[plugin Linky] Pb lors de l'ajout dans Domoticz

### ISSUE THREAD

**Issue by pop4rt** [guillaumezin/DomoticzLinky#124]
Je voulais utliser votre plugin Linky sous Domoticz mais lorsque je choisis LInky dans la liste des HW, il n'y a aucun champ relatif aux identifiants Enedis. Y-a-t-il des conditions pour afficher ces champs? C'est sur une autre page ?

J'utilise un NAS Synology DS218 et Domoticz 2020.1.
![image](https://user-images.githubusercontent.com/79974873/111423522-bad92c80-86f0-11eb-9b25-1c1339718c07.png)

**Comment by pop4rt** [comment]
Désolé je n'avais pas vu la partie "Obtention du consentement" du wiki.
Par contre, j'ai un autre pb lorsque je valide le partage des données sur Enedis, j'ai cette page vide qui s'affiche : 
https://enedis.domoticz.russandol.pro/auth/redirect/IdPrm=0652431254xxxx&code=server_error&error_description=server_error&

**Comment by guillaumezin** [comment]
Bonjour,
N'hésitez pas à réessayer quelques fois, quitte à attendre un peu, les serveurs de consentement sont tatillons.

**Comment by pop4rt** [comment]
Merci j'ai ressayé et ça a fonctionné ! Merci
Maintenant, j'ai bien des données qui s'affichent par contre j'ai une erreur dans les logs : 
"Async Secure Read Exception: 335544539, short read"
Y-a-t-il un paramètre à adapter pour prévenir de cette erreur ?

**Comment by guillaumezin** [comment]
Non, c'est un bug de Domoticz, typique Synology...

**Comment by guillaumezin** [comment]
Pour être exact, le message est peut-être corrigeable comme je l'avais fait ici : https://github.com/domoticz/domoticz/pull/3926/files
En ajoutant un "(e.value() != 335544539) &&"

mais j'avoue ne pas avoir trop le courage de proposer un patch, vu que je ne peux pas le tester

**Comment by guillaumezin** [comment]
Bonjour,
J'ai poussé un patch dans Domoticz, qui a été accepté, le message d'erreur "Async Secure Read Exception: 335544539, short read" devrait disparaître à partir de la version beta 2020.2 build 13124 ou lors de la sortie de la prochaine version stable 2020.3
