### ISSUE TITLE
Erreur "pas de données disponibles"

### ISSUE THREAD

**Issue by niawag** [guillaumezin/DomoticzLinky#127]
Bonjour et merci beaucoup pour ce plugin bien utile.
En regardant les différentes issues j'ai bien compris que mon problème n'était pas du fait du plugin et qu'il venait de données manquantes sur le site Enedis. Mon problème vient du fait que, lorsque cela se produit, je me retrouve "spammé" de mail indiquant l'erreur. Est-ce possible de faire en sorte de n'être prévenu qu'une fois ou de désactiver complètement la notification par mail pour ce problème ? 

Voici l'erreur reçue : 
```
Multiple errors received in the last 5 minutes:

2021-03-27 21:06:31.091 Error: (Linky) durant l'étape getdatahours de 2021-03-20 à 2021-03-27 - Pas de données disponibles, avez-vous associé un compteur à votre compte et demandé l'enregistrement et la collecte des données horaire sur le site d'Enedis (dans "Gérer l'accès à mes données") ?
2021-03-27 21:06:32.149 Error: (Linky) durant l'étape save de 2021-03-26 à 2021-03-27 - Données manquantes pour mettre à jour le tableau de bord
2021-03-27 21:06:32.149 Error: (Linky) Serveurs inaccessibles à cette heure, prochaine connexion : 2021-03-28 08:15:32
```

**Comment by guillaumezin** [comment]
Bonjour,
J'ai un problème identique depuis jeudi, ça doit venir de la plateforme Enedis effectivement. Par contre, je ne comprends pas votre problème de spam. Le plugin ne fait que mettre des messages dans les logs, il n'envoie pas de mails. Si vous recevez des mails, c'est que vous avez mis en oeuvre un autre mécanisme, avec lequel vous pouvez peut-être filtrer ?

**Comment by niawag** [comment]
Bonjour et merci pour la réponse, j'utilise le système de notification par mail de Domoticz, je ne crois pas qu'il soit possible de filtrer précisément : domoticz m'envoie un mail en cas de notif ou d'erreur dans le log. Ici il s'agit d'une erreur mais je ne vois pas comment demander à domoticz de ne pas m'envoyer de mail relatif à cette erreur seulement.

SI une solution existe je suis preneur!

**Comment by guillaumezin** [comment]
Bonjour,
Pouvez-vous essayer la version 2.3.6 ? J'ai passé beaucoup de message d'erreur en message de status.

**Comment by niawag** [comment]
Bonjour, j'ai mis à jour, merci beaucoup! Je verrai d'ici quelques temps si les données Enedis manquantes entrainent ou non l'envoi de mail.

**Comment by niawag** [comment]
Après quelques temps d'utilisation tout semble ok, je ferme donc l'issue, encore merci pour la prise en compte en la résolution de mon problème!
