### ISSUE TITLE
Données de production mais pas celles de conso depuis qq jours

### ISSUE THREAD

**Issue by Martial83** [guillaumezin/DomoticzLinky#128]
Bonjour et tout d’abord, un grand merci pour ce plugin.
Le plugin a très bien fonctionné depuis le 24 février (après que Enedis m'ai changé pour la 4ième fois mon linky qui refusait de communiquer!), mais depuis le 26 mars, je ne récupère plus que les données de production, celles de conso restent à 0.
En consultation sur le site enedis, tout est OK
Merci pour votre aide.
Domoticz Version 2020.2 build 
Raspberry Raspbian 10

**Comment by guillaumezin** [comment]
Bonjour,
De mon côté, c'est les données de consommation qui ne sont pas remontées pendant quelques jours, et je me demande si le problème n'a pas commencé le 26 mars également, ça refonctionne depuis hier. Je vous propose de surveiller ce qu'il se passe pendant encore quelques jours, c'est probablement un problème d'infrastructure côté Enedis.

**Comment by Martial83** [comment]
Merci pour la réponse.
Je vais attendre patiemment.

Autre point: n'est-il pas possible de récupérer les index vrais du compteur ?

**Comment by guillaumezin** [comment]
Non, l'API Enedis ne le permet pas (encore).

**Comment by Martial83** [comment]
Dommage.
Par le TIC, j'ai les index de conso, mais pas celui de production.
Merci encore une fois.

**Comment by Martial83** [comment]
> 
> 
> Bonjour,
> De mon côté, ce sont les données de consommation qui ne sont pas remontées pendant quelques jours, et je me demande si le problème n'a pas commencé le 26 mars également, ça refonctionne depuis hier. Je vous propose de surveiller ce qu'il se passe pendant encore quelques jours, c'est probablement un problème d'infrastructure côté Enedis.

Bonjour,
Toujours dans le même état: données de production Ok, mais pas celles de consommation.
Comment faire pour diagnostiquer?

Autre question: où puis-je trouver les specifications d'enedis concernant cet interface?
Merci

**Comment by guillaumezin** [comment]
Bonsoir,
Pour le diagnostic, cf. https://github.com/guillaumezin/DomoticzLinky#les-probl%C3%A8mes-persistent
Pour les spécifications Enedis, c'est ici : https://datahub-enedis.fr

**Comment by Martial83** [comment]
Log transmise ce jour.
Merci pour l'API, j'avais bien vu tout ça, mais j'espérais quelque chose de plus simple, ça a vraiment l'air d'un chemin de croix!
Cordialement

**Comment by guillaumezin** [comment]
Merci pour le log, je vais regarder plus en détail, mais ça pourrait être un bug du plugin, il passe très (trop ?) rapidement de la récupération de la consommation à celle de la production.

**Comment by guillaumezin** [comment]
Bonjour,
A priori, il semble en effet qu'Enedis n'envoie pas vos données de consommation. Pour le confirmer, pouvez-vous refaire et m'envoyer un log avec la version 2.3.7 que je viens de publier ? Si cela persiste, relancez la procédure de consentement en mettant le paramètre "Debug" sur "Reset consentement", en cliquant sur "Modifier", en remettant "Debug" sur "Simple" et en recliquant sur "Modifier". Faites bien attention sur la page d'Enedis à partager données de consommation et de production avec le plugin.

**Comment by Martial83** [comment]
Merci pour l'analyse.
J'ai ce message d'erreur au lancement du plugin:
2021-04-10 15:19:09.641  Error: (Linky) durant l'étape getdatahours de 2021-03-27 à 2021-04-03 - Erreur status : 400 - code ADAM-ERR0126 - description : The requested period must be less than 7 days for an access to the load curve. - URI : https://bluecoder.enedis.fr/api-doc/consulter-souscrire

A noter, que j'ai du, il y a quelques jours, renouveler le consentement sur la consommation qui était arrivé à échéance.

**Comment by Martial83** [comment]
Je vous ai envoyé la log, mais maintenant ça marche!

**Comment by Martial83** [comment]
Ca marche mais je n'ai pas récupéré les données entre le 28 février et le 3 avril.
Je pense que ça correspond à une période pendant laquelle le consentement n'était plus valide et ça corrobore une hypothèse que vous avez faite.

**Comment by guillaumezin** [comment]
Du coup on se retrouve avec le même problème que #123, je ferme ce ticket.
