### ISSUE TITLE
erreur apres mise a jour 2.3.7

### ISSUE THREAD

**Issue by rito80** [guillaumezin/DomoticzLinky#130]
bonjour, 
je viens de mettre à jour en 2.3.7 et j ai une erreur que je n 'ai jamais eu auparavant: la voici

2021-04-14 17:42:36.949 Error: Python Plugin System: (linky) durant l'étape getdatapeakdays de 2021-04-13 à 2021-04-14 - Erreur status : 404 - code no_data_found - description : no measure found for this usage point - URI : https://bluecoder.enedis.fr/api-doc/consulter-souscrire

Quelqu 'un à aussi cette erreur ?

je suis sous 
Domoticz V2020.2 (build 13049) (c)2012-2021 GizMoCuz
avec PluginSystem: Started, Python version '3.7.3'.

merci
cordialement
rito80

**Comment by guillaumezin** [comment]
Bonjour,
Effectivement, c'est une régression de la version 2.3.6, je vais le corriger dans les jours qui viennent, merci de l'avoir signalé.

**Comment by rito80** [comment]
bonjour, merci pour ce retour.
et encore félicitations pour le travail réalisé dans ce plugin

**Comment by guillaumezin** [comment]
Voulez-vous essayer la version 2.3.8 ?

**Comment by rito80** [comment]
avec plaisir :)

**Comment by rito80** [comment]
je viens de lancer le git pull, je redemarre domoticz

**Comment by rito80** [comment]
je n 'ai plus l erreur .
la recuperation des données se passe bien :)
