### ISSUE TITLE
erreur plugin Linky suite réinstallation Domoticz

### ISSUE THREAD

**Issue by Moulins58** [guillaumezin/DomoticzLinky#132]
Bonjours, 
Suite à la réinstallation de mon Domoticz , j'ai réinstallé le plugin Linky et apparemment, ca c'est mal passé, j'ai un message d'erreur dans las log.
`2021-04-27 08:55:42.098 Error: Linky: (Linky) 'onMessage' failed 'OverflowError':'date value out of range'.
2021-04-27 08:55:42.098 Error: Linky: (Linky) ----> Line 2128 in '/home/pi/domoticz/plugins/DomoticzLinky/plugin.py', function onMessage
2021-04-27 08:55:42.098 Error: Linky: (Linky) ----> Line 2064 in '/home/pi/domoticz/plugins/DomoticzLinky/plugin.py', function onMessage
2021-04-27 08:55:42.098 Error: Linky: (Linky) ----> Line 1736 in '/home/pi/domoticz/plugins/DomoticzLinky/plugin.py', function handleConnection
2021-04-27 08:55:42.098 Error: Linky: (Linky) ----> Line 1404 in '/home/pi/domoticz/plugins/DomoticzLinky/plugin.py', function calculateDaysLeft` 
Que faire?

**Comment by djpostka** [comment]
Tu est sur le PDL du linky, on dirait qu'il n'arrive pas a récupérer des valeurs plus anciennes, essaye de changer la valeur "Nombre de jours à récupérer pour les autres vues (730 max)" et "Nombre de jours à récupérer pour la vue par heures" en la mettant à 1.

**Comment by Moulins58** [comment]
Problème résolu,  j'avais coché consommation et production en autorisation
chez Enedis.
Bonne journée.

Henri LAUNAY

**Comment by guillaumezin** [comment]
Bonjour,
Pouvez-vous essayer de mieux décrire le problème que vous avez rencontré et sa résolution ? Je ne suis pas certain de bien comprendre, et je voudrais voir si ça vaut le coup de le documenter.
Merci.

**Comment by Moulins58** [comment]
J'ai été obligé de réinstaller complètement mon Domoticz .
Lorsque j'ai réinstallé le plugin Linky, ça c'est bien passé, ou je me suis
trompé c'est dans l'autorisation Enedis et je le savais , pourquoi avoir
fait l'erreur...
J'ai deux compteurs, un en consommation et l'autre en production. Celui de
production remonte déjà chez BDPV et si il n'y a pas de nouveau chez
Enedis, nous ne pouvons récupérer qu'une seule fois un compteur.
Et en demandant l'autorisation chez Enedis, j'ai coché les deux
consommation et production et la, blocage , erreur dans les logs et aucune
remontées .
Cordialement

*Henri LAUNAY                                              *
58 rue de Curette
44119 Grandchamp des Fontaines
Tél: 0629428345



Le jeu. 29 avr. 2021 à 08:47, Guillaume Zin ***@***.***> a
écrit :

**Comment by guillaumezin** [comment]
Ok, je comprends mieux, votre question sur la remontée chez BDPV est toujours ouverte, sans réponse, sur le forum de support d'Enedis. Ils ne répondent pas aux messages en ce moment...
