### ISSUE TITLE
Erreur 404 demande de consentement

### ISSUE THREAD

**Issue by DocteurNerd** [guillaumezin/DomoticzLinky#135]
Bonjour,

Tout d'abord merci beaucoup pour tout ce travail !
Je n'arrive malheureusement pas à faire fonctionner le plugin, (Domoticz version 2021.1) lorsque je récupère le lien pour la demande de consentement, j'arrive à une erreur 404.
Je n'ai pas l'impression d'oublier quoi que ce soit, mon compte Enedis existe depuis plusieurs mois, mon compteur y est bien accroché et j'y trouve mes relevés.

Merci par avance pour toute aide !

Cordialement,

DrNerd

**Comment by mlepannetier** [comment]
Bonjour,

Idem ;)

**Comment by guillaumezin** [comment]
Bonsoir,
Est-ce que ça a déjà fonctionné par le passé ? Réessayez quelque fois, il y a eu peut-être surcharge des serveurs.

**Comment by didi31** [comment]
Bonjour 
idem pour moi
Aujourd'hui j'ai une erreur "Internal server error" sur lesite russandol

**Comment by guillaumezin** [comment]
Bonjour, avez-vous toujours ces problèmes ?

**Comment by titis14** [comment]
Je suis passé sous home assistant 😄

**Comment by guillaumezin** [comment]
Bonsoir, je fais un peu de ménage, le plugin a beaucoup évolué depuis, je clos ce ticket sans activité depuis longtemps, vous le rouvrirez si le problème existe toujours.

**Comment by didi31** [comment]
Bonsoir
Pas de problème. Je suis passé sur home assistant.

25 janv. 2024 20:54:10 Guillaume Zin ***@***.***>:
