### ISSUE TITLE
Erreur consentement

### ISSUE THREAD

**Issue by Kirioss** [guillaumezin/DomoticzLinky#138]
Bonjour, 

Domoticz : 2021.1
DomoticzLinky : 2.3.8

Pendant la demande de consentement, j'obtiens le message d'erreur ci-dessous (après la validation du consentement sur le site Enedis)

Error Logging In
Il y a eu une erreur en essayant d'obtenir un jeton d'accès du service

{
  "reasons" : [ ],
  "details" : {
    "msgId" : "Id-8873b8600d1a91dd1e85c08f"
  }
}

Et dans les logs Domoticz : 
2021-06-03 08:15:41.199 Error: Linky: (Linky) durant l'étape : parseaccesstoken - Erreur status : 400 - code invalid_grant
2021-06-03 08:15:41.216 Error: Linky: (Linky) durant l'étape : parseaccesstoken - Le plugin va être arrêté. Relancez le en vous rendant dans Configuration/Matériel, en cliquant sur le plugin puis sur Modifier. Surveillez les logs pour obtenir le lien afin de renouveler le consentement pour la récupération des données auprès d'Enedis

**Comment by syrhus** [comment]
Idem, même problème.

**Comment by ogulf** [comment]
Idem chez moi

**Comment by guillaumezin** [comment]
Bonjour,
Il va falloir être patient, il y a une avarie chez Enedis:

![image](https://user-images.githubusercontent.com/541581/120841688-20102180-c56c-11eb-8037-93ba7493260e.png)

**Comment by cyrildu17** [comment]
Je les ai contacté a ce propos aujourd'hui et ils reviennent vers moi dès qu'ils ont débloqué la situation

**Comment by Miloune** [comment]
Une question me taraude suite à ce problème... Pourquoi faut-il redonner son consentement sachant que quand on le fait la 1ère fois c'est marqué que l'autorisation se fait pour 3 ans ?

**Comment by guillaumezin** [comment]
Pour répondre rapidement, parce que c'est mal fichu. Pour être plus complet, l'infrastructure Enedis a planté, le plugin a interprété le code d'erreur renvoyé par Enedis comme une erreur de clé invalide et en a déduit qu'il fallait recommencer le consentement. Il y a sans doute moyen de faire mieux, mais c'est compliqué de savoir et tester ces cas limites qui ne sont pas documentés...

**Comment by usky73** [comment]
Merci à vous de tenter de faire marcher ce truc.
ENEDIS est vraiment pas au niveau.

**Comment by Kirioss** [comment]
Dommage que Enedis n'ait pas les mêmes problèmes pour la collecte de nos conso... 😂

**Comment by KissKool-63** [comment]
Même problème ! J'en profite pour dire merci aux auteurs du plugin ! ;)

**Comment by guillaumezin** [comment]
> J'en profite pour dire merci aux auteurs du plugin ! ;)

De rien. J'avoue que je me serai bien lancé à écrire le même genre de plugin pour Gazpar, mais pour le bien de ma famille, je ne ferai pas ;-)

**Comment by Patbonamy** [comment]
Toujours en panne!!!
Merci au développeur.

**Comment by oredin** [comment]
Bonjour,

Pour info, l'infra Enedis a des problèmes de charge qui expliquent en grande partie les problèmes rencontrés.
La mauvaise nouvelle, c'est que j'ai reçu un mail de l'équipe en charge des webservices et il apparaît que ce sont les requêtes provenant du plugin qui génèreraient la surcharge de l'infra.

Je vais continuer à échanger avec eux (et avec Guillaume) pour voir comment on peut débrouiller le sujet et faire en sorte que le plugin puisse fonctionner sans faire tomber leur plateforme.

Je posterais un message dès que j'aurais des news sur le sujet.

**Comment by DavidTre07** [comment]
Bonsoir,
mauvaise nouvelle :(
Surement une infra mal dimensionnée pour répondre aux requêtes ou un design pas scalable.

On est si nombreux que ça à faire des requêtes ?
Car quand on voit le volume de données par personne ça me parait pas peser pas énorme...

En tout cas merci aux dev pour tout votre travail et surtout merci de s'occuper du problème !

**Comment by oredin** [comment]
Petite update d'hier soir de la part d'Enedis précisant que le problème provenait aussi d'une forte utilisation de l'appli mobile "Enedis à mes côtés".

On n'était pas les seuls fautifs ! :)

Normalement, ils ont déployé unn correctif hier soir qui est censé améliorer les choses.

Il ne reste plus qu'à voir si c'est bien le cas. Pour le moment, je n'ai pas eu de nouvelles de l'équipe Enedis concernant la consommation excessive du plugin sur leur plateforme.

Wait'n see !

**Comment by guillaumezin** [comment]
De mon côté, je vais proposer 2 évolutions dans les jours qui viennent:
- Côté infrastructure (donc pour toi @oredin) une vérification de version du plugin qui demandera aux versions trop anciennes de se mettre à jour. Les versions plus récentes mettent les données en cache et mangent moins de bande passante
- Côté plugin, la sauvegarde et la restitution du cache, du coup même en cas de plantage, etc, ça évitera que le plugin essaie de récupérer trop de données.

**Comment by ogulf** [comment]
Super, merci à vous !

Perso, je trouve un peu léger de la part d'Enedis de dire que ça vient du plugin les pb de surcharge... Même s'ils viennent de relativiser.
On parle de quoi ?.... 1000.... 2000 utilisateurs ?
Et si c'est vraiment la cause.... Je ne dis pas Bravo à Enedis !!!

**Comment by guillaumezin** [comment]
Oui, ça me surprend aussi, je leur ait dit, on est dans les 1000 utilisateurs. Après, le plugin est un peu bourrin, et je ne suis pas du tout un spécialiste du dimensionnement réseau (ni du Python, ni du PHP, etc.).

**Comment by guillaumezin** [comment]
@oredin Peux-tu regarder ce commit et me dire ce que tu en penses?
https://github.com/guillaumezin/Device-Flow-Proxy-Server/commit/8f0edc8e1d422d1e2448b2e5081f135b613f4d4e
Avec ça, normalement, tu peux mettre dans le fichier .env un paramètre VERSION_MIN par exemple à 2.3.3 (version à laquelle le cache est apparu) et les utilisateurs avec des versions plus anciennes seraient priés de mettre à jour.

**Comment by guillaumezin** [comment]
Bonsoir,
Je viens de publier une version 2.3.9 qui sauvegarde le cache sur disque et le réutilise au maximum pour diminuer les appels vers Enedis, si vos retours sont positifs, on poussera tout le monde à l'utiliser, de mon côté ça a l'air de fonctionner.

**Comment by DrMacabre** [comment]
Salut, je vois un premier problème avec cette nouvelle version, elle ne se connecte qu’à 8h50 et donc impossible d’avoir l’url pour la lier à enedis sauf en étant devant le log à ce moment-là. 🤔

**Comment by DrMacabre** [comment]
Bonjour,

Ça marche avec la dernière version. Merci encore.

**Comment by oredin** [comment]
> @oredin Peux-tu regarder ce commit et me dire ce que tu en penses?
> [guillaumezin/Device-Flow-Proxy-Server@8f0edc8](https://github.com/guillaumezin/Device-Flow-Proxy-Server/commit/8f0edc8e1d422d1e2448b2e5081f135b613f4d4e)
> Avec ça, normalement, tu peux mettre dans le fichier .env un paramètre VERSION_MIN par exemple à 2.3.3 (version à laquelle le cache est apparu) et les utilisateurs avec des versions plus anciennes seraient priés de mettre à jour.

Hello, j'essaie de regarder dans la journée si j'ai un trou côté boulot et je te tiens au courant.

**Comment by ogulf** [comment]
Je viens de tester la 2.3.9 (git pull, log OK, log domoticz OK) mais j'ai toujours un KO sur le consentement Enedis...

Log Domoticz :
```
2021-06-15 11:30:32.851 Linky hardware started.
2021-06-15 11:30:32.850 Status: Linky: (Linky) Entering work loop.
2021-06-15 11:30:32.851 Status: Linky: (Linky) Started.
2021-06-15 11:30:33.830 Linky: (Linky) Heures creuses mises à 22h30-6h30
2021-06-15 11:30:33.830 Linky: (Linky) Consommation à montrer sur le tableau de bord mis à value_cmonth / peak_day
2021-06-15 11:30:33.831 Linky: (Linky) Nombre de jours à récupérer pour la vue par heures mis à 7
2021-06-15 11:30:33.831 Linky: (Linky) Nombre de jours à récupérer pour les autres vues mis à 32
2021-06-15 11:30:33.831 Linky: (Linky) Nombre de jours à récupérer pour le calcul du pic mis à 1
2021-06-15 11:30:33.831 Linky: (Linky) Debug mis à 0
2021-06-15 11:30:33.839 Linky: (Linky) Pas de cache trouvé sur le disque
2021-06-15 11:30:33.839 Linky: (Linky) Si vous ne voyez pas assez de données dans la vue par heures, augmentez le paramètre Log des capteurs qui se trouve dans Réglages / Paramètres / Historique des logs
2021-06-15 11:30:33.820 Status: Linky: (Linky) Initialized version 2.3.9, author 'Barberousse'
2021-06-15 11:30:42.073 Status: Linky: (Linky) Récupération des données avec l'historique court
2021-06-15 11:30:42.284 Error: Linky: (Linky) Connectez-vous à l'adresse https://enedis.domoticz.russandol.pro/device?code=xxxx
```

Retour Enedis :
```
server_error
lincs-internal-server-error
```

**Comment by guillaumezin** [comment]
Enedis a annoncé que l'incident était résolu. Il y a peut-être juste beaucoup de monde à refaire l'étape de consentement, n'hésitez pas à réessayer.

**Comment by DrMacabre** [comment]
Ici ça marche mais ça n'a récupéré des données que jusqu'au 9 juin  et j'ai un gros trou entre le 31 mai et le 7 juin. Pourtant j'ai demandé de récupérer 15 jours dans les paramètres du plug. C'est normal ?

**Comment by DavidTre07** [comment]
Chez moi ça marche mais moi aussi un gros trou entre le 30 mai et 4 juin.

**Comment by guillaumezin** [comment]
Vous pouvez allonger le nombre de jours l'historique (paramètre "Nombre de jours à récupérer pour les autres vues"), le plugin réessaiera de temps en temps de récupérer plus de données, ça peut prendre quelques jours (il indique s'il essaie de récupérer "l'historique court" ou "l'historique complet", il se limite à 7 jours quand il récupère l'historique court et n'essaie que de temps en temps de récupérer plus, pour ne pas surcharger).

**Comment by guillaumezin** [comment]
J'ajoute que quand vous n'aurez plus de trous dans vos données, je recommande fortement de remettre le paramètre "Nombre de jours à récupérer pour les autres vues" à 7.

**Comment by DavidTre07** [comment]
OK, je tente et je vous dirais. Merci.

**Comment by pascal69480** [comment]
Hello,
Merci pour votre veille qui a permis de détecter ce problème et de pousser une nouvelle version du plugin..
J'ai fait un pull du plugin et regénéré une demande d'autorisation.
J'arrive bien chez Enedis mais au lieu de l'erreur que j'avais avant (server_error lincs-internal-server-error) je tombe désormais sur une erreur 500 chez russandol lorsque je valide le consentement :
Cette page ne fonctionne pasImpossible de traiter cette demande via enedis.domoticz.russandol.pro à l'heure actuelle.
HTTP ERROR 500

Une idée ?

**Comment by oredin** [comment]
> @oredin Peux-tu regarder ce commit et me dire ce que tu en penses?
> [guillaumezin/Device-Flow-Proxy-Server@8f0edc8](https://github.com/guillaumezin/Device-Flow-Proxy-Server/commit/8f0edc8e1d422d1e2448b2e5081f135b613f4d4e)
> Avec ça, normalement, tu peux mettre dans le fichier .env un paramètre VERSION_MIN par exemple à 2.3.3 (version à laquelle le cache est apparu) et les utilisateurs avec des versions plus anciennes seraient priés de mettre à jour.

Je viens de tester la modif du proxy sur mon instance de test. Avec un vieux plugin, j'ai bien eu le message me demandant de mettre à jour. Après MAJ, j'ai pu récupéré les données.

J'ai donc passer les modifs en prod sur le proxy.

**Comment by pascal69480** [comment]
Yepee yaheee !

Le consentement a bien été obtenu pour le plugin DomoticzLinky ! Vous pouvez fermer cette page et retourner sur Domoticz.

👏

**Comment by Kirioss** [comment]
Hello

Tout refonctionne correctement pour moi aussi, j'attends quelques jours pour voir si les trous se remplissent bien

Merci pour la correction !

**Comment by ogulf** [comment]
Consentement à nouveau opérationnel (plugin 2.3.9) :-)
En attente du chargement des jours manquants.

**Comment by guillaumezin** [comment]
J'ai corrigé dans la version 2.4.0 un bug sur la date de fin qui peut expliquer les jours manquants. Je ferme le ticket, si vous n'arrivez pas à récupérer les trous de données, ouvrez un autre ticket svp.
