### ISSUE TITLE
Erreur suite à mise à jour

### ISSUE THREAD

**Issue by DrMacabre** [guillaumezin/DomoticzLinky#139]
Bonjour, suite à l’absence de données depuis samedi, j’ai mis à jour le plugin via git pull et lorsque j’essaye de relier mon compteur, j’ai ce message d’erreur sur le site d’enedis

Il y a eu une erreur en essayant d'obtenir un jeton d'accès du service

{
  "reasons" : [ ],
  "details" : {
    "msgId" : "Id-d380b860c1cda18febfac6a2"
  }
}
Domoticz version 2021.1 13300
Plugin : 2.3.8

même erreur 400 dans les logs que le ticket précédent.

**Comment by guillaumezin** [comment]
Cf. #138
