### ISSUE TITLE
Remonter des données de production

### ISSUE THREAD

**Issue by PhilBilly1964** [guillaumezin/DomoticzLinky#14]
Bonjour,

A la maison, j'ai 2 compteurs un compteur consommation, et pour celui-ci tout marche nickel un grand merci pour le programme.

Ma question est pour le compteur production, j'ai des panneaux sur le toit et j'aimerai pouvoir remonter les données sur Domotics pour en particulier mettre une alarme quand j'ai une production à 0 sur une journée... (pour m'avertir par exemple que le disjoncteur de production à sauter!)

Pouvez-vous créer se développement?

les données à récupérer sont :
https://espace-client-particuliers.enedis.fr/group/espace-particuliers/mes-donnees-de-production-prod
Et nous pouvons récupérer uniquement les données par jour pas par heure.

Merci d'avance
Philippe

**Comment by guillaumezin** [comment]
Bonjour,

N'ayant moi-même pas de compteur de production, il m'est difficile de développer la fonction. A la rigueur ce serait possible si quelqu'un qui a comme vous acceptait de partager son login et mot de passe avec moi, mais ça m'embête, d'autant qu'après le développement, je vais avoir besoin régulièrement des accès pour le support quand des bugs me seront remontés.

Il y a un autre développeur qui a pris mon code et l'a modifié pour gérer la partie production : https://github.com/krotof1a/DomoticzLinkyProd, je surveille ce qu'il fait et quand ce sera mature, je lui proposerai de fusionner le tout dans un seul projet.

**Comment by PhilBilly1964** [comment]
Bonjour, 


J’ai essayé et tout fonctionne les compteurs de consommation et production, nickel ! 







Merci 


----- Mail original -----

De: "Guillaume Zin" <notifications@github.com> 
À: "guillaumezin/DomoticzLinky" <DomoticzLinky@noreply.github.com> 
Cc: "PhilBilly1964" <phil.ducret@free.fr>, "Author" <author@noreply.github.com> 
Envoyé: Dimanche 2 Juin 2019 20:15:35 
Objet: Re: [guillaumezin/DomoticzLinky] Remonter des données de production (#14) 


Bonjour, 
N'ayant moi-même pas de compteur de production, il m'est difficile de développer la fonction. A la rigueur ce serait possible si quelqu'un qui a comme vous acceptait de partager son login et mot de passe avec moi, mais ça m'embête, d'autant qu'après le développement, je vais avoir besoin régulièrement des accès pour le support quand des bugs me seront remontés. 
Il y a un autre développeur qui a pris mon code et l'a modifié pour gérer la partie production : https://github.com/krotof1a/DomoticzLinkyProd , je surveille ce qu'il fait et quand ce sera mature, je lui proposerai de fusionner le tout dans un seul projet.

**Comment by guillaumezin** [comment]
Je ferme le ticket du coup, si un jour j'ai le temps, je fusionnerai les travaux
