### ISSUE TITLE
blocage données manquantes

### ISSUE THREAD

**Issue by dltrainou** [guillaumezin/DomoticzLinky#142]
Bonjour, ça faisait trop longtemps sans problème!!!
il y a quelques jours,dans le log de domoticz, il m’était demandé de mettre a jour le plugin, ce que j'ai fait en allant le chercher ici, et le téléchargeant en zip et mis dans le bon répertoire avec les droits qui vont bien.
C'est reparti sans problème mais depuis la récupération journalière ne se fait plus (depuis 5 jours) avec le msg 
erreur (linky) durant l'étape save de 2021-06-18 à 2021-06-19 - Données manquantes pour mettre à jour le tableau de bord.
le date est toujours celle de la veille au jour courant. sur Enedis les données sont bien présentes et l'envoi données activé.
J'ai 2 compteurs, le pb identique est sur  les 2.
ci joint le log , merci d'avance du coup de main. bonne journée

**Comment by Bartras** [comment]
Bonjour,
Je confirme être dans le même cas.
Plus de mise à jour depuis le 15 juin 23h.
Je précise que le problème est présent sur une install avec la mise à jour et sur une autre où je n'ai pas fait la mise à jour.
Bonne journée.

**Comment by dltrainou** [comment]
bon!!!! c'est reparti sans rien toucher, sauf plugin en debug. Dernière donnée Vendredi 18 à 0h!!! wait and see.

**Comment by guillaumezin** [comment]
Je crois avoir réussi à reproduire le problème, et il n'a l'air de se produire que quand le cache de données est vide, c'est pour cela qu'il semble intermittent.

**Comment by guillaumezin** [comment]
Ce devrait être corrigé en version 1.4.0

**Comment by dltrainou** [comment]
Ok merci , bonne journée

 

De : Guillaume Zin ***@***.***> 
Envoyé : samedi 19 juin 2021 15:24
À : guillaumezin/DomoticzLinky ***@***.***>
Cc : dltrainou ***@***.***>; Author ***@***.***>
Objet : Re: [guillaumezin/DomoticzLinky] blocage données manquantes (#142)

 

Ce devrait être corrigé en version 1.4.0
