### ISSUE TITLE
mise à jour du plugin

### ISSUE THREAD

**Issue by brio78** [guillaumezin/DomoticzLinky#143]
Bonjour
Mon plugin ne marche plus car il est trop ancien
Si je fais une mise à jour par un git pull j'obtiens ;

pi@pi-domoticz:~/domoticz/plugins/DomoticzLinky $ git pull
Votre information de configuration indique de fusionner avec la référence 'refs/heads/datahub' du serveur distant, mais cette référence n'a pas été récupérée.

Pourriez vous m'aider, que dois je faire ?
raspberry pi 3 

merci

jf briois

**Comment by guillaumezin** [comment]
Bonjour, si vous faite "git fetch" avant "git pull", qu'est-ce que ça donne ?

**Comment by brio78** [comment]
Bonsoir,voici ce que j'obtiens
![image](https://user-images.githubusercontent.com/15893884/122653022-40320a00-d142-11eb-8930-208765ced30c.png)

**Comment by guillaumezin** [comment]
Bonjour, essayez ceci :
```
git remote prune origin
git fetch origin
git checkout master
git pull
```

**Comment by brio78** [comment]
Bonjour,
J'ai supprimé le répertoire DomotizLinky et ensuite j'ai rechargé le plugin et ca marche
merci pour votre aide
jf briois
