### ISSUE TITLE
Impossible to approve connexion from serveur

### ISSUE THREAD

**Issue by Holborn13200** [guillaumezin/DomoticzLinky#145]
server_error
lincs-internal-server-error

**Comment by afer92** [comment]
Même chose pour moi.

**Comment by oeildefeu** [comment]
même chose ici avec le plugin fraîchement mis à jour.

**Comment by guillaumezin** [comment]
Bonsoir, il faut parfois insister, avez-vous toujours cette erreur ?

**Comment by oeildefeu** [comment]
Bonsoir,
nouvelle tentative ce soir, avec succès au deuxième essai.
Après l'affichage du message d'erreur, j'ai fait retour en arrière puis j'ai revalidé... ça a marché. Les fois d'avant je n'ai pas fait ça. J'ai relancé tout le processus. Je ne suis pas convaincu que ce changement de procédure soit la source de la réussite de ce soir ...
