### ISSUE TITLE
Erreur status : 403 - code ADAM-DC-0008

### ISSUE THREAD

**Issue by PatPel42** [guillaumezin/DomoticzLinky#149]
Bonjour,
Je teste régulièrement et j'ai toujours cette Erreur status : 403 - code ADAM-DC-0008 malgré un consentement Enedis qui semble être accepté. Ci joint Log Domoticz.
Merci pour votre aide
[DomoticzLinky_2021_05_31_15_13_18_roe8vwtp.log](https://github.com/guillaumezin/DomoticzLinky/files/6570507/DomoticzLinky_2021_05_31_15_13_18_roe8vwtp.log)

_Originally posted by @PatPel42 in https://github.com/guillaumezin/DomoticzLinky/issues/131#issuecomment-851488864_

**Comment by guillaumezin** [comment]
Bonjour,
C'est toujours le cas avec la dernière version du plugin ? Je vois que votre log date du 31/05, Enedis a déployé des mises à jour depuis.

**Comment by PatPel42** [comment]
Bonjour,
Je viens de retester après mise à jour du plugin et j'ai toujours le même problème
[DomoticzLinky_2021_07_24_12_53_37_f6l8md8e.log](https://github.com/guillaumezin/DomoticzLinky/files/6872311/DomoticzLinky_2021_07_24_12_53_37_f6l8md8e.log)

**Comment by guillaumezin** [comment]
Est-ce que vous partagez vos données à un autre service ou une autre application, sur Smartphone par exemple ?

**Comment by PatPel42** [comment]
Je suis 3 Linky, 2 de consommation et un de production. Seul le production a le problème. Il est partagé avec le site BDPV. Les 2 Production sont aussi partagés sur Ecolyo et il  n'y a pas de soucis. Ce sont des sites Web qui mettent les données en forme. C'est pour les supprimer que je teste Domoticz afin d'avoir qu'un seul support.

**Comment by guillaumezin** [comment]
Cela ressemble au problème décrit dans #116

**Comment by guillaumezin** [comment]
Bonsoir,
D'après Enedis, vous ne devriez pas rencontrer de problème. Refaites peut-être le consentement, vérifiez que vous donnez bien votre consentement pour la consommation ET la production.

**Comment by guillaumezin** [comment]
Bonsoir, je fais un peu de ménage, le plugin a beaucoup évolué depuis, je clos ce ticket sans activité depuis longtemps, vous le rouvrirez si le problème existe toujours.
