### ISSUE TITLE
Auto héberger son proxy

### ISSUE THREAD

**Issue by Elerir** [guillaumezin/DomoticzLinky#155]
Bonjour,

Serait il possible de partager comment l'authentification côté proxy est réalisée auprès d'enedis? J'ai du mal à comprendre pourquoi cela nécessite un proxy intermédiaire, et si c'est le cas j'aimerais pouvoir le déployer sur mon serveur
De plus, rendre la partie proxy publique permettrait de t'éviter d'avoir à financer ce serveur dédié 

Merci !

**Comment by Elerir** [comment]
En fouillant ton github j'ai pu remarquer que tu avais déjà publié les sources, il serait bon de le mentionner dans le readme du coup
Merci à toi

**Comment by guillaumezin** [comment]
> il serait bon de le mentionner dans le readme
Bonjour, j'y fait brièvement allusion dans https://github.com/guillaumezin/DomoticzLinky#auteurs
