### ISSUE TITLE
Devices introuvables

### ISSUE THREAD

**Issue by southmind** [guillaumezin/DomoticzLinky#156]
J'ai utilisé ce plugin pendant plusieurs mois puis il a cesser de fonctionner. Comme je devais changer de fournisseur, j'ai simplement effacé le plugin dans "Matériel". Je tente depuis de le réactiver sans succès. J'ai réinstallé le plugin dans Domoticz, créé  un nouveau matériel (Compteur Linky) , autorisé l'enregistrement dans Enedis mais aucun device compteur n'apparait dans les dispositifs, bien que le plugin soit activé et qu'il m'indique que les devices associés ont été crée... Une recherche par type de matériel ne voit rien non plus. Je ne comprend pas le pb ...

**Comment by pbda** [comment]
Je viens d'avoir le même problème. Comme je voulais récupérer l'historique de consommation, j'ai mis le paramètre historique à 730. Du coup, la récupération des données est très longue (> 10 mn) et le device n'apparait pas de suite. En fait, il suffisait d'attendre...

**Comment by southmind** [comment]
Merci; même en attendant ca ne me semble pas vouloir créer le device; pourtant j'ai bien le fichier log associé au plugin qui se crée... Bien je vais le laisser tourner 24 h pour voir si un miracle se produit. Merci quand même.

**Comment by guillaumezin** [comment]
Bonjour,
Mettre le paramètre historique à 730 est très très risqué ! Commencez par le mettre à 15j par exemple, et si ça fonctionne, c'est bien là que se situe le problème. Quand on demande trop de données à Enedis, ça risque de finir en erreur.

**Comment by guillaumezin** [comment]
Si le problème persiste, suivez https://github.com/guillaumezin/DomoticzLinky#les-probl%C3%A8mes-persistent

**Comment by guillaumezin** [comment]
Sur les dernières versions du plugin, ce devrait être plus stable, le plugin n'essaie pas à chaque fois les 730 jours pour éviter de surcharger les serveurs, je considère le problème comme clos.
