### ISSUE TITLE
Plus de relevés depuis le 7 novembre

### ISSUE THREAD

**Issue by francouai** [guillaumezin/DomoticzLinky#158]
Bonjour!
depuis environ le 10 novembre, je ne recupere plus les infos d'enedis .
pourtant, apres revérification, la collecte de la consommation horaire est bien activée.
j'avoue de plus savoir quoi faire.

**Comment by MuadDibVV** [comment]
Bonjour,
Idem de mon coté : 
2021-11-23 20:29:12.899 Error: [...] durant l'étape getdatahours de 2021-11-16 à 2021-11-23 - Erreur status : 400 - code ADAM-ERR0126 - description : The requested period must be less than 7 days for an access to the load curve. - URI : https://bluecoder.enedis.fr/api-doc/consulter-souscrire

**Comment by francouai** [comment]
J'ai refait une installation au propre en supprimant les anciens fichiers et c'est reparti mais ca c'est encore arrêté au 22 alors que nous sommes le 24.
donc ca bloque encore.

**Comment by guillaumezin** [comment]
Bonjour,
Vos courbes sont bien visibles sur le site d'Enedis ? Vous pouvez m'envoyer vos logs en suivant la procédure décrite dans https://github.com/guillaumezin/DomoticzLinky#les-probl%C3%A8mes-persistent

**Comment by empierre** [comment]
pour ma part, on a viré mon compteur de mon compte et depuis impossible de
le faire rajouter...

**Comment by MuadDibVV** [comment]
> Bonjour, Vos courbes sont bien visibles sur le site d'Enedis ? Vous pouvez m'envoyer vos logs en suivant la procédure décrite dans https://github.com/guillaumezin/DomoticzLinky#les-probl%C3%A8mes-persistent

Merci pour la remarque : j'aurais du y penser, toutes mes excuses...
La dispo des données horaires est à renouveller tous les ans ! J'ai fait la demande de réactivation => j'attends la prise en compte

**Comment by guillaumezin** [comment]
@MuadDibVV je me suis fait avoir aussi, et d'autres utilisateurs également, le code d'erreur est abscons, ça génère des tickets pour rien

**Comment by guillaumezin** [comment]
@empierre il faut demander au support Enedis, vous êtes un peu à l'origine de ce plugin, avez-vous un compte sur https://datahub-enedis.fr/data-connect/support ?
