### ISSUE TITLE
ERREUR 404 lors de la demande de consentement de partage de données enedis

### ISSUE THREAD

**Issue by hokrai** [guillaumezin/DomoticzLinky#159]
Bonjour,

Tout est dans le titre :-)
url : https://mon-compte-particulier.enedis.fr/dataconnect/v1/oauth2/authorize/?response_type=code&client_id=xxxxxx&state=xxxxx&duration=P3Y

**Comment by guillaumezin** [comment]
Bonsoir,
Le problème est nouveau ? Systématique ? Un utilisateur avait un problème similaire et c'était ses paramètres DNS (résolution de noms Internet) qui étaient en cause.

**Comment by hokrai** [comment]
Bonsoir,

Pas de problème DNS il me semble.
La redirection se fait sur le portail enedis pour le consentement.
Je me loge sur le site enedis.
Une fois connecté, la 404 apparait sur le site enedis .......
Pas sur tout le site, juste sur la frame du milieu pour valider le consentement.

**Comment by hokrai** [comment]
<img width="1626" alt="Capture d’écran 2021-11-25 à 20 54 23" src="https://user-images.githubusercontent.com/36192077/143494919-39aaa298-d6ee-4b1a-9956-063192f28b28.png">

**Comment by hokrai** [comment]
Ca fonctionnait bien avant ...
Il y a deux trois semaines ... Impossible de télécharger les datas...
Désinstallation pllugin ....... réinstallation .......
Et depuis impossible d'activer le partage de données.
Je doute que cella vienne du plugin ..... mais je poste au cas ou .......

**Comment by toonsmil** [comment]
pareil chez moi

**Comment by guillaumezin** [comment]
Bonsoir, je pense que le problème se situe plus du côté d'Enedis, c'est toujours identique ?

**Comment by toonsmil** [comment]
Bonjour et bonne année , en effet cela devait venir de chez Enedis car apres plusieurs essais (sur plusieurs jours) c'est reparti sans rien toucher dans domoticz ni au plugin
