### ISSUE TITLE
Heure Pleine et heure creuse

### ISSUE THREAD

**Issue by darkpotpot** [guillaumezin/DomoticzLinky#16]
Bonjour,

Serait il possible de faire la différenciation entre les heures pleines et les heures creuses ?

Cordialement

Julien

**Comment by guillaumezin** [comment]
Bonjour,

Je n'ai pas l'option, je ne me rends pas compte. Les données HP/HC apparaissent clairement sur le site d'Enedis ? Pouvez-vous me faire des captures d'écran ?

**Comment by darkpotpot** [comment]
Bonjour,

je viens d'aller voir sur le site et en effet il n'y a pas la distinction entre les 2... J'avoue ne pas avoir fait attention à cela vu qu'auparavant j'utilisais directement la teleinfo pour récupérer mes infos de consommation. Désolé.

Par contre vu que l'on peut avoir la consommation par demi heure, il serait peut être possible de définir des tranches horaires dans le plugin pour qu'il ajoute la consommation dans la bonne partie. Par exemple si je définis mes tranches HC sur  00h30/07h30 et 12h30/14h30, alors la consommation se mettrait au bon endroit en fonction de l'horaire.

Julien

**Comment by guillaumezin** [comment]
Oui, je me suis dit la même chose, si l'info ne vient pas d'Enedis, je peux demander dans la page de configuration à l'utilisateur de définir ses tranches HP/HC. Je vais voir comment faire sans trop compliquer, il y a plusieurs tranches possibles en France. Mais il faut que je vois comment stocker ça intelligemment dans la base de données de Domoticz.

**Comment by guillaumezin** [comment]
Réflexion faite, c'est plus compliqué que ce que j'imaginais : comme Enedis fournit sur les vues de leur site l'historique par heure pour le mois, et seulement par jour pour les mois précédents, c'est impossible de reconstruire la partie HP/HC pour les mois précédents. Il faudrait donc que le plugin ne se base que sur la vue heure, et reconstruise les autres vues par cumulation de données. Le plugin n'est pas du tout architecturé comme ça, il ne fait que prendre les données Enedis pour les inclure dans la base de données Domoticz.

Pour faire plus simple, c'est un plugin différent qu'il faut faire pour votre demande. Je ne pense pas avoir le temps de maintenir deux plugins.

Et accessoirement, ça veut probablement dire aussi ajouter un type de dispositif dans Domoticz (pour inscrire des données de la veille dans la base de données), c'est très compliqué (le coeur de Domoticz est très très mal codé, et le mainteneur principal en étant probablement conscient, il accepte difficilement les nouveaux dispositifs).

**Comment by darkpotpot** [comment]
Bonjour,

pas de souci. A la base je pensais vraiment que Enedis fournissait l'information, encore un truc mal pensé... 

Merci.
