### ISSUE TITLE
MAJ readme => Penser à activer script dans Domoticz

### ISSUE THREAD

**Issue by MacAre** [guillaumezin/DomoticzLinky#161]
Bonjour,
Ce n'est pas une question mais une suggestion pour ajouter dans les prérequis qu'il faut **Activer les "Événements (Lua/Blockly/Scripts)" dans "Paramètres / Autre" de Domoticz**.

J'ai trouvé l'info ici: https://github.com/guillaumezin/DomoticzLinky/issues/38#issuecomment-623097403 car je n'arrivais pas à faire apparaître le matériel Linky malgré installation/désinstallation de Python etc...
Maintenant ça marche enfin.

**Comment by guillaumezin** [comment]
Merci, je le garde en tête pour la prochaine mise à jour.

**Comment by guillaumezin** [comment]
Ajouté en version 2.4.4
