### ISSUE TITLE
Error: (FindModule) Domoticz/DomoticzEx modules not found in interpreter.

### ISSUE THREAD

**Issue by laoil72** [guillaumezin/DomoticzLinky#163]
Salut,
Pour commencer je tiens à saluer le travail de Guillaume pour ce super plugin !!!

Voilà le message que j'ai depuis quelques jours lorsque que je fais un modifier dans matériel pour avoir le code pour le consentement

![Screenshot_2022-02-15-08-24-30-613_com android chrome](https://user-images.githubusercontent.com/68594459/154012638-50348679-0f2d-4b66-afa8-3b28985c49a9.jpg)

Version : 

![Screenshot_2022-02-15-08-23-46-405_com android chrome](https://user-images.githubusercontent.com/68594459/154012541-c7034cdc-e42d-40c3-a9e2-20925d602e91.jpg)

Dans l'attente d'une solution.

**Comment by guillaumezin** [comment]
Bonjour,
Avez-vous mis à jour Domoticz ? Je vois qu'une nouvelle version stable est sortie, il faut que je la teste. Je suis surpris par votre message d'erreur, le plugin Linky n'utilise pas DomoticzEx...

**Comment by laoil72** [comment]
Bonjour,
Effectivement je suis passé sur la derniere version dite "stable"
J'ai bien fait un "sudo chmod -R +777" sur le dossier plugin pour avoir un acces total celui-ci ayant sauté avec la nouvelle version...

**Comment by guillaumezin** [comment]
Pouvez-vous me donner un log plus complet, pas juste l'onglet erreur mais l'onglet "Tout" du log ?

**Comment by laoil72** [comment]
Problème résolu ! Mais sans savoir pourquoi...
J'ai refait une fresh install du plugin c'était pareil.
Je suis allé fouiner dans les options debug afin de vous fournir le log le plus complet et je suis tombé sur "reset consentement" j'ai refait un "modifier" pour relancer le plugin pour tester et c'est bon...

![Screenshot_2022-02-15-19-48-30-551_com android chrome](https://user-images.githubusercontent.com/68594459/154129309-4755faae-9f58-43ae-a147-cf3b26d3e56e.jpg)
![Screenshot_2022-02-15-19-48-45-914_com android chrome](https://user-images.githubusercontent.com/68594459/154129326-36bfdc8e-3ba4-4da2-88d1-638447326ab8.jpg)

**Comment by laoil72** [comment]
Aussi je suis sur debian 10.11 sur un mini pc Beelink bt3 pro. Et j'ai toujours ce message d'erreur...
