### ISSUE TITLE
Comment récuperer mon historique?

### ISSUE THREAD

**Issue by DRbuntu91** [guillaumezin/DomoticzLinky#165]
Bonjour
Pour me connecter à l'interface d'ENEDIS j'ai été obligé de mettre un nouveau mot de passe (je l'avais oublié)
Du coup j'ai été obligé de refaire mon consentement.
Et tout ça entre le 26 et 29 mars dernier ou ENEDIS semblait avoir des soucis (service indisponible)
J'ai pu refaire mon consentement mais je n'avais pas de données, du coup dans le doute j'ai supprimé mon  dispositif dans l'onglet matériel et j'en ai crée un nouveau. Ce n'est que plus tard que je me suis rendu compte que le souci était coté ENEDIS.
Entre-temps le service ENEDIS est revenu et j'ai a nouveau des données. 
Donc tout va bien mais.... j'ai perdu mon historique (environ 3 mois)
Je suppose que c'est par ce que j'ai supprimé le dispositif que j'avais.....

D’où ma question: y-a-t-il un moyen de récupérer l'historique que j'avais? 

Il me manque aussi les données du 29 mars qui ne sont pas encore disponible chez ENEDIS. Si ces données arrivent par miracle chez ENEDIS dans les jours à venir, es ce que le plugin va les récupérer automatiquement?

* Domoticz version 2022.1
* Python version 3.7.3
* Raspberry Pi 3B+ avec PiOS version 5.10
* Plugin version 2.4.3

Merci d'avance

**Comment by guillaumezin** [comment]
Bonjour,
Cf. https://github.com/guillaumezin/DomoticzLinky#nombre-de-jours-%C3%A0-r%C3%A9cup%C3%A9rer augmentez le "nombre de jours à récupérer pour les autres vues" dans les paramètres du plugin, le plugin essaiera (de temps en temps seulement pour ne pas surcharger Enedis) de récupérer un historique plus profond. Quand vous aurez votre historique, je recommande très fortement de remettre ce paramètre à 7.

**Comment by DRbuntu91** [comment]
Super ça a marché! J'ai même récupéré mon historique sur 6 mois.
Merci beaucoup
