### ISSUE TITLE
Error: (FindModule) Domoticz/DomoticzEx modules not found in interpreter

### ISSUE THREAD

**Issue by Phil353556** [guillaumezin/DomoticzLinky#167]
Bonjour,
Après une première installation (cf https://github.com/guillaumezin/DomoticzLinky/issues/166 que j'ai ensuite fermé)

J'ai modifié comme indiqué dans la documentation pour récupérer au max 730 jours et suis repassé à 7 jours.

D'après l'affichage dans domoticz, les données ont bien été récupérées et s'affichent jusqu'en avril 2020.

Que pensez du message sur la copie d'écran ci-jointe ?

![ksnip_20220331-182054](https://user-images.githubusercontent.com/64729485/161103149-d899c347-33c8-4855-a2ae-751157dc9079.png)
![ksnip_20220331-181208](https://user-images.githubusercontent.com/64729485/161103158-9e86979d-cd3c-4e51-9ffa-f3e3a66304e9.png)

domoticz : 2022.1 
OS: Raspbian GNU/Linux 10 (buster) armv7l 
Host: Raspberry Pi 4 Model B Rev 1.2
Python : 
dpkg -l|grep -i python|grep "\-dev"
ii  libpython-all-dev:armhf               2.7.16-1                                armhf        package depending on all supported Python2 development packages
ii  libpython-dev:armhf                   2.7.16-1                                armhf        header files and a static library for Python2
ii  libpython2-dev:armhf                  2.7.16-1                                armhf        header files and a static library for Python2
ii  libpython2.7-dev:armhf                2.7.16-2+deb10u1                        armhf        Header files and a static library for Python (v2.7)
ii  libpython3-dev:armhf                  3.7.3-1                                 armhf        header files and a static library for Python (default)
ii  libpython3.7-dev:armhf                3.7.3-2+deb10u3                         armhf        Header files and a static library for Python (v3.7)
ii  librtimulib-dev                       7.2.1-5                                 armhf        Versatile C++ and Python 9-dof, 10-dof and 11-dof IMU library (dev files)
ii  python-all-dev                        2.7.16-1                                armhf        package depending on all supported Python2 development packages
ii  python-dev                            2.7.16-1                                armhf        header files and a static library for Python2
ii  python-smbus:armhf                    4.1-1                                   armhf        Python bindings for Linux SMBus access through i2c-dev
ii  python2-dev                           2.7.16-1                                armhf        header files and a static library for Python2
ii  python2.7-dev                         2.7.16-2+deb10u1                        armhf        Header files and a static library for Python (v2.7)
ii  python3-dev                           3.7.3-1                                 armhf        header files and a static library for Python (default)
ii  python3-smbus:armhf                   4.1-1                                   armhf        Python 3 bindings for Linux SMBus access through i2c-dev
ii  python3.7-dev                         3.7.3-2+deb10u3                         armhf        Header files and a static library for Python (v3.7)

**Comment by Phil353556** [comment]
![ksnip_20220331-182503](https://user-images.githubusercontent.com/64729485/161104226-fddbb04e-831b-4002-aa85-613ad37e598d.png)

**Comment by guillaumezin** [comment]
Bonsoir, j'ai déjà vu cette erreur, mais ça a été transitoire et ça a disparu, je n'ai pas trop compris. Utilisez-vous d'autres plugins Python ?

**Comment by guillaumezin** [comment]
Ca semble être un message sans conséquence, qui devrait être réglé dans la prochaine version de Domoticz, cf. https://github.com/domoticz/domoticz/issues/5153

**Comment by Phil353556** [comment]
- Merci, attendons la prochaine version de domoticz
- coté plugins : j'ai trouvé cette liste https://www.domoticz.com/wiki/Plugins 
  je ne crois pas utiliser d'autres plugins en python que celui de DomoticzLinky
  pour info :  Depuis 2 ans, J'ai configuré un lien avec une station Netatmo et installé une clé USB Key z-Wave

**Comment by guillaumezin** [comment]
Normalement, problème réglé sur la dernière version stable de Domoticz
