### ISSUE TITLE
Pas une erreur, mais un typo

### ISSUE THREAD

**Issue by Phil353556** [guillaumezin/DomoticzLinky#168]
Bonjour,
via le menu "Rapport" de domoticz, on peut afficher année par année 
en haut à gauche s'affiche alors : 

Utilisation totale: T1: xxx kWh, T2: 0.000 kWh, Total: xxx kWh
Compteur: T1: 0.000 kWh, T2: 0.000 kWh
Total nett usage: xxx  kWh                            <------------------ typo   nett  >  net 
Coût annuel: xxx

Version du plugin : 2.4.3

Je découvre le plugin, c'est juste TOP. Merci !

**Comment by guillaumezin** [comment]
Bonjour,
Le problème n'est pas au niveau mais de Domoticz même...

**Comment by Phil353556** [comment]
Bonjour,
Ah désolé, je vais regarder si c'est indiqué sur le forum domoticz, si ce n'est pas le cas je signalerai
Je ferme le case
