### ISSUE TITLE
Dispositifs Compteur pas créé

### ISSUE THREAD

**Issue by rezzalex** [guillaumezin/DomoticzLinky#171]
Domoticz Container version Version: 2022.1 (build 14318)

N'ayant plus de données depuis plusieurs semaines, j'ai désinstallé le plug in et reinstallé.
J'ai la connection à Enedis qui semble fonctionner )a vàrifier dans les logs mais j'ai eu le lienv ers ENEDIS qui a fonctionner avec la confirmation par mail qui a suivie), mais le dispositif Domoticz n'est pas créer et je ne peux donc rien visualiser...

[DomoticzLinky_2022_04_26_10_26_06_yeipycmm.log](https://github.com/guillaumezin/DomoticzLinky/files/8561283/DomoticzLinky_2022_04_26_10_26_06_yeipycmm.log)

**Comment by rezzalex** [comment]
Il a fini par se créer mais ne récupère pas l' historique...

**Comment by guillaumezin** [comment]
Bonsoir, je vois un message "Technical error" venant d'Enedis. Arrivez-vous à visualiser vos données sur leur site ?

**Comment by rezzalex** [comment]
Bonsoir

Oui, j accède aux données sur le site d Enedis  

le compteur s' est finalement créé...
Maison possible de récupérer un historique.

Merci

**Comment by Caro87810** [comment]
Bonjour,
Le consentement Enedis a été effectué (mail de confirmation) mais le dispositif n'est pas créé dans les Dispositifs  (les champs "Adresse mail et Mot de passe" n'apparaissent pas dans la création du matériel
Merci

**Comment by guillaumezin** [comment]
@rezzalex : je suis bien embêté, l'erreur "Technical error. Please try later" que vous voyez dans vos log est remontée par Enedis et je ne peux rien y faire, peut-être devriez-vous ouvrir un ticket auprès d'eux sur https://datahub-enedis.fr/

@Caro87810 : j'ai l'impression que votre problème n'est pas le même, avez-vous suivi les étapes décrites dans https://github.com/guillaumezin/DomoticzLinky#obtention-du-consentement ?

**Comment by Caro87810** [comment]
Bonjour, Oui j'ai suivi les étapes . J'ai reçu le mail de Enedis de confirmation de collecte. Par contre je ne peux toujours pas renseigner identifiant et mot de passe lors de la déclaration du Linky dans Domoticz car les deux champs ne sont pas présents.

**Comment by Caro87810** [comment]
En complément de mon message

![image](https://user-images.githubusercontent.com/105160942/167585817-cbe51352-50b5-473c-bd67-63ef0d40e09d.png)

**Comment by Caro87810** [comment]
Bonjour,
Après de nombreux essais infructueux, lernier est le bon.
