### ISSUE TITLE
Problème de récupération de données de production d'un compteur linky

### ISSUE THREAD

**Issue by matthieu-antoniol** [guillaumezin/DomoticzLinky#172]
```
Domoticz 2022.1
Linux Mint
```

Bonjour, 

J'ai bien réussi à faire marcher le plugin sur deux PC, merci pour l'excellent travail.

Mon père possède un deuxième compteur Linky pour gérer de la production d'énergie (panneaux solaires).
Bien que je puisse récupérer les données du compteur de la même façon que pour de la consommation (via le site enedis et activation de récupération de données à distance).

Le device pour la production ne se crée pas dans domoticz.

Deux questions, est-il prévu dans le plugin de faire fonctionner en parallèle deux compteurs?

Est-ce un bug que la production ne s'affiche pas ou cela n'a pas été codé?

Je peux potentiellement aidé à améliorer le plugin de ce coté là.

Cordialement
Soulwax

**Comment by guillaumezin** [comment]
Bonsoir,
En théorie, ça fonctionne déjà, si vous avez plusieurs compteurs différents, que certains font production, consommation, ou les deux, les devices sont créés automatiquement. Dans la pratique, ça ne fonctionne pas bien, et le problème n'est pas trop du côté du plugin, en tout cas ce n'est pas ce que j'ai constaté jusqu'ici. Il y a par exemple un utilisateur qui partage sa consommation avec une appli (https://www.bdpv.fr), impossible de la partager en même temps avec le plugin, c'est l'infrastructure d'Enedis qui limite, cf. #116 et #149

**Comment by jipite** [comment]
Bonjour
Merci pour cet excellent travail sur ce plugin.
Mais je pense avoir détecté un bug lors de la récupération de la consommation d'un compteur de production, cela provoque une erreur 403 qui désactive le plugin. Il faudrait mieux traiter cette erreur dans le plugin.
A bientôt
Jean-Patrick

**Comment by guillaumezin** [comment]
@jipite Vous avez sans doute raison mais comme je n'ai pas de compteur de production, tout ce que je peux faire c'est déboguer par rapport aux "simulateurs" avec de "faux clients" que propose Enedis. Et ça fonctionne avec ces simulateurs. Mais si les simulateurs ne sont pas conforme à la réalité de ce qui est déployé, c'est forcément compliqué. Pouvez-vous suivre la suggestion ici https://github.com/guillaumezin/DomoticzLinky#les-probl%C3%A8mes-persistent et m'envoyer votre log ?

**Comment by jipite** [comment]
Bonjour

J'utilise à nouveau le plugin mais j'ai une erreur 403 en lecture des données du compteur de production. J'ai donc remodifié le plugin comme je l'avais fait il y a quelques mois et ça remarche, plus d'erreur 403.
Je mets le plugin en pièce jointe, si cela peut vous aider.

A bientôt
[plugin.txt](https://github.com/guillaumezin/DomoticzLinky/files/12545127/plugin.txt)

**Comment by guillaumezin** [comment]
Bonsoir, vous avez toujours le problème d'erreur 403 sur la dernière version du plugin ?

**Comment by guillaumezin** [comment]
Sans nouvelle, je clos.
