### ISSUE TITLE
Champs mail et mot de passe invisibles

### ISSUE THREAD

**Issue by sebzicos** [guillaumezin/DomoticzLinky#173]
Bonjour,
Je ne comprends pas, mon problème est assez simple car après installation du plugin, je peux bien créer un nouveau matréiel dans Domoticz mais il n'y a pas les champs pour le compte Enedis.
Voir capture jointe.
Merci
![Capture](https://user-images.githubusercontent.com/106453217/170844426-7c6e9874-cfc7-4d66-98fa-2e84b247ad0e.PNG)

Sur Raspberry 3B
Domoticz : 
Version: 2022.1 (build 14318)
Build Hash: a380461ea
Compile Date: 2022-04-22 07:36:31
dzVents Version: 3.1.8
Python Version: 3.7.3 (default, Jan 22 2021, 20:04:44) [GCC 8.3.0]

**Comment by VeryBitter** [comment]
Bonjour

je pense que vous n'avez pas lu la notice du plug-in. Il n'y a pas besoin de mot de passe ni de login. Il faut passer par l'adresse donnée dans le log, onglet configuration de domoticz.

**Comment by sebzicos** [comment]
Bonjour,
Merci de votre aide.

Vous avez un peu raison... En fait j'ai suivi un tuto ailleurs sur le Web qui je suppose était plus ancien et qui employait une version avec les champs email et mot de passe. J'ai cru que c'était une étape préalable cette histoire de lien.

J'ai suivi l'adresse donnée dans les logs et j'ai validé sur le site d'Enedis la page avec la case à cocher en bas pour confirmer la transmission de données à un tiers. J'ai été surpris que rien ne se passe après clic sur ce bouton "valider" mais j'ai bien reçu le mail de confirmation (en fait pleins de fois), donc je suppose que c'est bon.

Pour le reste dans domoticz, je ne vois pas de dispositif pour l'instant mais je vais potasser un peu !

Bonne soirée
Seb

**Comment by guillaumezin** [comment]
Certains tutos sont effectivement dépassés, depuis la version 2 du plugin, le partage de consentement se fait différemment, j'ai essayé de le signaler quand je le pouvais dans les commentaires de ces tutos...

**Comment by VeryBitter** [comment]
Bonjour
@sebzicos, effectivement j'ai observé ces mêmes comportements avec le bouton valider. J'ai bien reçu des tas de mails de confirmation, et moi aussi je ne vois pas de dispositif et le log m'indique qu'il n'arrive pas à récupérer les données d'Enedis (j'ai essayé avec autorisation pendant 5 min de nouveaux dispos, mais ça ne marche pas non plus). Peut-être un bug ?
