### ISSUE TITLE
Production à jour mais pas consommation

### ISSUE THREAD

**Issue by Martial83** [guillaumezin/DomoticzLinky#176]
Bonjour,

Depuis pas mal de temps (mi-mars) le plugin met bien à jour dans Dz mes données de production mais ne met plus du tout à jour les données de consommation.
Une idée de l'origine du problème?
Martial ANDRE

Dz: version 2022.1
Plugin: version 2.3.7

**Comment by guillaumezin** [comment]
Bonsoir, je fais un peu de ménage, le plugin a beaucoup évolué depuis, je clos ce ticket sans activité depuis longtemps, vous le rouvrirez si le problème existe toujours.
