### ISSUE TITLE
Compte Engie

### ISSUE THREAD

**Issue by flipper07** [guillaumezin/DomoticzLinky#177]
Bonjour, 
J'ai installer le plugin linky
je voudrais savoir si je peut utiliser le plugins si j'ai le fourniseur Engie.
car ça ne fonctionne pas
Merci

Version: 2022.1
Build Hash: c9526851b
Compile Date: 2022-01-31 09:34:32
dzVents Version: 3.1.8
Python Version: 3.7.3 (default, Jan 22 2021, 20:04:44) [GCC 8.3.0]

**Comment by guillaumezin** [comment]
Bonjour,

Quelque soit votre fournisseur d'énergie, vous pouvez créer un compte chez Enedis et avoir accès ainsi à votre consommation, sur le site web d'Enedis et avec le plugin. En revanche, si vous partagez déjà votre consommation avec une autre application (une application smartphone par exemple), il est possible que ce plugin ne fonctionne pas. Ce n'est pas normal, mais d'autres utilisateurs m'ont rapporté ce problème, plutôt dépendant de l'infrastructure d'Enedis que du plugin même.

Bonne journée.

**Comment by flipper07** [comment]
Bonsoir merci pour votre reponse
J'ai bien un compte chez enedis (que j'avais crée avant de passer chez Engie)
Mais il me demande d'ajouter un compteur en rentrant le numero de PRM, ce que j'ai fait, c'est la ou ca bloque il me dit : 

L’adresse indiquée est erronée ? Vérifiez dans un premier temps l’exactitude de votre numéro de point de livraison électrique (PDL/PRM), ou contactez votre fournisseur si vous êtes consommateur. Vous êtes producteur ? Vous pouvez contacter votre Agence Producteur au 0 969 321 800 (appel non surtaxé).

Pourtant j'ai bien mis le numero de PRM du linky et l'adresse est bien la bonne
Donc je ne peut pas aller plus loin..
Puisque je ne suis plus chez enedis je ne peut pas les appeler non?
Sinon j'ai penser aussi 2 autres solutions :

La 1ere, il existe un boitier qui ce branche sur le linky : module D2L
ca marche en wifi, le probleme c'est mon compteur est a 40 mètres de la maison donc ça risque d'etre juste... (je ne sais pas si je peut l'utiliser avec domoticz).
il y a aussi ce boitier :  Zlinky_TIC....

Le 2eme c'est un boitier qui ce branche sur le tableau electrique sur une phase (comme un amperemetre) du genre smappee ( que j'avais mais qui ne fonctionne plus) c'est pour ça que j'essaye de trouver une solution avec mon systeme Domoticz qui pourrait fonctionne comme avec mon boitier smappee.
Encore merci pour votre aide
bonne soirée

**Comment by flipper07** [comment]
Merci beaucoup pour les renseignements 
Je fait essayer de les appele demain pour voir avec eux
Bonne soirée.
et Merci encore
