### ISSUE TITLE
Dernières 24h par tranches de 30 minutes

### ISSUE THREAD

**Issue by Shasdo** [guillaumezin/DomoticzLinky#18]
Salut,

J'ai posté dans le forum Domoticz mais il sera plus visible ici.

Etant donné que Enedis propose un relevé toutes les 30mins, est-il possible que le graph "Dernières 24h" soit par tranches de 30 minutes plutôt que par tranches d'1h afin de profiter d'une granulométrie plus fine?

Merci pout ton plugin!

**Comment by guillaumezin** [comment]
Bon, comme répondu dans le forum, qui a été sauvagement effacé depuis, ça remet en cause tout le modèle de base de données de Domoticz, il faut donc aller patcher le code C, ça a été déjà très compliqué pour rendre ce plugin possible, je ne me relance pas là dedans, désolé.

**Comment by Shasdo** [comment]
Évidemment, si c'est du côté de Domoticz et non du plugin je comprends parfaitement.
Merci encore et bonne continuation.
