### ISSUE TITLE
Impossibilité de saisir les identifiants

### ISSUE THREAD

**Issue by Curchulainn** [guillaumezin/DomoticzLinky#181]
Bonjour,

Je souhaite faire fonctionner le plugin.

L'installation fonctionne correctement, en revanche lors de l'ajout de Matériel, les box "< input / >" de saisie des identifiants du compte Enedis n'apparaissent pas:
![domoticz_plugin_error](https://user-images.githubusercontent.com/109824871/180515928-e189eecc-1fa2-425f-a1c3-b7f0aa6ad7a7.png)

J'ai tester sous Chrome, Firefox, Edge : même problème
J'ai réinstaller 3 fois le pluging : même problème

Si j'ajoute sans identifiants Enedis, j'ai le log suivant :
```
2022-07-22 21:43:30.332 Linky Yutz conso: Worker thread started.
2022-07-22 21:43:30.589 Linky Yutz conso: Heures creuses désactivées
2022-07-22 21:43:30.589 Linky Yutz conso: Consommation à montrer sur le tableau de bord mis à value_day / peak_day
2022-07-22 21:43:30.590 Linky Yutz conso: Nombre de jours à récupérer pour la vue par heures mis à 7
2022-07-22 21:43:30.590 Linky Yutz conso: Nombre de jours à récupérer pour les autres vues mis à 7
2022-07-22 21:43:30.590 Linky Yutz conso: Nombre de jours à récupérer pour le calcul du pic mis à 1
2022-07-22 21:43:30.590 Linky Yutz conso: Debug mis à 1
2022-07-22 21:43:30.594 Linky Yutz conso: Pas de cache trouvé sur le disque
2022-07-22 21:43:30.594 Linky Yutz conso: Si vous ne voyez pas assez de données dans la vue par heures, augmentez le paramètre Log des capteurs qui se trouve dans Réglages / Paramètres / Historique des logs
2022-07-22 21:43:30.332 Status: Linky Yutz conso: Entering work loop.
2022-07-22 21:43:30.332 Status: Linky Yutz conso: Started.
2022-07-22 21:43:30.586 Status: Linky Yutz conso: Initialized version 2.4.3, author 'Barberousse'
2022-07-22 21:43:30.590 Status: Linky Yutz conso: Log dans le fichier /tmp/DomoticzLinky_2022_07_22_21_43_30_a57msstr.log pour le matériel Linky Yutz conso avec la version 2.4.3 du plugin
2022-07-22 21:43:40.067 Status: Linky Yutz conso: Récupération des données avec l'historique court
2022-07-22 21:43:40.301 Error: Linky Yutz conso: No transport, write directive to 'HTTPS connection' ignored.
```

J'ai chercher sur l'erreur : "2022-07-22 21:45:20.130 Error: Linky Yutz conso: No transport, write directive to 'HTTPS connection' ignored." mais sans succès.

Je pense que le problème découle que je ne puisse pas renseigner les identifiants du compte Enedis :(

Peut-être puis-je saisir les idenfiants dans un fichier de config directement ?

A priori les deux "<param" ne sont pas dans le fichier plugin.py : 
![domoticz_plugin_error_2](https://user-images.githubusercontent.com/109824871/180517979-1db9721f-a7d7-4811-af46-cb9d98b66daa.png)

Bonne vacances
Curchulainn

NB : Le compte Enedis fonctionne et je vois bien les deux compteurs (conso + prod) et les data associées.

* Please indicate your version of
  * Domoticz
Version: 2022.1
Build Hash: c9526851b
Compile Date: 2022-01-31 09:34:32
dzVents Version: 3.1.8
Python Version: 3.7.3 (default, Jan 22 2021, 20:04:44) [GCC 8.3.0]

  * Operating system
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

  * Computer type (PC/Raspberry Pi 3 B+/etc.)
[Raspberry Pi 4 Modèle B 4 Go ARM-Cortex-A72 4 x 1,50 GHz, 4 Go de RAM, WLAN-AC, Bluetooth 5, LAN, 4 x USB, 2 x Micro HDMI](https://www.amazon.fr/gp/product/B07TC2BK1X/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1)

**Comment by Curchulainn** [comment]
Test de modifier le "Reset consentement" dans debug : 
![image](https://user-images.githubusercontent.com/109824871/180520149-12ed646a-3eb4-49ee-a695-520de38c20aa.png)

**Comment by guillaumezin** [comment]
Bonjour,
Relisez bien le Readme, le mot de passe Enedis ne s'être pas dans les paramètres mais s'obtient à l'issue d'une phase de consentement. Cependant, comme vous l'avez fort justement noté, il y a une erreur de connexion qui doit correspondre à l'établissement de cette phase de consentement. Arrivez vous depuis votre RPi à accéder au domaine enedis.domoticz.russandol.pro qui sert d'infrastructure pour ce faire ? Essayez la commande wget https://enedis.domoticz.russandol.pro. Avez vous un firewall ou Domoticz est il dans un conteneur ? Vous m'excuserez, mon aide sera limitée, je suis loin de mes outils informatiques.

**Comment by guillaumezin** [comment]
Notez que le plugin doit également avoir accès à https://gw.prd.api.enedis.fr pour que tout se déroule bien

**Comment by Curchulainn** [comment]
Bonjour,

Merci pour le feedback. Check tout est bon dans les accès (le routeur aurait effectivement pu être un point problématique). 

Relance ce matin et tout fonctionne:
![image](https://user-images.githubusercontent.com/109824871/180648764-849d23e3-042b-461d-8911-2098929d3d70.png)

En revanche, il faut recommencer un paquet de fois le consentement (pb du côté Enedis je pense):
![image](https://user-images.githubusercontent.com/109824871/180648788-f1b9010f-0484-48f3-9f9e-d329b1d38aff.png)

Mais au bout de plusieurs tentatives tout fonctionne.

Conclusions (si jamais quelqu'un a le même problème) : 
1) bien vérifier sa connectivité chez soi aux sites mentionnés :)
2) Je pense que le problème de connectivité est dû au fait que je testais en soirée plutôt qu'en journée. Bien faire le consentement / lien en journée.

On passe au deuxième compteur pour la production.

Merci pour l'aide et bonne vacances !

**Comment by guillaumezin** [comment]
Merci, je ne pensais pas que les serveurs de consentement étaient également coupés la nuit, je ferai évoluer le plugin et le Readme pour le signaler. Effectivement, Enedis alloue un quota un peu limite au plugin qui a pas mal d'utilisateurs, j'ai été obligé d'être astucieux pour stabiliser la récupération de données, mais je n'ai pas fait "d'effort" pour le consentement, ça oblige à des contorsions complexes, il faut donc retenter...

**Comment by Curchulainn** [comment]
Bonjour,

Merci pour vos messages :)

Je vais clôturer le ticket car le problème est en effet résolu. Je me permets un dernier retour d'information pour d'autres personnes ayant un souci similaire:

1) si jamais vous avez 2 compteurs, il semblerait que cocher les deux cases en même temps pour l'association soit aussi une source d'erreur de la part d'Enedis (je n'ai pas réussi en tout cas):
![image](https://user-images.githubusercontent.com/109824871/180747813-22ee96d1-81a8-4478-8037-59da1e9c8bd9.png)

2) Toujours pas possible de mon côté d'associer le compteur production séparé (2 Matériels différents dans Domoticz), mais l'erreur ci-dessous est exactement la même que lors du processus d'association du compteur consommation, j'ai l'impression qu'il faille recommencer. (bon pour la production, ca a l'air d'être plus compliqué pour Enedis car j'en suis déjà à 6/7 essais :( )
![image](https://user-images.githubusercontent.com/109824871/180747888-0c64d1df-cd00-4059-ac6d-cf6e030aa57f.png)

Curchulainn
