### ISSUE TITLE
Self hosted proxy

### ISSUE THREAD

**Issue by david-spaeth** [guillaumezin/DomoticzLinky#183]
Hello,
can you share source of proxy  for self hosting?

Thank,

**Comment by guillaumezin** [comment]
It's already part of my github repositories: https://github.com/guillaumezin/Device-Flow-Proxy-Server

**Comment by david-spaeth** [comment]
I missed it thanks. Maybe add a link in the readme file?

**Comment by guillaumezin** [comment]
It's already in the readme ;-) Okay, not obvious, in the authors section, you'll find a link to sources of my version of the proxy, used in debug mode, and to the production proxy, very similar.
