### ISSUE TITLE
Question sur l'affichage "Dernière 24 Heures"

### ISSUE THREAD

**Issue by SAS-Malko** [guillaumezin/DomoticzLinky#186]
Bonjour,
Tout d'abord, Merci pour ce plugin très utile! 
Je rencontre un problème d'affichage avec les "Dernière 24 Heures"
J'ai généralement l'affichage des dernières 24 heures, et il "glisse" au fil de la journée, si bien que je ne vois qu'une partie de la journée de la veille. 
![Affichage 24 heures jour glissant](https://user-images.githubusercontent.com/79724916/196124146-b8438ec7-b7b1-4e3a-8959-c35ac06080eb.png)
Je pensais que c'était "normal" et je voulais demander si c'était améliorable, mais en parcourant les issues pour savoir si c'était un point déjà évoqué, j'ai vu que cet affichage pouvait également montrer une semaine complète, ce qui est tout à fait ce que je souhaite.
J'ai modifié la configuration de mon plugin en remplaçant "Pic consommation journée dernière" par "Pic consommation semaine dernière".  NB: Petite précision, à chaque fois que je clique sur "modifier", pour mettre à jour la config. du plugin, Domoticz se plante. Néanmoins je vois en le relançant que la modif. a bien été prise en compte. Bizarre mais bon...
![config plugin](https://user-images.githubusercontent.com/79724916/196122458-bd5ab105-ec5f-4262-aae9-f9d0687b5c9f.png)
Après avoir redémarré Domoticz, miracle, j'ai bien l'affichage escompté
![Affichage 24 heures semaine](https://user-images.githubusercontent.com/79724916/196124137-12dc76fd-7eb9-41a3-b7a9-f454aca32f61.png)
Malheureusement après quelques opérations sans rapport (consultation des logs, et autres...) je reviens sur l'affichage du Linky et je retrouve l'affichage initial, montrant seulement la journée de la veille.
J'ai aussi modifié "Consommation / Production journée dernière" par "Consommation / Production semaine dernière" sans plus de succès.
Du coup je sais que parfois j'ai l'affichage souhaité et parfois non mais je ne sais pas pour quelles raisons, ni comment faire pour avoir celui que je souhaite, quand je le souhaite.

Côté versions :
2022-10-17 08:59:38.804 Status: Domoticz V2020.1 (c)2012-1970 GizMoCuz
2022-10-17 08:59:38.816 Status: Build Hash: 0, Date: 1970-01-01 01:00:00
2022-10-17 08:59:38.817 Status: Startup Path: /usr/local/domoticz/
2022-10-17 08:59:40.468 Status: PluginSystem: Started, Python version '3.8.6'.
sur un NAS Synology

Merci d'avance pour toute aide :)
Cordialement
L.B.

**Comment by guillaumezin** [comment]
Bonjour,

Relisez attentivement https://github.com/guillaumezin/DomoticzLinky#nombre-de-jours-%C3%A0-r%C3%A9cup%C3%A9rer

Guillaume

**Comment by SAS-Malko** [comment]
Bonjour,
Merci beaucoup pour ce détail d'importance :D
J'y perdais un peu mon latin.
En fait, quand je relançais Domoticz le plugin allait lire les données chez
Enedis et les 7 jours s'affichaient... jusqu'à ce que Domoticz fasse le
ménage en accord avec mon paramétrage des "logs des capteurs", qui était
effectivement à 1.

Encore merci et bonne continuation

Laurent

Le lun. 17 oct. 2022 à 10:19, Guillaume Zin ***@***.***> a
écrit :
