### ISSUE TITLE
Affichage de la consommation sur le compteur

### ISSUE THREAD

**Issue by xavierlp** [guillaumezin/DomoticzLinky#19]
Bonjour

Utilisation de la version 1.1.9
Lors des faibles consommations quotidiennes (<10 kwh) l'afficahge est erroné.
Exemple lorsque la consommation quotidienne est de 2.094

![image](https://user-images.githubusercontent.com/13960604/64065812-c64e2b00-cc12-11e9-92b7-2500d8061002.png)

Le compteur affiche +10 -> 12.094

![image](https://user-images.githubusercontent.com/13960604/64065820-e7168080-cc12-11e9-99a6-56f6bb4f6adc.png)

**Comment by guillaumezin** [comment]
Ah bah c'est sûr, c'est bizarre, je n'avais jamais remarqué. C'est toujours +10 ?

**Comment by guillaumezin** [comment]
D'ailleurs, curieusement, là tout de suite ça m'affiche bien 5.683 kWh, c'est pour ça que je n'avais pas remarqué le problème, c'est peut-être moins systématique que ça en a l'air

**Comment by xavierlp** [comment]
J’ai modifié l’offset de 0 à 100 puis de 100 à 0 et à présent c’est corrigé 

Donc j’en déduit que ce n’est pas du fait du script 

Encore bravo pour le boulot
