### ISSUE TITLE
Domoticz linky :  pourquoi le dernier tableau comparaison n'affiche rien ?

### ISSUE THREAD

**Issue by Phil353556** [guillaumezin/DomoticzLinky#192]
Bonjour, 

Domoticz : 2022.2
Raspberry Pi : Raspberry Pi 4 Model B Rev 1.2
OS : 10 (buster) 

Pourquoi le tableau de comparaison (le dernier tout en bas de la page)  affichent : 

Y a des données depuis avril 2020
Merci
Phil
![image](https://user-images.githubusercontent.com/64729485/211295861-bccdd64f-ee0e-402d-9ccd-7ce28eb5cafb.png)

**Comment by guillaumezin** [comment]
Bonjour,
Je n'avais pas remarqué cette vue qui est apparue il y a peu. J'ai l'impression qu'il faut des données sur plus d'un an pour que ça puisse fonctionner. Et comme le plugin ne remonte pas de valeur de compteur absolu (Enedis ne fournit pas cette donnée) mais uniquement des valeurs d'usage, je ne suis pas certain que ce soit compatible avec la vue telle qu'elle fonctionne, cf. https://www.domoticz.com/forum/viewtopic.php?t=38242

**Comment by Phil353556** [comment]
Bonjour,
Ah effectivement : valeur compteur absolu, ce qui est une différence avec un autre plugin (DomoticzGazpar) concernant le gaz cf la copie d'écran ci-jointe, y a bien les valeurs.
Y aurait-il pas une possibilité en prenant comme référence la date la plus ancienne puis les valeurs d'usage en cumulé ?
![image](https://user-images.githubusercontent.com/64729485/212552929-4ff39adc-8c69-4127-a38a-4f20650aa7b4.png)
Merci et excellente année 2023

**Comment by guillaumezin** [comment]
C'est difficile, dans les premiers temps du plugin, j'avais fait comme ça, j'inventais une valeur de départ, puis je cumulais. L'ennui c'est que dans la structure des plugins sous Domoticz, on ne sais pas relire ce qui est en base de données, donc si le plugin perdait le fil pour une raison ou pour une autre, ça faisait des choses vraiment bizarre.

Dans l'API Gazpar, a contrario, on reçoit bien la valeur absolue du compteur en plus de l'usage, donc ce problème n'existe pas.

**Comment by Phil353556** [comment]
ok
Est ce qu'il y aura une évolution dans la prochaine version de l'API d'Enedis avec la mise à disposition de la valeur absolue du compteur ?
Merci
