### ISSUE TITLE
Connexion bloquée - No transport, write directive to 'HTTPS connection' ignored.

### ISSUE THREAD

**Issue by adruet29** [guillaumezin/DomoticzLinky#193]
[DomoticzLinky_2023_01_11_21_22_26_1_gmfngc.log](https://github.com/guillaumezin/DomoticzLinky/files/10395882/DomoticzLinky_2023_01_11_21_22_26_1_gmfngc.log)
  * Domoticz 2022.2
  * Debian bullseye
  * Type d'ordinateur : PC Intel

Bonjour,

J'ai changé de fournisseur d'électricité le mois dernier, j'ai donc perdu la récupération de mes données  depuis le plugincar le changement de fournisseur m'a obligé à réactiver la collecte de données, le paramétrage horaire sur le site d'Enedis, et faire le consentement dans le plugin.
Mais même après ça ça n'est pas revenu. J'ai bien mes données de conso sur le site Enedis (en jour par jour mais aussi heure par heure), mais impossible de les récupérer avec le plugin.
J'ai systématiquement des erreurs de type:
Error: Linky: No transport, write directive to 'HTTPS connection' ignored.
Et quand j'active le debug, je vois:
2023-01-11 21:22:36.112 Debug : onDisconnect called
2023-01-11 21:22:46.078 Debug : onHeartbeat called
2023-01-11 21:22:46.078 Debug : Connexion bloquée
2023-01-11 21:22:46.078 Debug : Etape sending
2023-01-11 21:22:56.094 Debug : onHeartbeat called
2023-01-11 21:22:56.094 Debug : Connexion bloquée
2023-01-11 21:22:56.094 Debug : Etape sending
2023-01-11 21:23:06.060 Debug : onHeartbeat called
2023-01-11 21:23:06.061 Debug : Connexion bloquée

J'ai essayé de faire pas mal de manip, re-refaire le consentement, attendre plusieurs jours, faire un reset du cache, mais rien n'y fait. Si quelqu'un a une idée...

**Comment by guillaumezin** [comment]
Bonjour,
J'ai reçu un message d'Enedis, signalant un problème avec leur infrastructure. Si vous allez dans les paramètres du plugin et que vous cliquez juste sur "Modifier" (pour relancer le plugin), c'est toujours pareil ? De mon côté, ça (re)fonctionne.

**Comment by adruet29** [comment]
Bonjour, j'ai fait la manipulation mais c'est toujours le même message d'erreur :
Error: Linky: No transport, write directive to 'HTTPS connection' ignored.

**Comment by adruet29** [comment]
Je clos, ça ne marche toujours pas, j'aurai fait 2 ans avec ce plugin avec succès, mais là j'ai décidé comme ça ne fonctionnait plus de passer sur un lixee et une remontée direct du compteur.
