### ISSUE TITLE
Impossible de récupérer les données Enedis

### ISSUE THREAD

**Issue by jcsombret** [guillaumezin/DomoticzLinky#195]
Bonjour,

Depuis plusieurs jours la récupération des données ENEDIS échoue, même lorsque je modifie le matériel Linky pour forcer une mise à jour, cela échoue.
J'ai également MAJ le plugin, (avec une réponse déjà à jour).

J'ai adressé mon fichier log sur la boite mail indiquée dans les commentaires du dépannage, car je ne vois rien qui m'éclaire sur le problème.
Merci de me dire si quelque chose ressort de ce fichier qui pourrait expliquer le disfonctionnement.

Bien cordialement à vous

JCSombret

**Comment by nicolasbinand** [comment]
Bonjour,

Même problème ici, depuis le 06/01. Le webservice enedis "consumption_load_curve" renvoie une 404 sur les plages de date après le 06/01 (et est OK avec le même token sur une plage de date avant le 06/01) .

J'ai réinitialisé mon consentement pour voir si le problème venait de là, mais le problème persiste. 

Nicolas

**Comment by guillaumezin** [comment]
@jcsombret j'ai bien reçu votre log, je vois le message "Durant l'étape : retry - Trop d'échecs de communication, le plugin réessaiera plus tard" qui signifie que les serveurs d'Enedis ne répondent pas ou que le plugin a atteint son quota. En effet, le plugin a un quota partagé entre tous les utilisateurs du plugin et comme il y a eu 2 crashs récents dans l'infrastructure (juste avant et juste après les vacances de Noël), ça a pu entraîner un surcroît d'appels de données avec tous les utilisateurs du plugin qui font des appels dans tous les sens. J'espère que ça va se stabiliser.

D'ici le mois de mars, le plugin va évoluer pour faire appel à une nouvelle version de l'infrastructure Enedis, peut-être que ce sera plus stable à ce moment là...

**Comment by jcsombret** [comment]
Merci pour toutes ces précisions

**Comment by ErnieFR** [comment]
"D'ici le mois de mars, le plugin va évoluer pour faire appel à une nouvelle version de l'infrastructure Enedis, peut-être que ce sera plus stable à ce moment là..."
Guillaume, c'est peut-être après tout le bon moment pour changer le plugin vers le type qui mont que le jour d'hier entier au lieu de montre le 24h passée qui donc bloque un grand part de visibilité ?!

**Comment by guillaumezin** [comment]
> Guillaume, c'est peut-être après tout le bon moment pour changer le plugin vers le type qui mont que le jour d'hier entier au lieu de montre le 24h passée qui donc bloque un grand part de visibilité ?!

Bonjour, 2 choses:
- le nouveau système dont je parlais est encore plus en panne que l'actuel chez Enedis, donc la bascule obligatoire a été repoussée à fin avril
- quelque soit le système, il manquera toujours les données de la veille. Enedis collecte les données des Linky la nuit et les met à disposition le lendemain, le plugin ne peut pas faire de "direct"
