### ISSUE TITLE
Consentement 

### ISSUE THREAD

**Issue by jcsombret** [guillaumezin/DomoticzLinky#196]
Bonjour,

Je suis bloqué dans ma collecte de mes consos sur ENEDIS, j'aurai besoin de refaire manuellement un consentement pour remettre en fonctionnement la télécollecte des consommations.

Je ne trouve pas comment faire !

En modifiant le dispositif pour engendrer une collecte il n'aboutit pas (car le précédent consentement a été corrompu par je ne sais quoi) et il ne me propose pas le lien à lancer pour valider un nouveau consentement.

Il doit bien y avoir une façon manuelle d'obtenir ce lien, si quelqu'un peut me venir en aide. 

Par avance merci

**Comment by Phil353556** [comment]
Bonjour, je me permet de répondre :
- lire le document de Guillaume : https://github.com/guillaumezin/DomoticzLinky
au paragraphe  : Obtention du consentement
c'est bien expliqué .. y compris comment refaire la demande
Phil

**Comment by jcsombret** [comment]
Merci à Phil pour sa réponse !

Néanmoins, comme je le précisé dans mon message, même en modifiant le plugin dans (configuration/matériel) le lien avec le code pour lancer la demande de consentement n'apparait pas...... C'est bien là mon problème......

**Comment by Phil353556** [comment]
arg / désolé
Question naive :  extrait de la documentation .. est ce tout bon  coté Enedis ?
"Vous devez avoir un compteur Linky, créer un compte utilisateur sur [Enedis](http://www.enedis.fr/), accepter les conditions d'utilisation et vérifier que vous visualisez bien les courbes sur le site. En particulier, vérifiez la vue par heures (allez sur "Suivre les mesures" et passez "affiché(e)s en" sur "heures"), [Enedis](http://www.enedis.fr/) peut vous demander la permission la première fois pour collecter et enregistrer les données par heure, ce plugin ne fonctionnera pas pleinement si vous n'avez pas passé cette étape. Vous pouvez activer la collecte et l'enregistrement des données par heure sur votre compte Enedis sur "Gérer l'accès à mes données" dans l'encart "Collecte de la consommation horaire" et dans l'encart "Enregistrement de la consommation horaire". Les données peuvent ne pas être disponibles après l'installation ou l'activation de Linky, soyez patient et vérifiez que vous recevez les données sur le site Enedis avant de rejetter la faute sur le plugin."

**Comment by jcsombret** [comment]
Oui toutes ces étapes sont validées.
D'ailleurs mon installation domiticz avec le plugin Linky fonctionnait depuis des années.

Entre temps un consentement a été donné à EDF pour collecter les informations, je crains que mon problème vienne de là, car depuis cela ne fonctionne plus avec domiticz. Sans doute Enedis n'accepte pas de fournir mes consos à plusieurs opérateurs.

J'ai donc supprimé le partage des données pour EDF sur mon compte Enedis et à présent je souhaite que le plugin présente une nouvelle demande avec le lien et le code, et c'est là que je bloque car quoi que je fasse le plugin ne me le propose pas.

Merci pour votre intérêt

**Comment by guillaumezin** [comment]
Bonsoir,
Essayez de passer "Debug" sur "Reset consentement" dans les paramètres du plugin, puis faites "Modifier". Attendez quelques secondes et repassez "Debug" sur son ancienne valeur et refaites "Modifier".

Après il est possible qu'Enedis ait du mal à partager les données vers plusieurs applications, cf. #116 et #149

**Comment by jcsombret** [comment]
Merci, 

J'ai énormément cherché et je m'en veux un peu de ne pas avoir trouvé, ça parait tellement évidant !!

Merci infiniment.

**Comment by guillaumezin** [comment]
Incident chez Enedis clos, relancez le consentement en cliquant sur "Modifier" dans les paramètres du plugin.
