### ISSUE TITLE
problème enregistrement enedis

### ISSUE THREAD

**Issue by Mickaelf16** [guillaumezin/DomoticzLinky#197]
Bonjour , 
J'ai installer le plugin mais quant je vais sur le lien pour la connexion a Enedis j'ai une erreur ERREUR 404
La page que vous recherchez n’existe pas.
si quelqu'un a déjà eu se problème.
Merci

**Comment by MxB2603** [comment]
Bonjour, Idem (Erreur 404 ... ) ce matin malgré plusieurs tentatives avec nouveau consentement ..
Merci d'avance

**Comment by stefg73** [comment]
idem, erreur 404

**Comment by guillaumezin** [comment]
Idem, il va falloir être patient, c'est une panne côté Enedis, je n'ai aucune idée de quand ce sera résolu

**Comment by jbremond** [comment]
idem, 404 encore aujourd'hui. 
J’édite l'application Survoltage qui utilise les mêmes mécanismes pour lier un compteur, et nous avons le même problème. Enedis est au courant du problème. On croise les doigts pour que ce soit réglé dans la semaine.

**Comment by stefg73** [comment]
On va attaquer la 3ème semaine de panne seveur Enedis ? Je n'ose y croire...

**Comment by guillaumezin** [comment]
Ca ne fonctionne effectivement toujours pas, j'ai reçu un mail d'Enedis il y a seulement quelques jours :

![image](https://user-images.githubusercontent.com/541581/216783970-941bd316-1f1f-45ac-a343-f129abee7fa5.png)

**Comment by stefg73** [comment]
ah bah si, Enedis l'a fait. Heureusement que les serveurs de prod des centrales nucléaire ou des militaires ne sont pas gérés par eux

**Comment by romainlrch** [comment]
Fonctionne pas pour moi non plus le 11/02...

**Comment by stefg73** [comment]
toujour rien le 12/02

Guillaumzin ? pas de news d'Enedis ? au moins une date pour la remise en prod ?

**Comment by guillaumezin** [comment]
Bonsoir, je viens de vérifier, c'est toujours marqué en panne sur le site d'Enedis, sans annonce de date de retour à la normale. Ce qui est beau, c'est que le plugin fonctionne avec la version 4 de L'API  et qu'ils veulent qu'on passe à la version 5 fin avril au plus tard, mais qu'elle est encore plus en panne...

**Comment by stefg73** [comment]
Toujours erreur 404 le 15/02/2023...

**Comment by ErnieFR** [comment]
Désolé je n'ai pas lu tout les posts sur ce forum avant poster sur le dernier. Maintenant je découvre tout le monde avec LINKY a un problème chez Enedis. Moi, depuis le 3 fev 2023 aucun recup de données par Domoticz, état "partager les données" sur le site de Enedis VIDE!!! J'ai du arrêter le partage et enregistration à l'heure, puis autoriser tout à nouveau. Maintenant le 17 fev 2023 l'état chez Enedis is comme il faut mais le liens avec Russandol.fr ne marche pas : 404 
![afbeelding](https://user-images.githubusercontent.com/60966258/219594739-014ac88d-957a-4af7-b0c4-c9df86f47627.png)

**Comment by stefg73** [comment]
Bonsoir, je ne crois pas que ce soit le serveur russendol qui ne répond pas, c'est le serveur qui héberge le service d'autorisation API chez Enedis qui ne répond plus depuis bientôt 1 mois...

Personne n'a un bon produit TIC wifi à pluguer sur le Linky et compatible Domoticz ?
Comme ça les serveurs Enedis peuvent bien tomber et rester en panne pendant des années.

**Comment by Zaphod-dev** [comment]
Suis-je le seul à avoir une importation normale des conso via le plugin Linky ?
![image](https://user-images.githubusercontent.com/12284507/219787644-9e430048-6572-4b5f-8d11-bfc3cd1d0182.png)

**Comment by guillaumezin** [comment]
Tant que vous n'avez pas besoin de vous (ré)authentifier, le plugin continuera à fonctionner...

**Comment by Zaphod-dev** [comment]
> Tant que vous n'avez pas besoin de vous (ré)authentifier, le plugin continuera à fonctionner...

Ok merci, je croise les doigts donc...
> Personne n'a un bon produit TIC wifi à pluguer sur le Linky et compatible Domoticz ?

Ca serait la solution, c'est vraiment pénible pour plein de raisons cette tendance à tout faire transiter sur le "cloud". Y compris les interdépendances lourdes et peu robustes...

**Comment by stefg73** [comment]
Comme indiquait Guillaumezin avec le passage "obligatoire" à la V5 en Avril, je me demande s'il ne va pas falloir attendre Avril/Mai avant d'avoir une API-Authorize V5 qui permettra le fonctionnement du plugin...
Pourquoi ils investiraient du temps (et peut-être de la fourniture) pour réparer une API qui sera obsolète dans 2 mois...

Je me mets en quête d'un TIC pour dire définitivement au revoir à Enedis. Dommage pour le plugin qui fonctionnait parfaitement quand ces messieurs d'Enedis faisaient correctement leur job...

**Comment by guillaumezin** [comment]
A priori L'API authorize ne va pas bouger en avril, c'est seulement la partie data qui bouge...

**Comment by Eucliwood090** [comment]
> > Tant que vous n'avez pas besoin de vous (ré)authentifier, le plugin continuera à fonctionner...
> 
> Ok merci, je croise les doigts donc...
> 
> > Personne n'a un bon produit TIC wifi à pluguer sur le Linky et compatible Domoticz ?
> 
> Ca serait la solution, c'est vraiment pénible pour plein de raisons cette tendance à tout faire transiter sur le "cloud". Y compris les interdépendances lourdes et peu robustes...

Un esp3286 fait l'affaire .

**Comment by oredin** [comment]
Bonjour,

Message reçu ce jour de la part d'Enedis annonçant la remise en route du consentement.

Si quelqu'un peut confirmer, ça permettra à Guillaume de clore les multiples tickets à ce sujet.

**Comment by stefg73** [comment]
Bonjour,

c'est fonctionnel au moins depuis ce matin.

**Comment by ErnieFR** [comment]
Ouiiiii ça marche comme il faut, merci pour tout tes efforts Guillaume!!

 2023-02-22 11:11:47.784 Status: (Linky-Maqué) Initialized version 2.4.3, author 'Barberousse'
2023-02-22 11:11:47.792 Status: (Linky-Maqué) Entering work loop.
2023-02-22 11:11:49.730 Status: (Shelly MQTT) Initialized version 0.6.1
2023-02-22 11:11:49.742 Status: (Shelly MQTT) Entering work loop.
2023-02-22 11:11:59.258 Status: (Linky-Maqué) Récupération des données avec l'historique court
2023-02-22 11:13:19.670 Status: (Linky-Maqué) Traitement pour le point de livraison 23312300992282
2023-02-22 11:13:39.060 Status: (Linky-Maqué) Stop directive received.
2023-02-22 11:13:39.061 Status: (Linky-Maqué) Exiting work loop.
2023-02-22 11:13:39.262 Status: (Linky-Maqué) Stopping threads.
2023-02-22 11:13:39.262 Status: (Linky-Maqué) Stopped.
2023-02-22 11:13:39.262 Status: (Linky-Maqué) Started.
2023-02-22 11:13:40.041 Status: (Linky-Maqué) Initialized version 2.4.3, author 'Barberousse'
2023-02-22 11:13:40.043 Status: (Linky-Maqué) Entering work loop.
2023-02-22 11:13:50.075 Status: (Linky-Maqué) Récupération des données avec l'historique court
2023-02-22 11:13:50.081 Status: (Linky-Maqué) Traitement pour le point de livraison 23312

**Comment by rcrocus** [comment]
Ca refonctionne aussi chez moi et l'historique a bien été récupéré !
Merci à @guillaumezin !

**Comment by GMLinky** [comment]
Fonctionne à nouveau
Merci

**Comment by GMLinky** [comment]
Consentement hier OK
Depuis ce matin "Pas de données disponibles" alors qu elles sont bien sur Enedis
Desactivation "Enregistrement données horaires" 2h d attente Ok
Puis Reactivation 5h d attente Rien avec des messages de temps en temps "Service indisponible"
Ce site est une grosse bouse.
Quelqu un a t il le meme probleme ?

**Comment by guillaumezin** [comment]
Incident chez Enedis clos, relancez le consentement en cliquant sur "Modifier" dans les paramètres du plugin.

**Comment by GMLinky** [comment]
Le consentement est OK, Enregistrement conso horaire Ok (apres 5h et de multiples "site indisponible" mais impossible d activer "Collecte de la conso horaire" j ai cliqué 20 fois dessus il marque "Demande en cours" et au rafraichissement "Désactivé". Je n ai plus de données.
