### ISSUE TITLE
Linky Plus de recup Consentement impossible sur Enedis

### ISSUE THREAD

**Issue by GMLinky** [guillaumezin/DomoticzLinky#199]
Depuis ce matin plus de Récup "Données manquantes", sur Enedis données dispo.
Domoticz arreter Linky plante le domoticz
Reset consentement, russandol OK, Enedis "Page not  found"
Que se passe-t-il ?
Enedis, Russandol ?
Qui d entre vous a le meme probleme ?

**Comment by guillaumezin** [comment]
Bonjour, même problème que #197

**Comment by GMLinky** [comment]
Contacté Enedis hier avec copie d écran.
Serait il possible que la page ait changé et que russandol n ait pas changé le lien ?
Peut on contacter Russandol ?
En attente d Enedis et de tout ce qui peut m aider

**Comment by pioupiou92** [comment]
Même problème: Erreur 404 chez Enedis ! Le fichier d'erreur indique "error": "authorization_pending"

**Comment by ErnieFR** [comment]
Salut les aussi-victimes de multiple organisations qui ne communique pas de tout :-(   
Depuis le 3 fev 2023 mon Domoticz a s'arrêté. Sur Enedis mon compte mont que des vides sur "partager les données". Donc j'ai arrêté partager, puis redemarré partager, puis redemarré enregistrement à l'heure et hier finalement tout semble comme il faut sur Enedis. Revenu sur Domoticz, redemarré et utilisé le liens de Russandol tout suite apres, mais une fois arrivé sur le site Enedis "404" Grrrrrrr. J'ai vérifié le domain russandol.fr et laissé une message sur contact@russandol.eu
Dans l'attente, comme d'habitude, vraiment dommage. 
Par contre, j'ai souvent posé la question pourquoi le "capteur" Linky dans Domoticz ne mont-il pas simplement le jour avant complet avec 24h d'info, au lieu de les 24h passé qui coupe automatiquement les heures inrecupable car Enedis produit pas à l'heure. Mais non, rien est developé en plus...

**Comment by GMLinky** [comment]
J ai envoyé un message à russandol il y a plusieurs jours. Pas de réponse. Enedis n a pas réagi non plus à ma copie d écran après contact téléphonique. Plus de données depuis le 07 Février au matin. Dernieres données du 05.02. Pas fiable. On fait quoi ? Car à mon avis plus personne ne peut utiliser le plugin dès lors que le consentement est nécessaire.

**Comment by GMLinky** [comment]
Consentement hier OK
Depuis ce matin "Pas de données disponibles" alors qu elles sont bien sur Enedis
Desactivation "Enregistrement données horaires" 2h d attente Ok
Puis Reactivation 5h d attente Rien avec des messages de temps en temps "Service indisponible"
Ce site est une grosse bouse.
Quelqu un a t il le meme probleme ?

**Comment by guillaumezin** [comment]
Je ne suis pas devant mon PC en journée, j'ai juste fait une tentative hier soir et le site d'Enedis était encore en carafe pour moi aussi...

**Comment by guillaumezin** [comment]
Incident chez Enedis clos, relancez le consentement en cliquant sur "Modifier" dans les paramètres du plugin.

**Comment by GMLinky** [comment]
Le consentement est OK, Enregistrement conso horaire Ok (apres 5h et de multiples "site indisponible" mais impossible d activer "Collecte de la conso horaire" j ai cliqué 20 fois dessus il marque "Demande en cours" et au rafraichissement "Désactivé". Je n ai plus de données.
