### ISSUE TITLE
Pas d'info sur le graph journalier.

### ISSUE THREAD

**Issue by Mat2Vence** [guillaumezin/DomoticzLinky#2]
Tout marche pour le mieux à part le graph journalier pour lequel je ne récupère aucune data.
J'ai un message d'erreur dans le log:
`2018-08-27 23:28:56.520 Error: (Linky) Error in received JSON data during step getdatahours from 24/08/2018 to 27/08/2018`

**Comment by guillaumezin** [comment]
Bonjour,

Je viens de vérifier et pour ma part j'ai bien reçu les données de ces derniers jours. Est-ce que vous voyez les données (heure par heure) sur votre compte Enedis ? Ce peut-être un problème isolé dans le temps, s'il y a des travaux en cours.

Quelle version de Domoticz utilisez vous ? Je pense que ce n'est pas votre soucis, mais la version stable 4.9700 n'affiche pas correctement les données journalières, grâce à un bug introduite juste avant la release... (mais votre message indique que vous ne recevez même pas ces données).

**Comment by guillaumezin** [comment]
Vous pouvez également tenter d'activer le debug pour avoir plus d'infos...

**Comment by Mat2Vence** [comment]
En effet, je ne savais pas qu'il fallait activer une option supplémentaire du côté d'enedis pour avoir les informations heure par heure.

**Comment by guillaumezin** [comment]
Il y a une option à activer maintenant ? Je ne savais même pas, ou alors je l'avais activé sans faire le lien. C'est l'activation de la courbe de charge ? Fonction de votre réponse, je vais peut-être l'ajouter dans les logs

**Comment by Mat2Vence** [comment]
En fait, le relevé heure par heure est considéré comme de la donnée privée. Donc par défaut, ce n'est pas collecté. En cliquant la première fois depuis le site de Enedis sur les data heures par heures, on nous demande d'accepter que les données soient collectées et gardées pour une période de 12 mois.

**Comment by guillaumezin** [comment]
Ok, merci, j'ajouterai le warning à l'occasion dans une prochaine version
