### ISSUE TITLE
Recupération dates manquantes

### ISSUE THREAD

**Issue by fligozat** [guillaumezin/DomoticzLinky#202]
Bonjour je n'ai pas la visu sur les consommations entre le 15/12/2022 et 22/12/2022. J'ai vérifié sur domoticz.db il n'y pas de valeurs à ces dates.
Comment puis je retrouver ces valeurs sachant que j'ai déjà supprimé et reinstallé le plugin. Les valeurs sont bien présentent sur enedis.

Fabrice

----------------------------------------------------------------

* Before posting a message here, please always check that your data are visible on the Enedis website, in the days view and in the hours view. If it does not work with the Enedis website, it will not work with the plugin either. Don't forget to allow hours data collect, it's explained in the readme.

* Domoticz version must be at least 3.9517, but short log view (hours view) will fail on release version 4.9700 (you'll need a more recent release or beta version if you already installed the version 4.9700 to get short log view working). Domoticz version must be at least 4.11774 or 2020.1 to see energy production and day / night tariff differences.

* Consider giving the read and execute rights to the plugin if you are on Linux, it is explained in the readme.

* The "async read" error often occurs the first time the plugin is executed and is due to a Domoticz bug. This error should not persist.

* For any problem, please enable the Debug mode by putting it on "Simple" or "Avancé", and post all the messages concerning the plugin, including the lines indicating the version of the plugin and the configured parameters, or even better, send the log file produced by the plugin (its path is given in the "Status" tab of the Domoticz logs) to the email indicated on the profile https://github.com/guillaumezin.

* Please indicate your version of
  * Domoticz
  * Operating system
  * Computer type (PC/Raspberry Pi 3 B+/etc.)

**Comment by Phil353556** [comment]
Bonjour,
Avez vous essayé ceci ?
Menu "Configuration" puis "Matériel"  clic sur la ligne du compteur linky et modification des valeurs tout en bas de la page.
Mettre 90 jours par exemple,  et une fois les données récupérées, repasser la valeur à 7.
Phil
![image](https://user-images.githubusercontent.com/64729485/220623493-f9a4a127-4a22-42de-8eb0-b3d819759fd5.png)

**Comment by fligozat** [comment]
Bonjour 
oui j'ai déjà essayé, je suis habituellement à 730, j'ai déjà modifié mais pas de changements.

Fabrice

**Comment by Phil353556** [comment]
Bonjour,  ah ok, désolé, c'est le seul point qui m'est venu à l'esprit.
ensuite si vous regardez d'autres "issues" ouverts,  @guillaumezin suggère qq fois de faire off / on du plugin avec réenresgistrement, maintenant que l'API Enedis consentement refonctionne,  pourquoi pas ?
ou attendez le passage de @guillaumezin sur cet "issue" 202
Phil

**Comment by guillaumezin** [comment]
@Phil353556 a raison, il faut mettre une valeur suffisamment élevée dans "nombre de jours à récupérer pour les autres vues". Par contre, pour ne pas surcharger les serveurs, le plugin n'essaie que de temps à autres de récupérer beaucoup de données. Et souvent, quand on en demande trop, on se fait jeter par les serveurs Enedis. Donc 730, c'est en général trop, s'il vous manque les données de décembre, mettez 120 et soyez patient.

**Comment by fligozat** [comment]
Ok merci de l'info j'ai modifié la valeur mais en faisant une mauvaise manip j'ai supprimé mon matériel et maintenant le site enedis est en maintenance.
Je regarderais dans les jours à venir si les valeurs reviennent.

**Comment by fligozat** [comment]
Bonjour merci c'est bon j'ai récupéré mes données manquantes. c'est parfait.
