### ISSUE TITLE
annuler et reforcer le consentement

### ISSUE THREAD

**Issue by empierre** [guillaumezin/DomoticzLinky#203]
Bonjour,

  en changeant de fournisseur, enedis a supprime les informations compteurs... donc il récupère je ne sais où le compteur sur un consentement passé, et pour le faire récupérer les informations à nouveau depuis mon compte il faudrait que je puisse le rejouer.

  comment faire ?

**Comment by guillaumezin** [comment]
Bonsoir,

Si vous suivez les instructions dans https://github.com/guillaumezin/DomoticzLinky#probl%C3%A8mes-relatifs-%C3%A0-lobtention-du-consentement, est-ce que ça vous aide ?

**Comment by guillaumezin** [comment]
Bonsoir, je fais un peu de ménage, le plugin a beaucoup évolué depuis, je clos ce ticket sans activité depuis longtemps, vous le rouvrirez si le problème existe toujours.
