### ISSUE TITLE
Cela ne semble pas un problème du plugin mais c'est surprenant

### ISSUE THREAD

**Issue by Phil353556** [guillaumezin/DomoticzLinky#205]
Bonjour,
Le domoticz "suit" deux compteurs sans aucun problème ie consentement Ok.
Cependant sur le site enedis il est indiqué que le données ne sont pas partagées avec un tiers.

Auriez vous une explication ?  car je m'attendais à voir un partage avec domoticz/linky ou russandol par ex .
Merci beaucoup

![image](https://user-images.githubusercontent.com/64729485/228521089-25eb7343-65e3-4707-977b-f8db155a5337.png)

**Comment by guillaumezin** [comment]
Non, j'ai déjà constaté ça, je ne l'explique pas

**Comment by Phil353556** [comment]
Bonjour,
Ok
Merci pour votre retour

**Comment by Phil353556** [comment]
étrangeté d'enedis donc
