### ISSUE TITLE
Impossible de refaire le lien avec ENEDIS

### ISSUE THREAD

**Issue by Filnet53** [guillaumezin/DomoticzLinky#209]
...

**Comment by Filnet53** [comment]
Bonjour, tout fonctionnait bien (Bravo et merci pour ce plugin) mais depuis quelques jours, je n'ai plus de données affichées. Dans le log domoticz, on note une demande de se reconnecter avec un nouveau code XXXX-YYYY. Ce que je fais. J'arrive sur le site ENEDIS, saisie du nom et du mot de passe et j'arrive sur une page ENEDIS affichant une erreur 500.
Où est mon erreur?
Cordialement
Filnet

**Comment by guillaumezin** [comment]
Je ne comprends pas, ils sont censés m'informer par mail quand leur infrastructure tombe, je ne reçois pas de notification la moitié du temps.

Toujours est-il que l'API qui permet de se connecter est en panne :

![image](https://github.com/guillaumezin/DomoticzLinky/assets/541581/49c62a0a-e58b-4e11-91ae-b4c58b831b83)

**Comment by Filnet53** [comment]
On patientera jusqu'à ce qu'Enedis se réveille... 
Merci pour votre réponse et pour le travail effectué.

**Comment by fab85170** [comment]
Bonjour, j'ai du coup le même problème, y a t'il une url ou on peut checker l'état de l'api?

Merci

**Comment by busshi** [comment]
Bonjour, j'ai aussi une 404 lors du renouvellement du consentement, avant c'était une 500 il y a du progrès chez Enedis on dirait ;)

**Comment by guillaumezin** [comment]
Ca se passe ici : https://datahub-enedis.fr/services-api/etat-des-services

**Comment by Phil353556** [comment]
- TOP / Merci pour l'url partagée
- C'est surprenant pour ne pas dire plus, que l'indisponibilité (=panne) dure depuis 2 semaines, sans aucune visibilité de retour à la normale.

**Comment by guillaumezin** [comment]
Ils ont rendu l'URL publique, ce n'était pas le cas au début. Ils envoient également aux développeurs un mail, des fois avec une estimation de date de retour à la normale je crois. Mais souvent l'URL indique la panne plusieurs jours après que les problèmes commencent, en tout cas les utilisateurs du plugin vont en général plus vite qu'eux pour ouvrir un ticket ici ;-). Et je trouve que ça arrive trop souvent. En tout cas plusieurs fois par an.

**Comment by fab85170** [comment]
Merci :)

**Comment by ncelgoh** [comment]
La fenêtre de renouvellement de consentement est revenue mais il est impossible de la valider ! Une explication ?
Merci

**Comment by fab85170** [comment]
petit truc bête, tu as bien cliquer la case a cocher consentement? moi ca a marché, et le plugin refonctionne... niquel

**Comment by guillaumezin** [comment]
Ca doit refonctionner maintenant, vous confirmez ?

**Comment by Filnet53** [comment]
Bonjour, pas chez moi :-(
_Service indisponible
 
Nous sommes désolés, le serveur est momentanément indisponible. Veuillez réessayer ultérieurement_

**Comment by ncelgoh** [comment]
Bonjour Oui cela refonctionne.Merci Nicolas Celgoh8 La Chénais35230 ST ArmelLe 24 juin 2023 à 11:34, Filnet53 ***@***.***> a écrit :﻿
Bonjour, pas chez moi :-(
_Service indisponible
Nous sommes désolés, le serveur est momentanément indisponible. Veuillez réessayer ultérieurement_

**Comment by Filnet53** [comment]
çà y est, c'est reparti pour moi aussi sans aucune action de ma part.

**Comment by guillaumezin** [comment]
Ok, je clos.
