### ISSUE TITLE
GDPR / Stockage identifiants / cookies / données en tranist ?

### ISSUE THREAD

**Issue by Elerir** [guillaumezin/DomoticzLinky#210]
Bonjour,

Pardonnez moi si je me trompe, mais il me semble qu'il n'y a pas beaucoup d'info concernant les données qui transitent sur ce serveur dédié.
Concrètement, qu'est ce qui transite par ce serveur ? (tokens, identifiants, données de conso..) 
Merci d'avance,

**Comment by guillaumezin** [comment]
Bonjour,

Les informations sont données avant de vous rediriger pour le consentement : https://enedis.domoticz.russandol.pro/auth/redirect

Mais je vais devoir faire évoluer ce texte...

Je fais avec @oredin aussi des statistiques sur l'utilisation du plugin, non partagées, uniquement pour des raisons techniques (ça nous permet de constater des dysfonctionnements, d'avoir une idée de la charge et de vérifier que les gens basculent sur les dernières versions du plugin).

Dans le contrat passé avec Enedis, je n'ai demandé accès qu'aux tokens et aux données. Je n'ai pas accès aux identifiants, au nom, à l'adresse de livraison, vous pouvez le vérifier quand vous basculez sur le site d'Enedis pour le consentement, ils indiquent précisément les données partagées.

En revanche Enedis fait évoluer son infrastructure pendant l'été, pour se décharger sur la nôtre. Je me retrouve à gérer une partie de la sécurité (au lieu de distribuer un token par utilisateur, Enedis va gérer un token par contrat, donc je dois gérer le token par utilisateur), du coup les données transiteront également par le serveur pour ajouter une couche de sécurité, elles ne seront pas stockées.

Vous pouvez auditer le code source du serveur:
https://github.com/russandol-sarl/Device-Flow-Proxy-Server pour la version déployée
https://github.com/guillaumezin/Device-Flow-Proxy-Server pour la future version

Après vous n'êtes pas obligé de faire confiance, je ne peux pas prouver que la version en production est bien celle que je montre sur github, auquel cas il ne faut pas utiliser le plugin.

Bonne journée.

**Comment by oredin** [comment]
Bonjour,

Comme l'explique Guillaume, nous avons fait en sorte d'éviter d'avoir quelques données personnelles que ce soit pour justement nous éviter des contraintes relatives à la CNIL et aux règles européennes.

Les statistiques d'utilisation sont même anonymisées pour ce qui concerne les IPs.

Que ce soit Guillaume ou moi, nous mettons à disposition ce service de manière gratuite et bénévole. Nous n'avons aucun intérêt à nous compliquer la vie avec des réglementations contraignantes.

Au final, vous êtes seul juge de notre bonne foi et du fait que vous souhaitiez ou non utilisé le plugin.

Bonne journée.

**Comment by Elerir** [comment]
Je vous remercie pour ces informations. Selon mon temps disponible, je
déploierai soit votre proxy, soit j'utiliserai le votre (en participant aux
frais du coup)

**Comment by guillaumezin** [comment]
Attention, pour déployer votre proxy, il vous faut un code d'application que donne Enedis sur https://datahub-enedis.fr/services-api/data-connect . Par contre ils ne le donnent qu'aux sociétés, donc il vous faut une structure avec un SIRET. Et Enedis précise bien que ce code d'application ne doit pas être partagé, d'où l’intérêt de ce proxy qui garde le code secret au chaud...

**Comment by Elerir** [comment]
Merci pour ces informations qui m'avaient échappées!

Le dim. 2 juil. 2023 à 13:21, Guillaume Zin ***@***.***> a
écrit :
