### ISSUE TITLE
"Issues" disparues?

### ISSUE THREAD

**Issue by dltrainou** [guillaumezin/DomoticzLinky#212]
Bonjour
en regardant le "issues" ce matin je ne vois plus les dernières!!! 
Çà s’arrête a mai!!!
je voulais voir ou en était le pb de l'affichage  "invalid"
Est ce chez moi seulement?
Bonne journée et merci du taf Guillaumezin

**Comment by guillaumezin** [comment]
Bonjour, il a été clos par la personne qui l'a créé, github.com filtre par défaut ceux qui sont clos, je vais le rouvrir, il est ici : https://github.com/guillaumezin/DomoticzLinky/issues/211

**Comment by dltrainou** [comment]
OK merci, je suis aussi passé sur la beta, ça a planté mais après reboot, pas de pb. Merci et bonne journbée

 

De : Guillaume Zin ***@***.***> 
Envoyé : mardi 1 août 2023 08:48
À : guillaumezin/DomoticzLinky ***@***.***>
Cc : dltrainou ***@***.***>; Author ***@***.***>
Objet : Re: [guillaumezin/DomoticzLinky] "Issues" disparues? (Issue #212)

 

Bonjour, il a été clos par la personne qui l'a créé, github.com filtre par défaut ceux qui sont clos, je vais le rouvrir, il est ici : #211 <https://github.com/guillaumezin/DomoticzLinky/issues/211>
