### ISSUE TITLE
Plugin non reconnu

### ISSUE THREAD

**Issue by jsn54** [guillaumezin/DomoticzLinky#215]
Bonjour à tous,
je viens de faire une installation de Domoticz 2023.2 (build 2023-07-21) sur un raspberry Pi Zero (distribution *dietpi* bullseye). Python 3.9 en environnement 'dev' est installé et reconnu par Domoticz (fenêtre 'à propos': Python Version: 3.9.2 (default, Mar 12 2021, 04:06:34) [GCC 10.2.1 20210110]).
Le plugin DomoticzLinky lui-même est installé dans le répertoire *ad hoc* et le script mis en exécutable:

    dietpi@DietPiZero:~$ ls -ail /opt/domoticz/plugins/DomoticzLinky/
    total 208
    138413 drwxr-xr-x 5 root     root       4096  5 août  12:30 .
    133122 drwxr-xr-x 5 domoticz domoticz   4096  5 août  12:30 ..
    141183 drwxr-xr-x 2 root     root       4096  5 août  12:30 assets
    138416 drwxr-xr-x 8 root     root       4096  5 août  12:30 .git
    141165 drwxr-xr-x 2 root     root       4096  5 août  12:30 .github
    141182 -rw-r--r-- 1 root     root      34523  5 août  12:30 LICENSE
    141214 -rwxr-xr-x 1 root     root     119286  5 août  12:30 plugin.py
    141215 -rw-r--r-- 1 root     root      30362  5 août  12:30 readme.md

L'environnement Python est bien installé par *dietpi-software* (#130 : Python3 + environnement *dev*):

    dietpi@DietPiZero:~$  dpkg --get-selections | grep python
    libpython3-dev:armhf				install
    libpython3-stdlib:armhf				install
    libpython3.9:armhf				install
    libpython3.9-dev:armhf				install
    libpython3.9-minimal:armhf			install
    libpython3.9-stdlib:armhf			install
    python3						install
    python3-dev					install
    python3-distutils				install
    python3-lib2to3					install
    python3-minimal					install
    python3.9					install
    python3.9-dev					install
    python3.9-minimal				install

Pourtant l'entrée "Linky" n'apparait pas dans les types de dispositifs disponibles, et les logs de démarrage sont vides (aucun défaut). Pouvez-vous m'indiquer les démarches complémentaires pour diagnostiquer le problème ? Merci d'avance

**Comment by guillaumezin** [comment]
Bonjour, confirmez-vous que domoticz est installé dans /opt/domoticz ? Chacun des ces répertoires étant accessibles à tous en lecture et exécution ? Ou bien Domoticz est il dans un container ?

**Comment by jsn54** [comment]
Oui, je confirme que domoticz est bien installé "à sa place" et avec les droits adaptés:

    dietpi@DietPiZero:~$ ls -ail /opt/domoticz/
    total 13772
    131092 drwxr-xr-x   7 domoticz domoticz     4096  5 août  09:35 .
    8198 drwxr-xr-x   3 root     root         4096  5 août  09:35 ..
    132150 drwxr-xr-x 121 domoticz domoticz     4096 31 janv.  2022 Config
    131093 -rwxr-xr-x   1 domoticz domoticz 13901080 21 juil. 17:29 domoticz
    131096 -rw-r--r--   1 domoticz domoticz     5936 25 avril 09:15 domoticz.sh
    133142 drwxr-xr-x   4 domoticz domoticz     4096  9 nov.   2020 dzVents
    131094 -rw-r--r--   1 domoticz domoticz   113293 21 juil. 17:26 History.txt
    131095 -rw-r--r--   1 domoticz domoticz    35147  9 nov.   2020 License.txt
    133122 drwxr-xr-x   5 domoticz domoticz     4096  5 août  12:30 plugins
    132067 drwxr-xr-x   9 domoticz domoticz     4096 30 avril 11:21 scripts
    131115 -rw-r--r--   1 domoticz domoticz     3414  9 nov.   2020 server_cert.pem
    131116 -rwxr-xr-x   1 domoticz domoticz     1721 30 avril 11:21 updatebeta
    131117 -rwxr-xr-x   1 domoticz domoticz      857 30 avril 11:21 updaterelease
    131118 drwxr-xr-x  14 domoticz domoticz     4096  6 juin  14:31 www

Domoticz est exécuté en "direct", ni container ni VM. L'interface web fonctionne bien, les planning sur les interrupteurs aussi.
La page de log (sur l'appli web) est vide. Merci d'avance pour votre aide. Jai déjà réussi à installer et exécuter ce plugin sur une précédente installation, je ne comprends pas trop ce qui a pu changer...

**Comment by jsn54** [comment]
Merci pour votre disponibilité et l'attention que vous portez à ma demande. Comment puis-je accéder au log complet ? J'ai regardé sur /var/log mais il n'y a pas d'entrée Domoticz. Merci d'avance pour votre aide !

**Comment by guillaumezin** [comment]
Bonjour, essayez ceci : https://www.domoticz.com/wiki/Troubleshooting#Check_the_Domoticz_log_files

**Comment by guillaumezin** [comment]
Bonsoir, je fais un peu de ménage, le plugin a beaucoup évolué depuis, je clos ce ticket sans activité depuis longtemps, vous le rouvrirez si le problème existe toujours.
