### ISSUE TITLE
Utilisation derniers 7 jours charts context menu

### ISSUE THREAD

**Issue by Jeffdeleffe** [guillaumezin/DomoticzLinky#22]
Bonjour sur la vue charts context menu, il est impossible de faire dérouler le menu pour exporter les données en format csv ou xls. En faisant zoom page cela est possible

* Please indicate your version of
  * Domoticz : 4.11307  beta
  * Operating system : raspbian
  * Computer type Raspberry Pi 3 B+

![Capture d’écran (1)](https://user-images.githubusercontent.com/15414543/64850043-ef0ff080-d614-11e9-8e8c-cf083f93cf4d.png)

**Comment by guillaumezin** [comment]
Bonjour, je comprends bien votre problème. Vous êtes sous Firefox je crois. Quelle version de Firefox, et quel OS ? Sous Linux, avec Firefox 69.0, je n'ai pas ce problème. Pouvez-vous essayez avec un autre navigateur.

Ceci dit, ce n'est pas le plugin qui gère cette vue, il ne fait que mettre les données à disposition de Domoticz. Autrement dit, c'est un bug à adresser à Domoticz (sur leurs forums https://www.domoticz.com/forum - en anglais - ou sur https://github.com/domoticz/domoticz) plutôt qu'ici.

**Comment by guillaumezin** [comment]
Je remarque que l'interligne dans votre menu est beaucoup plus large que sur mon système, avez-vous changé des paramètres de police de caractères ?

![image](https://user-images.githubusercontent.com/541581/64889989-d9c7b000-d66e-11e9-9173-d8912269da3e.png)

**Comment by guillaumezin** [comment]
Sans nouvelle, je close le ticket.
