### ISSUE TITLE
dossier de sauvegarde historique consommation Linky

### ISSUE THREAD

**Issue by gdv45** [guillaumezin/DomoticzLinky#223]
Bonjour,

Une question toute simple d'un néophyte : L'historique des consommations d’électricité du compteur Linky récupéré par le plugin est il enregistré quelque part sur le raspberry et si oui à quel endroit. Mon besoin est de récupérer cet historique supérieur à 2 ans sur une sauvegarde de domoticz pour la mettre sur mon domoticz actuel (qui est vierge suite à une fausse manip et au problème actuel d'Enedis).

J'ai un raspbery Pi 3B (modèle 022082) sous Raspbian Buster avec Domoticz 2021.1

Merci pour votre aide

gdv45

PS : j'y connais pas grand chose en langage linux, je suis tout juste capable d'adapter un commande qu'on me donne à mon cas particulier

**Comment by guillaumezin** [comment]
Bonsoir,

Tout est sauvegardé dans la base de données de Domoticz, donc si vous restaurez votre sauvegarde Domoticz, normalement ça vient avec.

**Comment by gdv45** [comment]
Ok. Y a til une autre solution car si je fais comme vous proposé, je vais perdre l'hisorique de certaine sondes de température (je fais pas de sauvegarde automatique de ma db). Il me faudrait vraiment du spécifique du plugin Linky.

Cordialement,
gdv45

**Comment by guillaumezin** [comment]
Dans ce cas vous devez éditer l'ancienne base de données domoticz.db avec un logiciel type sqlitebrowser, copier la ligne qui correspond au plugin linky de la table DeviceStatus et les données correspondant (DeviceRowID correspondant au ID de DeviceStatus) de la table MultiMeter_Calendar.

Après ça ne me paraît pas très utile, quand le plugin refonctionnera, on peut le paramétrer pour récupérer plusieurs années d'historique.

**Comment by gdv45** [comment]
Complétement d'accord avec vous. Mon problème est que j'ai besoin de récupérer environ 3 ans et que domoticz ne me permet d'en récupérer que 2. Le grand chef du plugin à t il une solution ?

Cordialement,
gdv45

**Comment by guillaumezin** [comment]
Comme je le disais, sinon il faut récupérer de l'ancienne base de données avec sqlitebrowser et injecter dans la nouvelle. Je ne l'ai jamais fait mais ça ne doit pas être très difficile.

**Comment by gdv45** [comment]
Bonjour,

Merci pour les info. Je vais commencer par attendre que tout refonctionne, je récupérerai le max d'historique et si ça suffit pas je compléterai en jouant avec la db.

Bon courage dans la suite de vos projets.

Cordialement,

gdv45
