### ISSUE TITLE
Expression des données en kWh

### ISSUE THREAD

**Issue by laservert2** [guillaumezin/DomoticzLinky#227]
Bonjour,
Je viens de découvrir un manque d'homogénéité  dans l'expression des consommations.
Cela est également perturbant au niveau de l'évolution de la consommation journalière lorsque l'on passe de 999 Wh à 1,000 Wh.
 Il a lieu, me semble-t-il, utile  de définir si le séparateur des milliers est l'espace, le point ou la virgule.

![IMG20231128124144](https://github.com/guillaumezin/DomoticzLinky/assets/138762562/2c0234cd-9718-4efc-9443-f9d6f7cefc01)

**Comment by guillaumezin** [comment]
Bonjour,
Oui, c'est très anglo-saxon comme façon de présenter, mais il ne s'agit pas d'un problème de plugin, mais d'un problème dans Domoticz même, je suis désolé, je ferme ce ticket, je ne tiens pas trop à mettre les mains dans le cambouis de Domoticz, je ne l'ai que trop fait, je vous recommande de demander directement de l'aide sur https://github.com/domoticz/domoticz/issues/
