### ISSUE TITLE
Pas de création du deuxième "device" compteur

### ISSUE THREAD

**Issue by walawa75** [guillaumezin/DomoticzLinky#228]
Comme je l'avais précisé dans un précédent post un deuxième Device compteur ne peut pas être monitoré alors que j'ai bien activé le consentement pour deux compteurs.
Le premier compteur s'affiche et remonte parfaitement tandis que le deuxième ne se crée même pas. Je n'avais pas ce problème autrefois.
Sinon grand merci à @guillaumezin pour cet excellent travail.

**Comment by vryf** [comment]
Je viens de relancer le consentement à l'instant et je rencontre exactement le même problème. 
J'ai transmis le log en mode debug simple à @guillaumezin pour analyse.

**Comment by oredin** [comment]
> @oredin tu confirmes que ça ne peut pas être un effet de bord d'un proxy, qui supprimerait virgule et tout ce qui suit lors de la réception du paramètre GET usage_point_id vers /auth/redirect ?

Hello,

A priori, il n'y a pas de raison que les paramètres soient modifiés. Fais moi suivre les traces pour que je jette un oeil sur les logs côté infra.

**Comment by guillaumezin** [comment]
@oredin Je t'ai envoyé le log, mais tu n'y apprendras pas grand chose...

**Comment by PatP33** [comment]
Bonjour,
J'ai le même problème, les données pour le 2eme compteur ne sont plus récupérées depuis le 10 septembre malgré plusieurs redémarrages, redemandes de consentement. 
J'espère que Enedis va rapidement corrigé le problème.
J'en profite pour dire un grand merci à @guillaumezin pour ce plugin.

**Comment by fredbarth** [comment]
Bonjour, même problème, 2 compteurs enregistrés sur le matériel Linky dans domoticz, les 2 sont autorisés sur l'interface enedis, et rien ne remonte du deuxième. Dans les logs seul le premier apparait, et la remontée des données ne fonctionne bien sur que sur ce dernier.
Les comptes doivent toujours être saisis avec seulement un espace entre eux, ou bien y a-t-il une nouvelle convention?
Merci bien évidemment guillaumezin, et brûlons un cierge pour la vitesse d'Enedis

**Comment by guillaumezin** [comment]
Bonjour, j'ai envoyé une question à Enedis il y a quelques jours mais je n'ai pas encore de réponse.

> Les comptes doivent toujours être saisis avec seulement un espace entre eux, ou bien y a-t-il une nouvelle convention?

De quoi parlez-vous ? Depuis maintenant longtemps vous n'avez pas à saisir vos numéros de compteur dans les paramètres du plugin (mais j'ai peut-être mal compris ce que vous voulez dire), vous avez normalement juste à les sélectionner au moment de la demande de consentement, quand vous êtes envoyé sur votre compte Enedis.

**Comment by guillaumezin** [comment]
Bonsoir,
J'ai reçu une réponse d'Enedis :

```
Bonjour,

En effet, il est maintenant possible d’obtenir le consentement pour plusieurs PRM en un seul appel, les PRM sont renvoyés en paramètres de l’url de redirection, séparés par des virgules.

Si ce n’est pas le cas pour vos clients, Pouvez-vous nous envoyer par retour de mail :
-          Un exemple de Curl utilisé par un de vos clients possédant plusieurs PRM
-          La date et l’heure de son essai
-          Le résultat après cet essai

Cela nous permettra de mieux analyser l’origine du problème.

Dans l’attente d’un retour de votre part, nous restons à votre écoute.
```
Donc d'après cette réponse, nous sommes bien face à une anomalie. Je vais dans un premier temps reprendre le log que vous m'avez fait parvenir pour essayer de débusquer ça.

**Comment by vryf** [comment]
Bonjour,
Je reviens aux nouvelles concernant le traitement de cette anomalie.
Avez vous pu identifier l'origine du problème ?
Envisagez vous une mise à jour du plugin ?
Merci d'avance,
Cordialement,
Frédéric

Le lun. 11 déc. 2023 à 21:42, Guillaume Zin ***@***.***> a
écrit :

**Comment by guillaumezin** [comment]
Bonsoir,
J'ai renvoyé des informations à Enedis, la balle est dans leur camp, mais ils ne sont pas réactifs...

**Comment by walawa75** [comment]
Bonjour à tous,
La baballe serait t'elle revenue depuis 2 mois ? :-)

**Comment by guillaumezin** [comment]
Ils ont répondu, complètement à côté de la question, ils faut que je les relance, je ne l'ai pas fait.

**Comment by vryf** [comment]
Bonjour à tous,
Entre temps, j'ai contourné le problème en créant autant de "materiels"
linky que de contrats à suivre...
Au final ça marche aussi bien :)




Le sam. 17 févr. 2024 à 19:38, Guillaume Zin ***@***.***> a
écrit :

**Comment by damf25** [comment]
> Bonjour à tous, Entre temps, j'ai contourné le problème en créant autant de "materiels" linky que de contrats à suivre... Au final ça marche aussi bien :) 

Bonjour

Pouvez-vous me dire comment vous avez procédé pour créer un nouveau matériel Linky et affecter à chacun un compteur différent ?
Merci

**Comment by vryf** [comment]
Bonjour,
C'est assez simple:
- Dans Domoticz/Configuration/Matériels, choisir un nouveau materiel de
type "Linky", le nommer par exemple "Compteur Linky maison A", et cliquer
sur "Ajouter"
- Surveiller le log et copier le lien vers l'adresse internet pour valider
le consentement
- Sur la page de consentement, ne cocher que le compteur qui vous intéresse
et valider.
- Domoticz va alors rapatrier l'historique de ce compteur.
- Refaire cette opération pour chaque contrat ("Compteur Linky maison
B"...) en sélectionnant lors du consentement les compteurs chacun à leur
tour.
Bon courage,

**Comment by damf25** [comment]
Merci, ça marche parfaitement, j'ai pu récupérer mon deuxième compteur.

**Comment by guillaumezin** [comment]
Bonjour, j'ai bon espoir de corriger le problème dans la semaine qui vient. Il s'agit d'une erreur d'une erreur de documentation Enedis couplée à un choix technique malheureux qui m'oblige à adapter l'infrastructure de consentement, je vous tiens au courant.

**Comment by walawa75** [comment]
Bonjour Guillaume, ça c'est vraiment une bonne nouvelle !! Merci de nous tenir au courant car à l'instar d'autres personnes je n'ai jamais réussi à faire fonctionner 2 comptes séparément. 
D'autre part ayant aussi un compte enedis pro est t'il possible de rediriger la demande de consentement vers l'adresse estampillée pro ? Car ça redirige systématiquement vers l'adresse particulier.

**Comment by guillaumezin** [comment]
Bonjour,
On ne parle peut-être pas de la même chose, si vous avez 2 comptes séparés, je ne peux pas faire grand chose, il faut créer 2 instances du plugin. Par contre si vous avez 2 compteurs (ou plus) qui apparaissent sur le même compte, le plugin va bientôt pouvoir tout récupérer.
Concernant le compte pro, je suis surpris, Enedis dans sa documentation n'indique pas plusieurs adresses différentes pour les pro et pour les particuliers, pourriez-vous me montrer un exemple (avec capture d'écran) ?
Merci.

**Comment by guillaumezin** [comment]
Bonjour,

L'infrastructure intermédiaire a été corrigée pour prendre en charge les comptes avec plusieurs compteurs. Je m'excuse du temps que ça a pris, nous en avons profité pour moderniser le code, et la mise au point a été fastidieuse. Pouvez-vous me dire si maintenant ça fonctionne ? Vous devez cependant relancer le consentement, cf. https://github.com/guillaumezin/DomoticzLinky?tab=readme-ov-file#probl%C3%A8mes-relatifs-%C3%A0-lobtention-du-consentement

Merci pour vos retours.

**Comment by PatP33** [comment]
Bonjour
Tout fonctionne très bien. Les 2 compteurs se mettent bien à jour.
Merci beaucoup

**Comment by guillaumezin** [comment]
Bonjour, je clos. Concernant les comptes pro, Enedis m'a indiqué que l'API que j'utilise ne les prends pas en charge et ça sous-entendait que ce ne serait pas le cas dans le futur, car ils m'ont demandé d'utiliser l'API SGE tiers qui n'a rien à voir, donc ce ne sera pas fait avec ce plugin.
