### ISSUE TITLE
Graphe 24h qui n'affiche que 4h

### ISSUE THREAD

**Issue by mooky31** [guillaumezin/DomoticzLinky#232]
Bonjour,

Une idée de pourquoi le graphe 24h n'affiche que 4h ? (screenshot pris à 18h54)
![image](https://github.com/guillaumezin/DomoticzLinky/assets/54031618/e37201ce-6b1a-453a-88b3-38b3b7e076ed)

Les autres graphes fonctionnent bien.
Domoticz 2024.1, plugin linky mis à jour hier, raspberry 3b, debian buster

**Comment by Phil353556** [comment]
Bonjour, cela me semble normal, en haut à droite c'est indiqué 3h 1h 
Cordialement

**Comment by mooky31** [comment]
3h 1h sont censés etre des niveaux de zoom sélectionnables - du moins les autres graphes marchent comme ça. Mais là je n'ai pas cliqué dessus, cf l'absence de bouton "réinitialiser".
Quand je clique sur 3h ou 1h, le graphe ne bouge pas. Un bouton réinitialiser apparaît. Si je clique sur réinitialiser, il ne se passe rien.

**Comment by guillaumezin** [comment]
Ca doit vouloir dire qu'il manque des données dans le paquet reçu. Attendons de voir demain s'il y a un trou.

**Comment by mooky31** [comment]
Capture de ce matin, 8h18
![image](https://github.com/guillaumezin/DomoticzLinky/assets/54031618/54ad5ac6-5dfd-409d-b6ab-7b663c1bc8b1)

Le graphe a bien rallongé, mais il finit toujours à 23h, alors qu'il est 8h.
J'ai vérifié l'heure système sur le raspi elle est OK.
domoticz@domoticzpi:~ $ date
ven. 12 janv. 2024 08:19:08 CET

Je précise que l'installation du plugin linky date de plusieurs mois, et fonctionnait à l'époque.
Aucune idée de quand le graphe 24h a cessé de fonctionner par contre, je ne le regarde pas tous les jours.

Le graphe semaine a l'air OK : 
![image](https://github.com/guillaumezin/DomoticzLinky/assets/54031618/1c6e8b56-e729-496d-b67c-7c697967aba5)

**Comment by guillaumezin** [comment]
Le plugin ne récupère, entre 7h et 9h, les données que de la veille, c'est une limitation de l'API Enedis. Donc tout semble normal à présent.

**Comment by mooky31** [comment]
OK, merci d'avoir pris le temps de me répondre
