### ISSUE TITLE
pas de dispositif linky dans l'onglet "mesures"

### ISSUE THREAD

**Issue by defaliz** [guillaumezin/DomoticzLinky#233]
bonjour,
merci pour ce plugin
je reçois bien les infos de mon linky mais il n'y a rien dans l'onglet mesure... pas de dispositif linky...

voici les logs :
Linky: Récupération des données avec l'historique court
2024-01-24 13:44:37.071 Status: Linky: Traitement pour le point de livraison xxxxxxxx
2024-01-24 13:44:37.314 Status: Linky: Prochaine connexion : 2024-01-25 08:07:37

une idée ?
merci

**Comment by guillaumezin** [comment]
Bonsoir,
Cf. https://github.com/guillaumezin/DomoticzLinky#configuration est-ce que "Accepter de nouveaux dispositifs matériels" est activé au moins temporairement (Configuration / Paramètres / Système / Matériel/dispositifs) ?

**Comment by defaliz** [comment]
Merci Guillaume, après vérification tout fonctionne au poil !
à quoi sert "utilisation 2" dans le graphe ?
bonne journée
Alain
