### ISSUE TITLE
Consentement, compteur incompatible

### ISSUE THREAD

**Issue by qdel** [guillaumezin/DomoticzLinky#236]
Hello,

Pas vraiment un souci avec le plugin car je ne l'utilise pas. Mais j'utilise le proxy https://enedis.domoticz.russandol.pro/.

Comme les issues ne semblent pas regardé de ce coté, je tente mon coup ici: https://github.com/russandol-sarl/Device-Flow-Proxy-Server/issues/15.

**Comment by guillaumezin** [comment]
Oui, on a remarqué le problème, j'ai questionné Enedis et ils m'indiquent que c'est une panne chez eux, il faut maintenant patienter...

**Comment by qdel** [comment]
Ok, je vais donc continuer dans mon check journalier :)

**Comment by qdel** [comment]
Fonctionne depuis ce matin !
