### ISSUE TITLE
Perte du graphique journalier HC/HP

### ISSUE THREAD

**Issue by rcrocus** [guillaumezin/DomoticzLinky#238]
Bonjour,

Depuis une mise à jour Domoticz en 2024.4 version 16025 (BETA), je n'ai plus sur le graphique qui listait par jour le total des HC/HP (avec la comparaison possible avec l'année précédente). Ce graphique m'était très pratique pour mon suivi quotidien  (il était intitulé "Sur la semaine passée", présent dans le fichier README si vous voulez voir à quoi il ressemblait)

A la place il a été remplacé par un graphique qui liste par heure la consommation.

Savez-vous s'il est possible de récupérer l'ancien graphique ?

En vous remerciant par avance.
Cordialement.

**Comment by guillaumezin** [comment]
Bonjour,
J'ai installé la version beta Version: 2024.4 (build 15998), sur cette version il y a effectivement un nouveau graphique utilisation par heure, mais le graphique de la semaine passée existe toujours. Avez-vous vidé le cache ? Faites CTRL+F5, si non suffisant, regargez https://www.domoticz.com/DomoticzManual.pdf page 35.
De toute façon, les données sont toujours là, donc rien n'est perdu. Notez que ce n'est pas le plugin qui gère les graphiques, mais bien Domoticz.
Vous me direz si l'effactement du cache a résolu le problème ?
De mon côté je vais installer une beta encore plus récente pour voir si c'est une régression.

**Comment by guillaumezin** [comment]
Je suis passé à la build 16027 et je constate la même chose que vous. Je vais essayer de trouver où est la régression et le signaler aux mainteneurs de Domoticz, en espérant qu'ils corrigent eux-mêmes. Non pas que je ne sache pas le faire, mais c'est des fois un peu chronophage...

**Comment by guillaumezin** [comment]
C'était facile, c'est ici, ils ont fait exprès de l'enlever :

https://github.com/domoticz/domoticz/commit/8e8f3a58d0600e8b1caddab28e17809f0ad637df

Et maintenant, ça va être le bras de fer pour le remettre...

**Comment by guillaumezin** [comment]
Question subsidiaire : comment faisiez-vous la comparaison ? Chez moi ça n'a jamais fonctionné...

**Comment by guillaumezin** [comment]
J'ai essayé de discuter, j'ai reçu une fin de non-recevoir, avec un peu de condescendance, comme je m'y attendais.

**Comment by rcrocus** [comment]
Bonsoir,
Merci pour tes recherches et ton analyse précise.
Je viens également de voir tes échanges côté Domoticz....dommage d'être aussi fermé.

De mon côté, j'ai réussi à retrouver les infos du côté des rapports : http://ip:port/#/Devices/DeviceID_Linky/Report/2024/6

Cordialement.
