### ISSUE TITLE
Trop d'échecs de communication, le plugin réessaiera plus tard  depuis le  17 Juillet 2024

### ISSUE THREAD

**Issue by jacquesclowez** [guillaumezin/DomoticzLinky#239]
Bonjour à tous,

Info   machine :  OS: Debian 12  sur terminal  Dell Wyse ( ssd 240 Go avec 8 Go ram).
info OS:
root@domoticz:/home/domoticz#  lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 12 (bookworm)
Release:        12
Codename:       bookworm
root@domoticz:/home/domoticz# uname -a
Linux domoticz 6.1.0-22-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.94-1 (2024-06-21 ) x86_64 GNU/Linux

Info Domoticz:
domoticz version  Version: 2024.7
Build Hash: b317cfab1
Compile Date: 2024-07-13 16:59:31
dzVents Version: 3.1.8
Python Version: 3.11.2 (main, May 2 2024, 11:59:08) [GCC 12.2.0]

Version 2.5.7 du plugin

j'ai systématiquement l'erreur 👍 :
2024-07-20 12:35:36.094 Status: Linky: Traitement pour le point de livraison xxxxxxxxxxxxxxx
2024-07-20 12:36:16.091 Status: Linky: Durant l'étape : retry - Trop d'échecs de communication, le plugin réessaiera plus tard
2024-07-20 12:36:16.114 Status: Linky: Prochaine connexion : 2024-07-20 13:36:16
2024-07-20 13:00:00.857 Status: Starting automatic database backup procedure... 
 depuis le 17 Juillet 2024. 
Les services Enedis (https://datahub-enedis.fr/services-api/etat-des-services/) sont OK.

Suis-je le seul ????  . Domoticz fonctionne très bien, l' update du plugin Linky à été faite. Tout semble correct.
dans les logs,,,,un pb avec enedis.domoticz.russandol.pro ??

en pj  un fichier log.    

Un petit conseil  svp      .... merci 

[DomoticzLinky_2024_07_20_13_57_18_5e89vyue.log](https://github.com/user-attachments/files/16320773/DomoticzLinky_2024_07_20_13_57_18_5e89vyue.log)

**Comment by guillaumezin** [comment]
Pareil chez moi, je pense que c'est une panne Enedis, leur site qui reflète l'état des services à toujours un temps de retard. Enedis renvoie une erreur technique. Sans rire, ça tombe en panne à chaque vacances, comme si la personne chargée d'appuyer sur le bouton n'était pas là...

**Comment by Phil353556** [comment]
Bonjour,
Idem 
- Problème indiqué dans le fichier journal depuis : 2024-07-18 08:09:56.055
- Messages  : 
 * "_Durant l'étape getdatahours de 2024-07-11 à 2024-07-18 - Pas de données disponibles, ni en consommation, ni en production, avez-vous associé un compteur à votre compte et demandé l'enregistrement et la collecte des données horaire sur le site d'Enedis (dans "Gérer l'accès à mes données") ?_"
 * "_Durant l'étape : retry - Trop d'échecs de communication, le plugin réessaiera plus tard_"

Il semble que l'on soit parti pour un certain temps sans données ...

**Comment by DRbuntu91** [comment]
Bonjour
J'ai la même erreur - et plus de données depuis mercredi 17 juillet:
2024-07-21 09:06:59.222 Status: Wops: Récupération des données avec l'historique court
2024-07-21 09:06:59.271 Status: Wops: Traitement pour le point de livraison xxxxxxxxxxxxxx
2024-07-21 09:07:39.059 Status: Wops: Durant l'étape : retry - Trop d'échecs de communication, le plugin réessaiera plus tard
2024-07-21 09:07:39.240 Status: Wops: Prochaine connexion : 2024-07-21 10:07:39`

Par contre je viens de me connecter sur l'interface web de ENEDIS et mes données sont bien la (horaire et journalier).

J'ai aussi re-vérifié les services ENEDIS avec le lien donné par jacquesclowez

Du coups si les services ENEDIS sont OK et les données sont disponibles, le pb. se situe ou?

Willy

**Comment by guillaumezin** [comment]
Bonjour, ça refonctionne depuis, je me trompe ?

**Comment by Phil353556** [comment]
Bonjour,
Oui c'est Ok
dernier message d'erreur fût ce matin : 
`2024-08-07 08:05:37.398 Error: Compteur xxxxx: Durant l'étape getdatahours de 2024-07-10 à 2024-07-17 - Erreur status : 503 - code Service Unavailable - description : Service unavailable for the moment. Please try later.`

Ensuite c'est bon et tout l'historique semble avoir été récupéré

Cordialement

**Comment by jacquesclowez** [comment]
Bonjour,

le plugin semble être de nouveau fonctionnel... J 'ai malgré tout encore l'erreur :

024-08-08 13:24:31.285 Status: Linky: Initialized version 2.5.7, author 'Barberousse'
2024-08-08 13:24:31.288 Linky: Heures creuses mises à 21h00-23h00 01h30-07h30
2024-08-08 13:24:31.288 Linky: Consommation à montrer sur le tableau de bord mis à mean_cmonth / peak_day
2024-08-08 13:24:31.288 Linky: Nombre de jours à récupérer pour la vue par heures mis à 7
2024-08-08 13:24:31.288 Linky: Nombre de jours à récupérer pour les autres vues mis à 32
2024-08-08 13:24:31.288 Linky: Nombre de jours à récupérer pour le calcul du pic mis à 1
2024-08-08 13:24:31.288 Linky: Debug mis à 0
2024-08-08 13:24:31.302 Linky: Cache chargé depuis le disque
2024-08-08 13:24:31.302 Linky: Si vous ne voyez pas assez de données dans la vue par heures, augmentez le paramètre Log des capteurs qui se trouve dans Réglages / Paramètres / Historique des logs
2024-08-08 13:24:41.076 Status: Linky: Récupération des données avec l'historique court
2024-08-08 13:24:41.082 Status: Linky: Traitement pour le point de livraison 02284659869686
2024-08-08 13:24:57.891 wyse_salon: General/Percentage (CPU_wyse_salon)
2024-08-08 13:25:21.074 Status: Linky: Durant l'étape : retry - Trop d'échecs de communication, le plugin réessaiera plus tard
2024-08-08 13:25:21.102 Status: Linky: Prochaine connexion : 2024-08-08 14:25:21 

Cependant des données ont été collectées  avec un trou du 22 au 30 Juillet 2024, et également le 7 Aôut 2024., c'est peut-être du à un trop grand nombre de connexions . 
A vrai dire , je ne vois pas trop quoi faire pour les données manquantes,  sont t'elles perdu définitivement ?
Je suis à l'écoute d'un conseil .... merci...

**Comment by jacquesclowez** [comment]
Bonjour, 

merci Guillaumezin pour cette réponse... j'avais déjà augmenté le nombre de jour  mais je ne savais pas  que le plugin essayait  "de temps en temps   pour ne pas surchargé.......". il suffit donc d'être patient :) ..........
A+

**Comment by jacquesclowez** [comment]
Bonjour Guillaumezin  et à tous ,

juste une petite question, effectivement il y a des erreurs de communication depuis le 6 Août 2024 donc pas de récupération de données,  est-ce un trop grand nombre de connexion ou un problème coté Enedis ?
faut-il simplement être patient ou ai-je une action à faire de mon coté. :)
merci ...

**Comment by guillaumezin** [comment]
Bonjour,

@jacquesclowez : de mon côté ça tourne comme une horloge. Des fois il s'agit d'un problème local sur un compteur donné, dans ce cas il faut ouvrir un ticket de support auprès d'Enedis. Pouvez-vous mettre "Debug" sur "Avancé" et m'envoyer votre log sur mon mail visible sur https://github.com/guillaumezin pour que j'y vois plus clair ?

**Comment by guillaumezin** [comment]
@jacquesclowez : merci pour vos logs. Voyez-vous vos données sur le site d'Enedis ?
Je vois des messages "Technical error. Please try later" précédés de "Via':'HTTP/1.1 enedis.domoticz.russandol.pro", ça veut dire que le message d'erreur est envoyé par Enedis, qu'il n'est pas du fait du plugin, il ne peut pas inventer les données.
Il faudra probablement demander l'aide d'Enedis via le formulaire de contact https://datahub-enedis.fr/services-api/contacter-le-service-api/
Il y avait aussi un forum où on pouvait demander de l'aide mais ça fait des mois qu'ils est en maintenance...

**Comment by jacquesclowez** [comment]
Bonjour Guillaume,
dans les logs, j'avais des "trous"  qui se répercutaient dans l'affichage.... Normal..... je pense que le cache était altéré... j'ai donc fait une raz du cache et refait une demande de consentement  suite au message  "Technical error. Please try later" précédés de "Via':'HTTP/1.1 enedis.domoticz.russandol.pro"  présent dans les traces... 
Tout est OK maintenant.... merci  pour ton aide  et bravo pour ta disponibilité. :(
cordialement, Jacques

**Comment by guillaumezin** [comment]
Merci pour le retour, j'en déduis qu'un erreur technique en boucle peut être réglée par un reset consentement, je pense que c'est indépendant du cache. Je vais enrichier le readme avec cette information.
