### ISSUE TITLE
Compteur Total Linky non visible.

### ISSUE THREAD

**Issue by Alexofhiswalnut** [guillaumezin/DomoticzLinky#24]
Bonjour,

j'ai installé Domoticz sur un Raspberry Pi3 avec votre script Linky. Tout fonctionne bien sauf que je n'a pas les données du compteur Total, j'ai juste les données de la journée précédente qui s'affiche sur le Dashboard. Voir photo :
![image](https://user-images.githubusercontent.com/18416783/69425206-cbf77080-0d2a-11ea-88f6-14b205100b2d.png)

Pouvez-vous afficher en plus les données total du compteur ?

Merci par avance.

Version: 4.10717
Build Hash: b38b49e5
Compile Date: 2019-05-09 13:04:08
dzVents Version: 2.4.19
Python Version: 3.7.3 (default, Apr 3 2019, 05:39:12) [GCC 8.2.0]
Rasbian 10

**Comment by guillaumezin** [comment]
Bonjour,

Je travaille à une nouvelle version qui permettra effectivement de récupérer et d'afficher plus d'information. Vous pouvez déjà dans les paramètres du plugin choisir d'afficher la valeur de la journée précédente, de la semaine, du mois ou de l'année. Enedis a "ouvert les vannes" pour les programmeurs et je suis reconnu officiellement comme développeur donc j'ai accès à leur modèle de données. Par contre il va falloir être patient, ça me fait refaire beaucoup de choses.

Guillaume

**Comment by Alexofhiswalnut** [comment]
Merci c'est top. Bon courage à vous =)

**Comment by guillaumezin** [comment]
Bonjour, veuillez essayer la version 2 qui vient d'être publiée, et dites moi ici si vous trouvez les informations qui conviennent.

**Comment by Alexofhiswalnut** [comment]
J'ai mi à jour la version et j'ai cette erreur :

2020-08-25 18:23:00.142 Error: (LinkY) durant l'étape getdatahours de 2020-08-18 à 2020-08-25 - Pas de données disponibles, avez-vous associé un compteur à votre compte, activé la courbe de charge et demandé la collecte des données par heure sur le site d'Enedis ?

**Comment by guillaumezin** [comment]
Vous devez peut-être retourner sur le site d'Enedis pour demander la collecte des données par heure, j'ai dû le faire moi-même alors que je pensais déjà l'avoir fait, puis attendre une journée pour que le plugin fonctionne.

**Comment by Alexofhiswalnut** [comment]
D'accord je vais attendre alors merci

Le mar. 25 août 2020 à 19:49, Guillaume Zin <notifications@github.com> a
écrit :

**Comment by Alexofhiswalnut** [comment]
J'ai beau activer l'autorisation des nouveaux capteurs 5 mins . Rien ne se créer dans les devices...

**Comment by guillaumezin** [comment]
Toujours le même soucis ?

**Comment by Alexofhiswalnut** [comment]
Oui , mais mon compte ENEDIS à un problème donc rien à voir avec le plugin.

**Comment by guillaumezin** [comment]
Bonjour, il y a eu beaucoup d'améliorations sur le plugin, je vous encourage à mettre à jour, à baisser le paramètre "nombre de jours à récupérer pour les autres vues" à 7, je clos le ticket.
