### ISSUE TITLE
DomoticzEbusd

### ISSUE THREAD

**Issue by neiitzab** [guillaumezin/DomoticzLinky#243]
bonjour,
juste une remarque, j'ai l'impression qu'il y a une erreur dans le readme a cet endroit ou il est question de domoticzEbusd qui semble être un autre plugin que vous avez developpé :

"
If you don't see the plugin in the hardware configuration tab, give for everyone read permission to plugin and read and execute permission for directory, for Linux:

cd whatever/plugins
chmod ugo+rx DomoticzEbusd
chmod ugo+r DomoticzEbusd/plugin.py

"

Ou c'est moi qui n'est pas compris quelque chose?

**Comment by guillaumezin** [comment]
Ah oui, copié collé d'un autre plugin que j'ai écrit 😂

**Comment by neiitzab** [comment]
Ok! Ca me rassure. Je débute complètement sur domoticz, raspberry et debian, du coup j'ai galèrer à comprendre ou était l'erreur 😅
