### ISSUE TITLE
Installation sur Domotcz Version: 2024.7 

### ISSUE THREAD

**Issue by Fr8929** [guillaumezin/DomoticzLinky#245]
Bonjour,

Suite à un changement de DD de mon RPI PI3B+, j'ai donc tout réinstallé Debian Bullseye et domoticz Version: 2024.7
Build Hash: b317cfab1.
Je tente de faire afficher le plugin DomoticzLinky dans la configuration-- Matériel, mais il n'apparait pas dans le menu déroulant. 
J'ai pourtant suivi toutes les étapes de l'installation, redémarré, mais rien n'y fait, est ce que ma version Domoticz est compatible avec le plugin?
A vous lire.

**Comment by Tatroxitum** [comment]
Bonjour, avez vous bien installé une version de python 3 supérieure à 3.7 ?

**Comment by Tatroxitum** [comment]
Il faudrait vérifier dans setup-a propos de domoticz que cette version de
python est bien reconnue par domoticz.
Si c'est le cas, vérifiez les droits d'accès au répertoire domoticzLinky,
et au fichiers contenus dedans
(ls -all)

**Comment by Fr8929** [comment]
Après avoir installé PIP, maintenant il est visible dans le matériel de domoticz.
Il devait me manquer quelque chose dans Python3.
Merci pour les indications.
