### ISSUE TITLE
Linky production

### ISSUE THREAD

**Issue by tomaprice83** [guillaumezin/DomoticzLinky#25]
Bonjour,
Merci pour ce plugin qui fonctionne bien avec mon linky de consommation. Peut-on envisager de l'utiliser également pour faire remonter les informations provenant d'un linky de production (panneaux solaires) ? Si oui comment ?
Cdt.

**Comment by guillaumezin** [comment]
Ce n'est pas possible avec le plugin actuel, mais Enedis a ouvert de nouvelles interfaces de programmation qui me permettront de récupérer ces informations, mais qui demande une refonte du plugin. Soyez patient...

**Comment by tomaprice83** [comment]
Ok. Pas de soucis. Merci pour le retour. CdtLe 5 déc. 2019 19:27, Guillaume Zin <notifications@github.com> a écrit :Ce n'est pas possible avec le plugin actuel, mais Enedis a ouvert de nouvelles interfaces de programmation qui me permettront de récupérer ces informations, mais qui demande une refonte du plugin. Soyez patient...

**Comment by pjuhel2** [comment]
Bonjour et bonne année.
Depuis le 1er janvier, il n'y a plus de données. Les erreurs suivantes sont enregistrées: Error: (Linky) Données manquantes durant l'étape getdatahours de 28/12/2019 à 01/01/2020, Error: (Linky) Erreur à la réception de données JSON (code : erreur) durant l'étape getdatahours de 01/01/2020 à 05/01/2020. 
Est-il nécessaire de changer un paramètre pour l'année 2020?

**Comment by disquette38** [comment]
Bonjour et Bonne Année également,
J'ai effectivement les mêmes erreur depuis le début d'année ->03/01/2020, mais depuis ce matin cela me semble OK.
Les données sont bien présente dans domoticz.

**Comment by guillaumezin** [comment]
Bonne année !

J'ai moi aussi beaucoup d'erreurs ces derniers jours, Enedis doit migrer des choses.

Je travaille sur une nouvelle version du plugin qui s'appuie sur des interfaces de programmation officielles, ça devrait stabiliser les choses et permettre à terme d'afficher aussi les courbes de production d'énergie.

**Comment by guillaumezin** [comment]
Bonjour, j'ai publié le plugin version 2.0.0 qui prend en charge les compteurs de production, n'hésitez pas à mettre à jour et à tester, je ferme ce ticket.
