### ISSUE TITLE
Heures Creuse

### ISSUE THREAD

**Issue by thomasCompta** [guillaumezin/DomoticzLinky#26]
Bonjour,

serait-il possible d'ajouter les options des heures creuses pour avoir un tarif plus juste?

Merci.

**Comment by guillaumezin** [comment]
J'ai regardé, c'est possible, mais très complexe, car le plugin ne suffit pas, il faut modifier Domoticz même. Et Enedis ne donne pas les tarifs (car ils fournissent l'énergie mais ne la commercialisent pas), donc ce serait à vous d'entrer les tarifs dans les paramètres de Domoticz, et à modifier à chaque évolution tarifaire, rendant le tarifs des anciennes données caduques. Je garde l'idée sous le coude, mais je ne promets rien.

**Comment by guillaumezin** [comment]
J'ai un prototype qui fonctionne, mais ça suppose que ce patch soit intégré : https://github.com/domoticz/domoticz/pull/3877

**Comment by guillaumezin** [comment]
![image](https://user-images.githubusercontent.com/541581/74689381-33fb0d00-51db-11ea-98b8-1d1020683252.png)

![image](https://user-images.githubusercontent.com/541581/74689406-51c87200-51db-11ea-97c7-e1dc8e5b82aa.png)

**Comment by thomasCompta** [comment]
Bonjour et merci pour le proto.
Si je comprends bien je dois attendre qu'il soit intégré à domoticz c'est bien ça?

**Comment by guillaumezin** [comment]
C'est ça, le code est prêt, pour que ça fonctionne avec de vrais données, il me faut une autorisation d'Enedis, la demande est faite

**Comment by Dg-59** [comment]
Bonjour je suis intéressé aussi le patch sera inclus ou on devra l'installer nous même ?

**Comment by guillaumezin** [comment]
Ce sera directement supporté dans la version à venir.

**Comment by Dg-59** [comment]
Merci :+1:

**Comment by guillaumezin** [comment]
Bonjour, veuillez essayer la version 2 qui vient d'être publiée, elle prend en charge les heures creuses.

**Comment by Dg-59** [comment]
Voila j'ai fait la mise a jour pour les heures creuse je suis en 1h04-7h04  et 12h34-14h34

j'ai un peux de mal a comprendre "Vous pouvez choisir les plages horaires d'heures creuses, sous la forme "2h00-7h00 13h00-16h00" par exemple, laisser vide pour désactiver. Vous pouvez préciser des plages différentes pour chaque point de livraison, par exemple "12345678901234 1h00-6h00 12h00-14h00 88888888888888 13h00-16h00" "

**Comment by guillaumezin** [comment]
Je suis désolé, je ne me suis jamais senti très pédagogue...
