### ISSUE TITLE
[IMPROVEMENT] Ajouter la moyenne de la consommation de la veille sur le tableau de board

### ISSUE THREAD

**Issue by yah00078** [guillaumezin/DomoticzLinky#27]
Hello ! 
Tout d'abord merci pour ce plugin très pratique !

-> Je trouve qu'il pourrait être pratique de pouvoir afficher dans le tableau de bord la consommation horaire moyenne sur la journée précédente (La veille)

J'ai commencé a regarder le code, mais pas encore assez bien compris pour proposer du code !

Merci pour le travail ;-)

**Comment by guillaumezin** [comment]
Je prends bien note de votre suggestion, il y a de nouveaux modes déjà prévus dans la prochaine version du plugin, qui est un refonte, ne vous lancez pas maintenant à modifier un code qui va largement bouger dans les semaines qui viennent

**Comment by guillaumezin** [comment]
Pouvez-vous regarder ce que propose le plugin en version 2.0.0 ?

**Comment by guillaumezin** [comment]
Je ferme le ticket, c'est pris en compte dans les dernières version du plugin.

**Comment by yah00078** [comment]
Je viens de voir vos commentaires, j'essaye de ce pas. merci !
