### ISSUE TITLE
connexion site enedis

### ISSUE THREAD

**Issue by c4coer** [guillaumezin/DomoticzLinky#29]
bonjour, le site enedis a changer
l'url semble diffèrent sur le plug in, et le captcha bloque la connexion semble t il.
pouvez vous me dire si c'est le cas ?
j'ai modifié le plug in avec la nouvel adresse pour tester mais je suis bloqué par le captcha (erreur identifiant)
merci

**Comment by guillaumezin** [comment]
Effectivement, il y a maintenant un captcha. Le plugin en l'état ne peut plus fonctionner.

En parallèle, Enedis a eu l'intelligence de développer des API pour les programmeurs : https://datahub-enedis.fr

J'ai anticipé l'apparition des captcahs et je suis inscrit et reconnu comme développeur, j'ai un prototype qui commence à bien fonctionner : https://github.com/guillaumezin/DomoticzLinky/tree/datahub

N'installez pas encore cette version de plugin, elle ne fonctionne pour l'instant qu'avec des données factices. Pour avoir accès au véritables données, je dois signer un contrat avec Enedis mais en tant que particulier, je ne peux pas. Un autre développeur qui a une petite structure d'Entreprise est en train de m'aider à mettre en place la petite infrastructure nécessaire et est en signature.

Bref, c'est dans les cartons, c'est même bien avancé, reste la question contractuelle à finaliser pour avoir une nouvelle version de plugin fonctionnelle et pérenne.

**Comment by guillaumezin** [comment]
Par contre il faudra une version beta très récente de Domoticz, et cela obligera à mettre à niveau vers Debian/Raspbian Buster ceux qui sont sur cette plateforme.

**Comment by c4coer** [comment]
pas soucis j'utilise toujours la dernière bêta

Le mer. 4 mars 2020 à 11:16, Guillaume Zin <notifications@github.com> a
écrit :

**Comment by c4coer** [comment]
j'ai essayé ensuite cela renvoi sur un site ou il faut valider un code (celui-des log) , mais la valeur de compteur 110 Kw, ne correspond pas a mon compte comment se fait la relation avec mon compte  enedis ?

**Comment by guillaumezin** [comment]
Comme dit dans mon précédent message, ça ne fonctionne pour l'instant qu'avec des données factices, tant que les considérations contractuelles ne sont pas réglées avec Enedis

**Comment by c4coer** [comment]
ah ok j'avais compris.  comme quoi il faut tout lire :)

Le jeu. 5 mars 2020 à 20:37, Guillaume Zin <notifications@github.com> a
écrit :

**Comment by Philtass** [comment]
Ok, super que ce soit en cours.
Je suis bien en bêta domoticz et raspbian buster et je viens juste de rouvrir un compte Enedis. J'attends avec impatience la nouvelle version du plugin.
Cela dit, je suis également producteur grâce à mes panneaux solaires. Les données de production n'étaient pas dispo sur l'ancien site Enedis, mais maintenant ça à l'air de fonctionner. Pour l'instant les données de prod sont à zéro, mais j'ai bon espoir de les récupérer un jour (demande faite à Enedis ce jour, résultat attendu dans les 3 ans qui viennent si c'est comme d'hab avec eux). Et donc, ce serait top si on pouvait aussi les récupérer dans domoticz.
A dispo pour tester si besoin.

**Comment by guillaumezin** [comment]
C'est prévu et ça devrait fonctionner d'emblée avec la nouvelle version de plugin, pourvu que Domoticz soit à jour

**Comment by c4coer** [comment]
perso j'ai mis un compteur pour récupérer ma production du solaire

**Comment by davidmarli** [comment]
J'ai un soucis : j'ai copier la nouvelle version du plugin et je l'ai rendu exécutable.
Mais dans le matériel sous domoticz le plugin n'apparait pas dans la liste déroulante ...
J'ai redémarré domoticz, rien n'y fait ...

Comment lreinstaller le tout ?

Merci.

**Comment by guillaumezin** [comment]
Si vous parlez de la version "datahub", elle n'est pas encore utilisable, elle ne fonctionne qu'avec des données factices. Quand bien même, elle devrait au moins apparaître dans la liste.

La version "master" fonctionnait-elle avant ?

Quel OS (Linux, Windows) et plateforme (PC, Raspberry PI, Synology, etc.) utilisez-vous ?

Dans quel répertoire avez-vous placé plugin.py ?

Avez-vous bien installé Python 3 ?

**Comment by davidmarli** [comment]
alors, dans l'oredre.

C'est un domoticz qui est installé depuis un moment.
LE compteur linky a été installé fin juin, donc j'ai du m'interesser à votre plugin courant octobre (qd j'ai enfin eu la remontée datas sur enedis)
Bref, j'avais installé via ce qui est écrit sur le github (créer un repertoire domoticzLinky dans le rep plugins de domoticz, cloner le github ...

Ensuite j'avais pu sur la page domoticz sélectionner DomoticzLinky dans la matériel.

MAIS, depuis quelques temps la remontée de données ne fonctionnait plus, j'avais laissé tombe (pas le temps de chercher).
Puis j'ai voulu enlever le materiel correspondant à DomoticzLinky et depuis impossible de la faire afficher dans la liste déroulante : il a disparu.

J'ai tenté de reinstaller l'ancien plugin : RIEN
Le nouveau toujours RIEN !!!!

Pour python 3 aucune idée ... comment on fait ?

Merci en tout cas pour votre aide.

**Comment by guillaumezin** [comment]
Mettez une capture de Domoticz / Configuration / A propos

Votre plugin.py est dans plugins/domoticzlinky ou plugins/domoticzlinky/domoticzlinky ?

**Comment by davidmarli** [comment]
oh punaise : 

Version: 4.11777
Build Hash: 2948df585
Compile Date: 2020-03-06 07:26:49
dzVents Version: 3.0.1
Python Version: **None**

comment c'est possible ? J'ai quelques scripts python sur le raspberry qui fonctionnent !

plugin.py est dans Domoticz/DomoticzLinky.

Merci

**Comment by guillaumezin** [comment]
Vous ne pouvez pas lancer le script comme vous le faites, c'est normal.

J'en déduis que Python 3 est installé. Si c'est bien le cas, ça voudrait dire que vous avez installé une version de Domoticz compilée sans support de Python, est-ce possible ?

Une prochaine fois, créer un ticket à part...

**Comment by davidmarli** [comment]
bon j'arrête l'incruste ...
Je suis en beta, et les nouvelles versions plantent si pas buster.*
Donc j'ai essayé de passer de stech à buster, ça a du merdouiller ...

Je vais refaire une installation propre ...

on verra.

Est-il possible d'avoir une date pour le nouveau plugin ?

Merci.

**Comment by guillaumezin** [comment]
Non, pas de date, de mon côté tout est prêt, j'attends l'autorisation d'Enedis

**Comment by davidmarli** [comment]
Bon ben bizarre.

Je viens d'installer une raspbian buster toute neuve.
Domoticz idem dernière beta, toujour python : none
L'ancien plugin ne fait toujours rien apparaitre dans la boite de dialogue du materiel sous domoticz !!!

**Comment by guillaumezin** [comment]
Je suis passé sous Buster il y a 15 jours, je viens de mettre à jour Domoticz (beta) 4.11786 et ça fonctionne

```
À propos de Domoticz
Version: 4.11786
Build Hash: 16cbfa328
Compile Date: 2020-03-14 19:27:12
dzVents Version: 3.0.1
Python Version: 3.7.3 (default, Dec 20 2019, 18:57:59) [GCC 8.3.0]
```

```
python3 --version
Python 3.7.3
```

**Comment by davidmarli** [comment]
Ben je n'y comprend rien !!!

Déjà comment savoir quelle version de python est installée ?

Et surtout pourquoi cela n'apparait pas dans domoticz ???

**Comment by lvdtime** [comment]
Bonjour et merci pour ce très bon plugin pour Domoticz

Je suis arrivé un peu au mauvais moment pour l'utiliser puisque je pense que le nouveau site d'Enedis est en place et donc je ne récupère pas tout ce que je veux avec le branch master.

Je me suis dis que j'allais installer la branch "datahub" en attendant que vous ayez les accords pour utiliser les API Enedis.

J'ai donc supprimé les répertoires liés à l'ancien plugin et recréé le répertoire plugins/DomoticzLinky puis copié plugin.py dans ce répertoire, j'ai ensuite lancé la commande chmod ugo+x plugin.py et pour finir j'ai relancé Domoticz.

J'ai ensuite voulu faire l'ajout dans le matériel mais Linky n'apparaît plus dans la liste.

J'ai donc regardé les logs et je tombe sur cette erreur et je ne sais pas trop quoi en faire : 
`Error: PluginList: Parsing '/home/domoticz/domoticz/plugins/DomoticzLinky/', 'Error document empty.' at line 0 column 0 in XML ''.`

Concernant le Domoticz installé voici les informations trouvées dans "Configuration/A propos"

> À propos de Domoticz
> Version: 4.11799
> Build Hash: 87bfd914d
> Compile Date: 2020-03-19 16:39:50
> dzVents Version: 3.0.1
> Python Version: 3.7.3 (default, Dec 20 2019, 18:57:59) [GCC 8.3.0]

Je continue mes recherches et je suis preneur de bonnes idées.

Bonne journée

**Comment by davidmarli** [comment]
Bonjour,

pour moi un redémarrage du Pi a tout remis en ordre ...

**Comment by lvdtime** [comment]
1er essai de reboot sans succès :(

**Comment by guillaumezin** [comment]
La version datahub ne vous renverra au mieux que des données factices pour l'instant, j'attends l'autorisation d'Enedis pour passer sur de vrais données, et avec le confinement dû au Covid-19, je pense qu'ils ont d'autres priorités.

Quand bien même, le problème que vous rencontrez est anormal et je n'arrive pas à le reproduire. Avez-vous essayer d'effacer l'entrée Linky, redémarrer à l'ajouter à nouveau ?

**Comment by lvdtime** [comment]
J'ai lu vos post et en effet j'ai vu que ça ne servirait à rien, mais vu que je n'arrive pas à avoir les relevés horaires avec l'ancien plug'in je me suis dit que j'allais préparer mon installation pour le nouveau et ça marchera quand ce sera actif.

Je teste en repartant de zéro et je vous donne un nouveau statut

Merci

**Comment by lvdtime** [comment]
Bonjour à tous,
Je pars du principe que la copie se passait mal et que le fichier était donc erroné (je passait par un wget).
J'ai fais un copier-coller basique et ça semble bon.
Désolé pour le dérangement
Bonne journée et bon courage avec Enedis

**Comment by 33ced** [comment]
bonjour,

ci-joint mon log après que le relevé ait bien été activé sur ENEDIS.
J'ai l'impression que je ne peux pas me loger à ENEDIS, qu'en pensez vous? merci

Je suis en version domoticz :
Version: 2020.1
Build Hash: 63fa969e4
Compile Date: 2020-03-22 15:16:16
dzVents Version: 3.0.1
Python Version: 3.7.3 (default, Dec 20 2019, 18:57:59) [GCC 8.3.0]

et le plugin 1.2.3,
voici 2 logs, pas a la meme heure

2020-03-27 16:08:23.629 (Compteur) Ce plugin est compatible avec Domoticz version 3.9517 et plus récent, mais la vue par heure peut ne pas fonctionner avec la version 4.9700
2020-03-27 16:08:23.630 (Compteur) Adresse e-mail mise à **adresse OK**
2020-03-27 16:08:23.630 (Compteur) Mot de passe entré
2020-03-27 16:08:23.630 (Compteur) Consommation à montrer sur le tableau de bord mis à day
2020-03-27 16:08:23.630 (Compteur) Accepter automatiquement les conditions d'utilisation mis à True
2020-03-27 16:08:23.631 (Compteur) Nombre de jours à récupérer pour la vue par heures mis à 7
2020-03-27 16:08:23.631 (Compteur) Nombre de jours à récupérer pour les autres vues mis à 366
2020-03-27 16:08:23.631 (Compteur) Debug mis à 1
2020-03-27 16:08:23.631 (Compteur) Si vous ne voyez pas assez de données dans la vue par heures, augmentez le paramètre Log des capteurs qui se trouve dans Réglages / Paramètres / Historique des logs
2020-03-27 16:08:23.614 Status: (Compteur) Initialized version 1.2.3, author 'Barberousse'
2020-03-27 16:08:23.622 Status: (Compteur) Entering work loop.
2020-03-27 16:08:33.660 (Compteur) Récupération des données...
2020-03-27 16:08:33.661 (Compteur) Connect
2020-03-27 16:08:33.989 (Compteur) Dict details (2):
2020-03-27 16:08:33.989 (Compteur) --->'Status':'302'
2020-03-27 16:08:33.989 (Compteur) --->'Headers (13):
2020-03-27 16:08:33.990 (Compteur) ------->'Date':'Fri, 27 Mar 2020 15:08:33 GMT'
2020-03-27 16:08:33.990 (Compteur) ------->'Server':'Apache'
2020-03-27 16:08:33.990 (Compteur) ------->'Set-

Cookie':'['AMAuthCookie=xBChZFU78a2CSYsn5Kyk9VlhxXy9_cjV_9Rbf-A7vVEhXdGtbapeyl2IjYm1y6NEhU0VRB_Jqj0TpQqGuFaJ2w..*AAJTSQACMDIAAlNLABMyOTY1NjExNzI0ODY5NDc4OTU2AAJTMQACMDQ.*; Domain=.enedis.fr; Path=/', 'AMAuthCookie=xBChZFU78a2CSYsn5Kyk9VlhxXy9_cjV_9Rbf-A7vVEhXdGtbapeyl2IjYm1y6NEhU0VRB_Jqj0TpQqGuFaJ2w..*AAJTSQACMDIAAlNLABMyOTY1NjExNzI0ODY5NDc4OTU2AAJTMQACMDQ.*; Domain=.erdf.fr; Path=/', 'amlbcookie=04; Domain=.enedis.fr; Path=/', 'amlbcookie=04; Domain=.erdf.fr; Path=/', 'AMAuthCookie=LOGOUT; Domain=.enedis.fr; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Path=/', 'AMAuthCookie=LOGOUT; Domain=.erdf.fr; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Path=/', 'JSESSIONID=6C1FE27D4BDE597840E0574F64F62690; Path=/auth/; HttpOnly', 'amlbcookie=LOGOUT; Domain=.enedis.fr; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Path=/', 'amlbcookie=LOGOUT; Domain=.erdf.fr; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Path=/', 'iPlanetDirectoryPro=LOGOUT; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Path=/']'
2020-03-27 15:54:21.624 (Compteur) ------->'X-Frame-Options':'SAMEORIGIN'
2020-03-27 15:54:21.625 (Compteur) ------->'Cache-Control':'private'
2020-03-27 15:54:21.625 (Compteur) ------->'Pragma':'no-cache'
2020-03-27 15:54:21.625 (Compteur) ------->'AM_CLIENT_TYPE':'genericHTML'
2020-03-27 15:54:21.625 (Compteur) ------->'X-AuthErrorCode':'-1'
2020-03-27 15:54:21.626 (Compteur) ------->'Location':'https://espace-client-connexion.enedis.fr/messages/information.html'
2020-03-27 15:54:21.626 (Compteur) ------->'Allow':'POST, GET'
2020-03-27 15:54:21.627 (Compteur) ------->'Vary':'Accept-Encoding'
2020-03-27 15:54:21.627 (Compteur) ------->'Content-Length':'0'
2020-03-27 15:54:21.627 (Compteur) ------->'Content-Type':'text/html;charset=UTF-8'
2020-03-27 15:54:38.216 (Compteur) Dict details (3):
2020-03-27 15:54:38.216 (Compteur) --->'Status':'403'
2020-03-27 15:54:38.216 (Compteur) --->'Headers (5):
2020-03-27 15:54:38.216 (Compteur) ------->'Date':'Fri, 27 Mar 2020 14:54:21 GMT'
2020-03-27 15:54:38.217 (Compteur) ------->'Strict-Transport-Security':'max-age=16070400; includeSubDomains'
2020-03-27 15:54:38.217 (Compteur) ------->'Vary':'Accept-Encoding'
2020-03-27 15:54:38.217 (Compteur) ------->'Content-Type':'text/html'
2020-03-27 15:54:38.218 (Compteur) ------->'Content-Length':'117'
2020-03-27 15:54:38.218 (Compteur) --->'Data':'b"<html>\n <head>\n <title>Erreur</title>\n </head>\n <body>\n <h1>Votre requete n'a pas pu aboutir.</h1>\n </body>\n</html>"'
2020-03-27 15:54:54.720 (Compteur) Dict details (3):
2020-03-27 15:54:54.721 (Compteur) --->'Status':'403'
2020-03-27 15:54:54.721 (Compteur) --->'Headers (5):
2020-03-27 15:54:54.721 (Compteur) ------->'Date':'Fri, 27 Mar 2020 14:54:38 GMT'
2020-03-27 15:54:54.722 (Compteur) ------->'Strict-Transport-Security':'max-age=16070400; includeSubDomains'
2020-03-27 15:54:54.722 (Compteur) ------->'Vary':'Accept-Encoding'
2020-03-27 15:54:54.723 (Compteur) ------->'Content-Type':'text/html'
2020-03-27 15:54:54.723 (Compteur) ------->'Content-Length':'117'
2020-03-27 15:54:54.723 (Compteur) --->'Data':'b"<html>\n <head>\n <title>Erreur</title>\n </head>\n <body>\n <h1>Votre requete n'a pas pu aboutir.</h1>\n </body>\n</html>"'
2020-03-27 15:55:11.177 (Compteur) Dict details (3):
2020-03-27 15:55:11.177 (Compteur) --->'Status':'403'
2020-03-27 15:55:11.178 (Compteur) --->'Headers (5):
2020-03-27 15:55:11.178 (Compteur) ------->'Date':'Fri, 27 Mar 2020 14:54:54 GMT'
2020-03-27 15:55:11.179 (Compteur) ------->'Strict-Transport-Security':'max-age=16070400; includeSubDomains'
2020-03-27 15:55:11.179 (Compteur) ------->'Vary':'Accept-Encoding'
2020-03-27 15:55:11.179 (Compteur) ------->'Content-Type':'text/html'
2020-03-27 15:55:11.180 (Compteur) ------->'Content-Length':'117'
2020-03-27 15:55:11.180 (Compteur) --->'Data':'b"<html>\n <head>\n <title>Erreur</title>\n </head>\n <body>\n <h1>Votre requete n'a pas pu aboutir.</h1>\n </body>\n</html>"'
2020-03-27 15:55:11.183 Error: (Compteur) Les données reçues ne sont pas du JSON : Expecting value: line 1 column 1 (char 0) durant l'étape getdatadays de 26/02/2020 à 26/03/2020

**Comment by 4cc3ssD3ni3d** [comment]
Hello !
J'ai le même problème que @33ced !
=> un 403 quand il essaye de taper sur l'url https://espace-client-connexion.enedis.fr/messages/information.html ...
Et par conséquent, aucune infos remontées dans Domoticz ...

**Comment by 33ced** [comment]
> Hello !
> J'ai le même problème que @33ced !
> => un 403 quand il essaye de taper sur l'url https://espace-client-connexion.enedis.fr/messages/information.html ...
> Et par conséquent, aucune infos remontées dans Domoticz ...

Regardes une réponse dans la page https://github.com/guillaumezin/DomoticzLinky/issues/33

**Comment by SimonMellerin** [comment]
Salut @guillaumezin ,

Je développe aussi une application qui "crawlait" l'ancien site d'enedis comme ton module.

L'appli que je développe ([aeneria](https://gitlab.com/aeneria/aeneria-app/)) à pour but d'être auto-hébergée (avec [yunohost](https://yunohost.org/#/) notamment)

La question que je me pose est la suivante : tu vas obtenir une clé d'API de la part d'Enedis basé sur un contrat, mais du coup, tu vas 'hardcoder' cette clé dans le code de ton module ? Ou bien chaque utilisateur devra obtenir sa propre clé ?

**Comment by guillaumezin** [comment]
> Salut @guillaumezin ,
> 
> Je développe aussi une application qui "crawlait" l'ancien site d'enedis comme ton module.
> 
> L'appli que je développe ([aeneria](https://gitlab.com/aeneria/aeneria-app/)) à pour but d'être auto-hébergée (avec [yunohost](https://yunohost.org/#/) notamment)
> 
> La question que je me pose est la suivante : tu vas obtenir une clé d'API de la part d'Enedis basé sur un contrat, mais du coup, tu vas 'hardcoder' cette clé dans le code de ton module ? Ou bien chaque utilisateur devra obtenir sa propre clé ?

Je vais (faire) héberger un site web intermédiaire : https://github.com/guillaumezin/Device-Flow-Proxy-Server. La clé sera utilisée entre le site et Enedis, et pas vue par le plugin, car je n'ai contractuellement pas le droit de faire apparaître la clé dans le code, surtout en open source. Le plugin va passer par ce site pour l'obtention du jeton de consentement.

**Comment by SimonMellerin** [comment]
Merci pour ta réponse, je comprends mieux !

Effectivement avoir un serveur 'passe-plat' c'est une bonne idée, je vais peut-être te copier ;)

**Comment by guillaumezin** [comment]
Attention, pour qu'Enedis donne une clé privée, il faut avoir une structure d'entreprise, c'est pour ça que j'ai demandé à quelqu'un d'héberger le site, je n'ai pas de structure d'entreprise personnelle et mon employeur ne peut pas signer pour moi.

**Comment by guillaumezin** [comment]
Par ailleurs, le site web que je propose marche bien avec l'offre gratuite de https://www.alwaysdata.com

**Comment by chatainsim** [comment]
Bonjour, avez-vous du nouveau d'Enedis ? Ou c'est toujours en attente chez eux ?

**Comment by guillaumezin** [comment]
Nous avons reçu la clef privé, nous faisons des essais, le site d'Enedis part en erreur 500, je crais que le problème ne soit chez eux...

**Comment by guillaumezin** [comment]
Bonjour, j'ai publié le plugin version 2.0.0, n'hésitez pas à mettre à jour et à tester, je ferme ce ticket.
