### ISSUE TITLE
Not working anymore?

### ISSUE THREAD

**Issue by Miloune** [guillaumezin/DomoticzLinky#3]
Hi,

I want to use this plugin, but i never had it to work.

I successfully connect to Enedis on Chrome, but the plugin can't fetch data:

Here my logs:

> 2018-08-31 20:37:11.123 Error: (Linky) Didn't received data during step getdatadays from 04/03/2018 to 02/04/2018
> 2018-08-31 20:37:11.525 Error: (Linky) Didn't received data during step getdatadays from 02/02/2018 to 03/03/2018
> 2018-08-31 20:37:11.826 Error: (Linky) Didn't received data during step getdatadays from 03/01/2018 to 01/02/2018
> 2018-08-31 20:37:12.128 Error: (Linky) Didn't received data during step getdatadays from 04/12/2017 to 02/01/2018
> 2018-08-31 20:37:12.429 Error: (Linky) Didn't received data during step getdatadays from 04/11/2017 to 03/12/2017
> 2018-08-31 20:37:12.730 Error: (Linky) Didn't received data during step getdatadays from 05/10/2017 to 03/11/2017
> 2018-08-31 20:37:13.132 Error: (Linky) Didn't received data during step getdatadays from 05/09/2017 to 04/10/2017
> 2018-08-31 20:37:13.433 Error: (Linky) Didn't received data during step getdatadays from 06/08/2017 to 04/09/2017
> 2018-08-31 20:37:13.734 Error: (Linky) Didn't received data during step getdatadays from 02/08/2017 to 05/08/2017
>

**Comment by guillaumezin** [comment]
Hi,

Do you get data on Enedis website: https://espace-client-particuliers.enedis.fr/group/espace-particuliers/suivi-de-consommation ?

Can you enable debug and post log?

**Comment by Miloune** [comment]
Hello,
I got this message, maybe it explain a lot: "Votre relevé est désormais effectué sans vous déranger. Votre consommation sera prochainement accessible sur votre compte."

**Comment by guillaumezin** [comment]
Since when did you get Linky? It seems that the service is not yet fully available, wait 15 days / one month and it should work.

**Comment by Miloune** [comment]
I don't know, maybe one month. But it's since i got Linky or since i activated my Enedis account?

**Comment by guillaumezin** [comment]
I got data about 1 month after Linky installation, it should come shortly

**Comment by guillaumezin** [comment]
Hi @Miloune do you get data now?

**Comment by Miloune** [comment]
Hi @guillaumezin, still no data... Enedis website seem to be down too at this moment.

**Comment by Miloune** [comment]
Hi @guillaumezin, I now get my data :) But not for "Usage last 24 hours" it's normal?

**Comment by guillaumezin** [comment]
Do you see hours view on Enedis website ? You might have to enable something specific to get hours data, because it is considered as private date.

Short log view may fail too on version 4.9700 because of a regression on Domoticz introduced just before the release, you may try the beta version.

**Comment by Miloune** [comment]
Ok, did i you said, activated on Enedis website and upgraded to the latest beta version. I think i have to wait fews days before having my data.
I think we can close this issue since i already have some data. Thank you :)

**Comment by guillaumezin** [comment]
OK, feel free to reopen if it's still not working,. I updated the Readme to give more hints on the problems you encountered.
