### ISSUE TITLE
Compte Enedis avec plusieurs compteurs enregistrés.

### ISSUE THREAD

**Issue by yoFra** [guillaumezin/DomoticzLinky#30]
Merci guillaumezin pour ce plugins que je viens de tester.
J'y récupère avec succès les infos d'un premier compteur.
Mais j'en dispose d'un second enregistré sur le site d'Enedis.
Comment faire pour en récupérer les infos de celui-ci ?
       .YO.

  * Domoticz v2020.1
  * Raspbian 10 (buster)
  * Raspberry Pi 2 Model B Rev 1.1

**Comment by guillaumezin** [comment]
Bonjour,

C'est prévu dans la future version 2 du plugin, le plugin est presque prêt, j'attends une autorisation d'Enedis pour le rendre officiel (pour l'instant cette nouvelle version ne fonctionne qu'avec des données factices).

**Comment by yoFra** [comment]
OK. Merci de ta réponse.
J'attends donc la V2.
Bonne continuation.      .YO.
