### ISSUE TITLE
Suggestion : ajouter la puissance atteinte max par jour

### ISSUE THREAD

**Issue by FFF3347** [guillaumezin/DomoticzLinky#37]
Bonjour, 

Heureux utilisateur du plugin, je souhaiterais savoir SVP s'il est prévu d'ajouter la Pmax journalière. 
Elle est bien disponible dans les restitutions ENEDIS (et coté fournisseur également). 
Elle pourrait être particulièrement utile dans un futur plus ou moins proche afin de connaitre la marge de puissance que nous avons pour l'ajout d'un consommateur tel qu'une borne de recharge pour véhicule électrique (7kW, 32A pour les modele les plus commun). 
Par rapport à notre abonnement, nous pourrions voir les moments de la journée où cette ajout de charge ne passe pas, et privilégier ainsi les horaires avec le moins de contraintes.

Merci par avance.

**Comment by guillaumezin** [comment]
C'est prévu et déjà à l'essai dans la version 2, qui sortira quand Enedis me donnera leur autorisation d'utiliser leur nouvelle API, mais tout a été ralenti à cause de COVID-19

**Comment by FFF3347** [comment]
Je comprens, pas simple...

A ENEDIS, j'y travaille depuis 17 ans, et je bosse en ce moment avec des stagiaires/apprentis sur des applis et portails (ce n'est pas moi qui développe), mais pas lié au domaine LINKY. 
Si vous avez un nom de contact afin que je fluidifie votre demande, n'hésitez pas :)

**Comment by guillaumezin** [comment]
Votre collègue répond régulièrement aux messages du forum de support sur https://datahub-enedis.fr si vous voulez son nom, mais il a clairement écrit que la pandémie avait tout ralenti, et je ne fais aucun reproche, c'est juste un constat.

**Comment by guillaumezin** [comment]
Bonjour, j'ai ajouté ça au plugin version 2, pouvez-vous tester et me dire si ça fonctionne pour vous ?

**Comment by FFF3347** [comment]
Bonjour, 

Alors oui, ça fonctionne, mais uniquement sur les X derniers jours (premier affichage).
J'espérais, pour mon usage, retrouver la Pmax journalière/mensuelle/annuelle par exemple dans les rapports (et/ou les graphiques) afin de simuler/contrôler facilement l'ajout de charge que pourrait engendre les bornes de recharge individuelle (translation +7kVA dans Excel, ou pourquoi pas directement dans le plugin :) ).

A moins qu'il y ait une fonction pour l'ajouter ? 
Je ne l'ai pas trouvé...

Bref, déjà satisfait ;)

**Comment by guillaumezin** [comment]
Bonjour, modifier la gestion des rapports Domoticz représente trop de travail, je considère le point comme clos puisque le plugin peut déjà afficher la conso veille/semaine/mois.
