### ISSUE TITLE
Plugin qui n'apparait pas dans domoticz 2020.2

### ISSUE THREAD

**Issue by darrepac** [guillaumezin/DomoticzLinky#38]
Salut

Je viens d'installer le plugin sur la version 2020.2 sur un Raspi 2b / Buster, mes autres plugins marchent nickel mais linky n'apparait pas. Rien dans le log non plus, pourtant le plugin semble au bon endroit
![image](https://user-images.githubusercontent.com/7128994/80811031-5f2fae80-8bc5-11ea-8930-02e42e483956.png)

**Comment by guillaumezin** [comment]
Les droits sur le répertoires sont-ils corrects ? Faites

`ls -al`

**Comment by darrepac** [comment]
En effet, j'ai pas checké:
![image](https://user-images.githubusercontent.com/7128994/80812896-2eea0f00-8bc9-11ea-9531-8b9452e6f8ac.png)
Mais tous mes plugins semblent logés à la même enseigne
![image](https://user-images.githubusercontent.com/7128994/80812927-42957580-8bc9-11ea-9841-340e46a0671b.png)

**Comment by lvdtime** [comment]
Hello
J'ai eu le même problème, le téléchargement dysfonctionne et j'ai donc créé le fichier en faisant un copier-coller du code.
Le plugin chez moi fait 74521 octets
![image](https://user-images.githubusercontent.com/62449538/80813813-06fbab00-8bcb-11ea-993e-b40b957f7dc3.png)

**Comment by guillaumezin** [comment]
Le plugin version 1.2.4 doit bien faire 39187 octets, c'est le cas chez moi

**Comment by guillaumezin** [comment]
Les droits sur le répertoire semblent ok

**Comment by lvdtime** [comment]
Sorry
Je pensais que c'était le nouveau

**Comment by guillaumezin** [comment]
Vous n'avez pas de messages d'erreur particulier si vous relancez Domoticz ?

**Comment by darrepac** [comment]
non rien...ni d'erreur ni rien, zarb

**Comment by guillaumezin** [comment]
Que donne "python3 --version" ?

**Comment by darrepac** [comment]
3.7.3

**Comment by guillaumezin** [comment]
Pouvez-vous essayer de suivre ce qui est indiqué dans https://www.domoticz.com/wiki/Using_Python_plugins#Troubleshooting ?

**Comment by weos44** [comment]
Bonjour,

Je viens de me lancer en domotique avec domoticz
J 'ai un souci moi aussi avec le plugin et Domoticz 2020.2.
Je suis sous un raspberry avec raspbian et domoticz 2020.2
Mon installation est à jour.
![image](https://user-images.githubusercontent.com/64697968/80868520-848eec00-8c9b-11ea-80c7-158049d319aa.png)

Normalement la derniere version de python est installé
![image](https://user-images.githubusercontent.com/64697968/80868502-54dfe400-8c9b-11ea-8cd5-57d71f7f592e.png)

J' ai bien donné les permissions avec chmod.

Mais je n ai aucun retour sous domoticz
![image](https://user-images.githubusercontent.com/64697968/80868760-d421e780-8c9c-11ea-9945-2a2fef9e2fff.png)
![image](https://user-images.githubusercontent.com/64697968/80868787-f9aef100-8c9c-11ea-97ed-05c5ed046570.png)

![image](https://user-images.githubusercontent.com/64697968/80868809-0a5f6700-8c9d-11ea-9f28-0208a2e18227.png)

J'ai bien creer mon acces chez enedis et mis mon mot de passe + email  sous domoticz
Je ne suis pas un crack en linux, j'ai donc suivi point par point les installations, mais peut être ai je omis quelque chose.

merci beaucoup de votre aide.

**Comment by guillaumezin** [comment]
Pourriez-vous vérifier le contenu de plugin.py ? Par exemple, ligne 30, lisez-vous "Journée dernière" ou un truc bizarre genre "Journée derniA©re" ?

**Comment by guillaumezin** [comment]
Et dans Paramètres / Autre, vérifiez que "Événements (Lua/Blockly/Scripts)" est activé.

**Comment by guillaumezin** [comment]
@weos44 votre problème est différent, vous devez attendre la version 2 du plugin, surveillez les autres tickets ouverts, par exemple #33

**Comment by darrepac** [comment]
> Pourriez-vous vérifier le contenu de plugin.py ? Par exemple, ligne 30, lisez-vous "Journée dernière" ou un truc bizarre genre "JournA©e derniA©re" ?

Oui ca marche bien, pas de pb d'encodage.
ET les plugins sont bien activés.
De toute facon si il faut attendre une version 2, pas d'urgence...sachant que j'ai déjà la téléinfo sur domoticz. C'était plus pour le fun de rajouter ce plugin

**Comment by weos44** [comment]
@guillaumezin  ok merci de votre retour, j attend donc le version 2. bonne journée

**Comment by Zener06** [comment]
Bonjour,
J'ai la même configuration,et le même soucis que @darrepac , et les pistes d'investigations proposées donnent les même résultats. Je suis disponible pour toute investigation complémentaire.

**Comment by guillaumezin** [comment]
Bonjour,
J'ai mis à jour le plugin en beta sur https://github.com/guillaumezin/DomoticzLinky/tree/datahub et il doit fonctionner avec les données réelles maintenant. Je dis il doit car pour l'instant mon compte Enedis ne fait pas apparaître mon compteur, donc je n'ai pas pu vérifier, mais si certains veulent, à leurs risques et périls, faire un essai, ils peuvent me faire un retour ici. Attention, si vous utilisez la commande git, faites "git checkout datahub" avant la commande "git pull" décrite dans le readme.

**Comment by guillaumezin** [comment]
Bonjour, j'ai publié le plugin version 2.0.0 qui change beaucoup de choses et doit corriger nombre de problèmes, n'hésitez pas à mettre à jour et à tester, je ferme ce ticket.
