### ISSUE TITLE
A little problem with hours log

### ISSUE THREAD

**Issue by Linurael** [guillaumezin/DomoticzLinky#4]
Hello ,

everything works fine except displaying data by hours.
I looked on the site of ENEDIS to check the presence of the data and on the site I have access to the display of the data correctly.

Is there a parameter to put in place or an additional procedure for this display mode?

Thanks a lot for this plugins.

**Comment by guillaumezin** [comment]
Hello,

What is your Domoticz version? Hours view can't work with version 4.9700.

Can you enable debug and post the log?

**Comment by Linurael** [comment]
Thanks for answer, i have 4.9700 version.
Now i known why it don't work. 

When i come back to home i try to enable debug and post it

**Comment by Linurael** [comment]
You want resultat appear in "system/log" ? or something special ?

**Comment by guillaumezin** [comment]
No need for your debug log, if you want hours data, you must upgrade Domoticz to a more recent version. I'm sorry, I made a lot of patches to make the Linky plugin possible with Domoticz, and a few days before the stable release, one of the patch has been broken, it didn't let me the time to see the regression.

PS : don't be sorry to be french, I am too ;-)

**Comment by guillaumezin** [comment]
I don't think it is a good idea to go to oldest version, but don't forget to backup your database BEFORE upgrading to beta, and keep your backup for a while before deciding to stay with the beta version, domoticz tends to break often between versions...

**Comment by QuentinMorel** [comment]
Thanks for everything, it works perfectly now !

**Comment by guillaumezin** [comment]
I re-submit patches to Domoticz dev team a few days after 4.9700 release to fix hours view, I guess v4.9701 is too close to version 4.9700 (there are new versions every day) and contains the bug too.

**Comment by ooii** [comment]
Thanks. I'll check later.

I think we can switch to french on this repo :)

**Comment by guillaumezin** [comment]
Oui, mais comme le fil avait été commencé en anglais...

**Comment by ooii** [comment]
On vient de le passer en français...
