### ISSUE TITLE
Heures pleines / Heures creuses 

### ISSUE THREAD

**Issue by brandicourtgb** [guillaumezin/DomoticzLinky#40]
Boujour,
est-il possible d'afficher les consos Heures pleines / Heures creuses ?

**Comment by guillaumezin** [comment]
C'est prévu dans la prochaine version qui sera disponible je l'espère sous peu, cf. #26

**Comment by brandicourtgb** [comment]
Merci !
 
 
 
 
> Message du 11/05/20 12:16> De : "Guillaume Zin" > A : "guillaumezin/DomoticzLinky" > Copie à : "brandicourtgb" , "Author" > Objet : Re: [guillaumezin/DomoticzLinky] Heures pleines / Heures creuses  (#40)> >
>
> C'est prévu dans la prochaine version qui sera disponible je l'espère sous peu, cf. #26
—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[ { "@context": "http://schema.org", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "https://github.com/guillaumezin/DomoticzLinky/issues/40#issuecomment-626611701", "url": "https://github.com/guillaumezin/DomoticzLinky/issues/40#issuecomment-626611701", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "https://github.com" } } ]

**Comment by guillaumezin** [comment]
Bonjour, j'ai publié le plugin version 2.0.0 qui prend en charge les heures creuses, n'hésitez pas à mettre à jour et à tester, je ferme ce ticket.
