### ISSUE TITLE
Plugin non reconnu dans domoticz

### ISSUE THREAD

**Issue by Manu4810** [guillaumezin/DomoticzLinky#41]
Bonjour,
J'essaye d'installer le plugin Linky sur Domoticz pour la 1ère fois. Le matériel n'apparaît pas dans la liste et le plugin ne semble pas actif.
Je suis allé voir dans le log domoticz, et j'ai trouvé le message suivant:
 **_2020-05-24 00:02:16.499 Status: New sensors allowed for 5 minutes...
2020-05-24 00:02:21.618 Error: PluginList: Parsing '/usr/local/domoticz/var/plugins/DomoticzLinky/', 'Error document empty.' at line 0 column 0 in XML ''._** 
Domoticz tourne sur un NAS synology avec le module python 3:
**_2020-05-23 23:57:54.128 Status: Domoticz V2020.1 (c)2012-1970 GizMoCuz
2020-05-23 23:57:54.128 Status: Build Hash: 0, Date: 1970-01-01 01:00:00
2020-05-23 23:57:54.128 Status: Startup Path: /usr/local/domoticz/
2020-05-23 23:57:54.380 Status: PluginSystem: Started, Python version '3.5.1'._** 
La suite domoticz a été installée à partir du gestionnaire  de paquets, et se trouve à l'adresse /volume1/@appstore/domoticz. Le répertoire des plugin se trouve sous ~domoticz/var/plugins.
J'ai créé moi-même le répertoire DomoticzLinky dans le répertoire plugin et y ai collé le plugin python avec droit en exécution et lecture:
**_xxxxxx:/volume1/@appstore/domoticz/var/plugins/DomoticzLinky$ ll
total 360
drwxr-xr-x 1 root root     18 May 23 23:55 .
drwxr-xr-x 1 1000 1000     56 May 23 23:54 ..
-rwxr-xr-x 1 root root 365110 May 23 23:55 plugin.py_**
J'ai dû louper une étape, ou bien ma configuration n'est pas conforme à l'attendu ?

**Comment by guillaumezin** [comment]
2 pistes : est-ce normal que ça parle un coup de  /usr/local/domoticz/var/plugins/DomoticzLinky et un coup de /volume1/@appstore/domoticz/var/plugins/DomoticzLinky ? C'est le même répertoire avec un lien ?
Pouvez-vous regarder avec un éditeur de texte, en forçant l'encodage UTF-8, le contenu du plugin.py ? Si vous y voyez des accents en bon français, c'est bon, si vous y voyez des choses genre A© c'est qu'on rencontre un problème d'encodage

**Comment by Manu4810** [comment]
Oui, a priori, il y a un lien, car après m'être connecté au NAS en ssh, je peux accéder au plugin soit via /usr/local/domoticz/var/plugins/DomoticzLinky..., soit via /volume1/@appstore/domoticz/var/plugins/DomoticzLinky... Cela est d'ailleurs confimé par le log "2020-05-23 23:57:54.128 Status: Startup Path: /usr/local/domoticz/"
Et pour les accents, j'en vois un peu partout dans le fichier plugin.py.
Je n'ai pas utilisé la commande git car j'ai compris que c'était équivalent à copier le  plugin directement au bon endroit. Erreur ?

**Comment by guillaumezin** [comment]
Que ce soit la commande git ou une copie, ce devrait être pareil. Après, je me méfie, si vous téléchargez par exemple le fichier avec Windows et que vous le copier sur le NAS, l'encodage des caractères accentués est parfois différent entre les deux systèmes. Comme je vois que vous pouvez vous connecter en SSH, pouvez-vous vérifier que les accents sont bien formattés, y compris avec la commande "cat /usr/local/domoticz/var/plugins/DomoticzLinky/plugin.py" ?

**Comment by guillaumezin** [comment]
Lisez ce fil : https://easydomoticz.com/forum/viewtopic.php?f=10&t=8888&start=80

Certains ont eu le même problème que vous et l'ont résolu

**Comment by Manu4810** [comment]
Effectivement, le processus de copie 'manuelle" a généré des problèmes. Les accents étaient bien présents, mais les guillements tous traduits en &quote, l'indentation et les lignes de commentaire totalement pulvérisées avec un format pseudo-HTML. J'ai donc copié le contenu du plugin dans un fichier vierge UTF-8, puis copié ce ficher dans le NAS via SSH en surveillant l'absence de corruption du format à chaque opération, et après arrêté Domoticz puis redémarré le service et avoir autorisé l'ajout de matériel pendant 5', j'ai vu apparaître le compteur Linky dans le menu déroulant. Merci !

**Comment by Manu4810** [comment]
Cela m'amène à une autre question: je dispose de deux points de livraison (deux compteurs) associés au même compte linky, tous deux avec collecte des données horaires.  Comment le plugin fait-il pour choisir entre les deux compteurs ?

**Comment by guillaumezin** [comment]
La version 1 du plugin est conçue comme si un utilisateur se connectait à son compte Enedis avec son navigateur qui affichait les courbes. Je n'ai qu'un compteur, donc je n'ai mis au point le plugin que dans ce cas de figure, je ne sais pas comment il va se comporter avec 2 compteurs. En revanche, je prépare une version 2 du plugin qui s'appuie sur les API officielles Enedis, cette version gérera 2 compteurs en créant 2 dispositifs Domoticz distincts. La version 2 ne sera déployée que quand j'aurai réglé des questions contractuelles avec Enedis, c'était sur le point de se faire, et COVID-19 est venu mettre le bazar, donc ça n'avance plus...

**Comment by Manu4810** [comment]
Bon, je n'ai pas encore réussi à faire tourner le plugin. Le log mentionne des erreurs 404 page non trouvée et un échec à la connexion, et le compteur indique 0.000kWh. 
Je me demande si les lignes suivantes du plugin sont toujours valables, car quand je me connecte à mon compte ENEDIS, l'URL valable est le suivant: https://mon-compte-particulier.enedis.fr/suivi-de-mesures/

**_LOGIN_BASE_URI = 'espace-client-connexion.enedis.fr'
API_BASE_URI = 'espace-client-particuliers.enedis.fr'
BASE_PORT = '443'
API_ENDPOINT_LOGIN = '/auth/UI/Login'
API_ENDPOINT_DATA = '/group/espace-particuliers/suivi-de-consommation'
API_ACCEPT_TERMS = '/c/portal/update_terms_of_use'_**_**

Cependant, j'ai modifié les variables du plugin en remplaçant 'espace-client-connexion.enedis.fr' par 'mon-compte-particulier.enedis.fr' et 'suivi-de-consommation' par 'suivi-de-mesures' sans plus de succès.

**Comment by guillaumezin** [comment]
Bonjour, j'ai publié le plugin version 2.0.0 qui doit corriger ce problème, n'hésitez pas à mettre à jour et à tester, je ferme ce ticket.

**Comment by Manu4810** [comment]
C'est tout bon, merci !
