### ISSUE TITLE
Improvement : gerer plusieurs compteurs sous le meme compte 

### ISSUE THREAD

**Issue by bigatis** [guillaumezin/DomoticzLinky#43]
Bonjour,
Pour commencer, un grand merci aux développeurs de ce plugin qui me sert énormément. 

Je viens de m'apercevoir qu'enedis propose de gérer plusieurs compteurs sous le meme compte (depuis combien de temps ?).  Actuellement jai du créer plusieurs comptes pour gérer mes différents compteurs (ça marche très  bien mais nécessite de gérer plusieurs  adresses  mail)

Le plugin pourrait évoluer pour prendre en compte cette nouvelle fonctionnalité.

Merci encore
Sylvain

**Comment by guillaumezin** [comment]
Bonjour,
C'est prévu dans la version 2, en cours de développement.
Cordialement,
Guillaume

**Comment by bigatis** [comment]
Bravo !
