### ISSUE TITLE
Mise à jour

### ISSUE THREAD

**Issue by usky73** [guillaumezin/DomoticzLinky#46]
Bonjour,
Petit question sur ce plugin, vu qu'il va falloir faire une mise à jour.
- cette mise à jour est elle automatique ?
- Si ce n'est pas le cas comment identifier la version du pulgin installé ?

**Comment by guillaumezin** [comment]
Bonjour,
Non, la mise à jour n'est pas automatique, sauf si vous utilisez https://www.domoticz.com/wiki/Python_Plugin_Manager (mais vous devez être sous Linux). La version du plugin apparaît dans Configuration / Log lorsque Domoticz démarre ou lorsque vous allez dans Configuration / Matériel, cliquez sur le plugin puis sur "Modifier".

**Comment by guillaumezin** [comment]
Bonjour, une version 2.0.0 du plugin vient d'être publiée, lisez le readme pour mettre à jour.
