### ISSUE TITLE
mise a jour

### ISSUE THREAD

**Issue by dltrainou** [guillaumezin/DomoticzLinky#48]
Bonjour
est ce que la possibilité de compte Enedis multi-compteur est prévue dans la mise a jour?
merci d'avance

rasp pi3 debian buster
domoticz 2020.2

**Comment by ErnieFR** [comment]
> 
> 
> Bonjour
> est ce que la possibilité de compte Enedis multi-compteur est prévue dans la mise a jour?
> merci d'avance
> 
> rasp pi3 debian buster
> domoticz 2020.2

vois autre sujets déjà lancés

**Comment by dltrainou** [comment]
OK,  je vais donc attendre un peu 
merci pour l'excellent travail.

**Comment by guillaumezin** [comment]
Bonjour, veuillez essayer la version 2 qui vient d'être publiée.

**Comment by ErnieFR** [comment]
Salut, le plug-in marche très bien chez moi avec deux compteurs. 
Seulement parce que une maison est vide et vendu, la comsommation est 
nul et le plug-in n'aime pas. Il est rouge et mont dans le log :

2020-11-27 16:11:41.075 Error: PLUGIN-Manager hardware (15) thread seems 
to have ended unexpectedly
2020-11-27 16:15:53.343 Error: PLUGIN-Manager hardware (15) thread seems 
to have ended unexpectedly
2020-11-27 16:17:26.585 Error: (Linky-Combette) durant l'étape save de 
2020-11-26 à 2020-11-27 - Données manquantes pour mettre à jour le 
tableau de bord
Dès quand il-y-a un agence pour visite (vente) la consummation est > 
0kwh le plugin directement est bien pour un jour!

Petit bug je crois, merci pour tout votre temps pour produire le plugin! 
Cdt, Erwin

Op 25-8-2020 om 13:50 schreef Guillaume Zin:

**Comment by guillaumezin** [comment]
Bonjour,
Envoyez par mail (mail visible sur https://github.com/guillaumezin) le fichier log produit par le plugin, le chemin de ce fichier est donné au (re)démarrage du plugin, lorsque vous mettez le paramètre "Debug" sur "Simple".
