### ISSUE TITLE
Envoi de données vers Influxdb

### ISSUE THREAD

**Issue by ricorico94** [guillaumezin/DomoticzLinky#49]
Bonjour,
Mon domoticz envoie certaines données vers un autre raspberry avec Influxdb et Grafana pour faire des graphes, des analyses et aussi pour stocker les valeurs non moyennées (domoticz moyenne les valeurs après un certain temps).
J'ai donc voulu faire pareil avec les données horaires récupérées par le plugin Linky et les envoyer vers Influxdb en utilisant le m'écanisme de Domoticz (menu envoi de données, etc.).
Apparemment, dans ce cas, influxdb ne reçoit rien.. Est-ce normal ? Peut-être est-ce parce que le plugin récupère le sdonnées horaires par batch plutôt que par changement de valeur ? Y a-t-il une méthode pour alle rhistoriser ces données vers influxdb ?

NB: j'ai fait ces tests en juin avant que le plugin s'arrête de fonctionner por cause de login échoué.
J'utilise domoticz 2020.2 sous Raspbian Buster sur un raspberry pi 2B.

Encore merci pour le plugin et bon courage pour la future màj pour réactiver la connexion!
Ricorico94

**Comment by guillaumezin** [comment]
Bonjour,
Je ne suis pas surpris que ça ne fonctionne pas, le plugin récupère effectivement les données par batch, et les insère directement dans les vues d'historique, je ne vois pas de prime abord comment répondre à votre besoin, sans me plonger dans le code C de Domoticz, ce que je ne suis pas pressé de faire (le code est assez indigeste...).

**Comment by ricorico94** [comment]
Bonjour,
Merci pour votre réponse. Dommage que ce ne soit pas facile à faire, mais effectivement je ne vais pas vous demander tout ce boulot ! C'est déjà sympa de passer du temps sur le plugin -et d'ailleurs, il va faloir que je teste pour votre beta pour "réparer" le plugin qui ne fonctionne plus depuis les changements d'Enedis.

**Comment by guillaumezin** [comment]
Bonjour, j'ai cherché un peu mais c'est trop de boulot, je ne le ferai pas.
