### ISSUE TITLE
Probleme de connexion avec le nouveau plugin 2.0

### ISSUE THREAD

**Issue by usky73** [guillaumezin/DomoticzLinky#55]
Bonjour
Je viens de mettre à jour le plugin, domoticz me donne bien un code dans le log par contre quand je le rentre sur le site de enedis j'ai ce message : 
`invalid_request
Code non valide`

Merci de votre aide

**Comment by Dg-59** [comment]
j'ai heu le tour, il faut le refaire plusieurs fois est sa passe

**Comment by usky73** [comment]
bon je me réponds... c'est le readme qui me gène. J'ai suivi le lien et rentré le code mais cela ne marchait pas.
J'ai pris le lien du log avec le code intégré et j'ai pu m'enregistrer.
Mais toujours pas d'info.
Le log de domoticz me donnait un message d'erreur de lecture de config.... Je ne l'ai pas gardé.  :-(
J'ai redémarré le serveur. Du coup il me redonne un code...

**Comment by usky73** [comment]
bon j'ai recommencé et du coup j'ai les messages d'erreur de domoticz
`2020-08-25 17:55:52.598 Error: (Linky - June 2019) Domoticz.Configuration operation failed: 'module 'Domoticz' has no attribute 'Configuration''
2020-08-25 17:55:52.598 Error: (Linky - June 2019) Domoticz.Configuration operation failed: 'module 'Domoticz' has no attribute 'Configuration''
2020-08-25 17:55:52.598 Error: (Linky - June 2019) Domoticz.Configuration operation failed: 'module 'Domoticz' has no attribute 'Configuration''
2020-08-25 17:55:52.598 Error: (Linky - June 2019) Domoticz.Configuration operation failed: 'module 'Domoticz' has no attribute 'Configuration''
2020-08-25 17:55:52.598 Error: (Linky - June 2019) Domoticz.Configuration read failed: 'module 'Domoticz' has no attribute 'Configuration''
2020-08-25 17:55:52.598 Error: (Linky - June 2019) durant l'étape : done - Erreur à la lecture des points de livraison`

**Comment by Dg-59** [comment]
oui bizarre mais ça a fonctionné, j'ai reçu un mail de enedis :

Date de la demande | 25/08/2020
-- | --
Fin du partage | 26/08/2023
Destinataire | Plugin Domoticz ? Linky

est dans mon log:

2020-08-25 17:50:17.899 Error: (Enedis) durant l'étape getdatahours de 2020-08-18 à 2020-08-25 - Pas de données disponibles, avez-vous associé un compteur à votre compte, activé la courbe de charge et demandé la collecte des données par heure sur le site d'Enedis ?
le tps que enedis fasse le changement je pense

**Comment by FFF3347** [comment]
> Bonjour
> Je viens de mettre à jour le plugin, domoticz me donne bien un code dans le log par contre quand je le rentre sur le site de enedis j'ai ce message :
> `invalid_request Code non valide`
> 
> Merci de votre aide

Bonsoir, 
Idem pour moi, ça ne passe pas. 
Je suis sur NAS SYNO. 
Après MAJ de PYTHON, puis de Domoticz (j'étais en 2020.1, passage en 2020.2), et enfin du plugin, quand je m’enregistre, j'ai eu la première fois le même message que vous.

Puis, deuxième tentative :   
> server_error
> lincs-internal-server-error

Au 3ieme essai, c'est passé :)

**Comment by guillaumezin** [comment]
@usky73 en quelle version de Domoticz êtes-vous ?

**Comment by usky73** [comment]
> @usky73 en quelle version de Domoticz êtes-vous ?

Je viens de tout mettre à jour, le raspberry et domoticz : 11995
meme soucis.

**Comment by guillaumezin** [comment]
Votre problème est probablement lié à cette ancienne version de Domoticz. Je suis moi-même sous Raspberry et je n'ai pas de problème de mise à jour. Vous la lancez en ligne de commande avec "updaterelease" ?

**Comment by guillaumezin** [comment]
Ma version sur Raspbian buster :

À propos de Domoticz
Version: 2020.2
Build Hash: b63341bc0
Compile Date: 2020-04-26 13:47:55
dzVents Version: 3.0.2
Python Version: 3.7.3 (default, Dec 20 2019, 18:57:59) [GCC 8.3.0]

**Comment by usky73** [comment]
> Votre problème est probablement lié à cette ancienne version de Domoticz. Je suis moi-même sous Raspberry et je n'ai pas de problème de mise à jour. Vous la lancez en ligne de commande avec "updaterelease" ?

oui, j'ai fait un reboot et domoticz ne se lance plus
Job for domoticz.service failed because the control process exited with error code.

**Comment by Reivax851** [comment]
Pour ma part tout passe jusqu'au même message que @Dg-59 : 
![image](https://user-images.githubusercontent.com/12487713/91218368-3786c800-e719-11ea-8a8c-0bdff6820678.png)
Je vais patienter, on ne sait jamais...
Avec Domoticz: Version: 2020.1 Python 3.5.3

**Comment by Dg-59** [comment]
Version: 2020.2
Build Hash: b63341bc0
Compile Date: 2020-04-26 13:47:55
dzVents Version: 3.0.2
Python Version: 3.7.3 (default, Dec 20 2019, 18:57:59) [GCC 8.3.0]

**Comment by 0rsa** [comment]
Tout a bien fonctionné ici, que ce soit le plugin, le lien avec Enedis, où la récupération des informations du bon PDL. En one shot donc un grand merci à l'auteur pour son boulot.
Debian Buster
Version: 2020.2 (build 12277)
Build Hash: 54acf5178-modified
Compile Date: 2020-08-25 15:30:53
dzVents Version: 3.0.11
Python Version: 3.7.3 (default, Jul 25 2020, 13:03:44) [GCC 8.3.0]

**Comment by guillaumezin** [comment]
@Reivax851 avez-vous activé la collecte des données par demi-heure sur le site d'Enedis ? Une fois fais, les données peuvent n'être disponibles que le lendemain pour le plugin

**Comment by Emile06** [comment]
J'ai cette version de domoticz
Version: 4.10717
Build Hash: b38b49e5
Compile Date: 2019-05-09 13:04:08
dzVents Version: 2.4.19
Python Version: 3.4.2 (default, Jul 11 2019, 21:54:59) [GCC 4.9.2]

dans mesure rien n'est créé, j'ai les message suivants:
 👍  2020-08-26 18:48:00.605 Error: (EDF): Async Secure Read Exception: 1, stream truncated
2020-08-26 18:48:10.588 Error: (EDF): Async Secure Read Exception: 1, stream truncated
2020-08-26 18:48:20.565 Error: (EDF) Domoticz.Configuration operation failed: ''module' object has no attribute 'Configuration''
2020-08-26 18:48:20.565 Error: (EDF) Domoticz.Configuration operation failed: ''module' object has no attribute 'Configuration''
2020-08-26 18:48:20.565 Error: (EDF) Domoticz.Configuration operation failed: ''module' object has no attribute 'Configuration''
2020-08-26 18:48:20.565 Error: (EDF) Domoticz.Configuration operation failed: ''module' object has no attribute 'Configuration''
2020-08-26 18:48:20.565 Error: (EDF) Domoticz.Configuration read failed: ''module' object has no attribute 'Configuration''
2020-08-26 18:48:20.565 Error: (EDF) durant l'étape : done - Erreur à la lecture des points de livraison
2020-08-26 18:48:20.566 Error: (EDF): Async Secure Read Exception: 1, stream truncated 

La version 4.10717de Domoticz est-elle compatible?

**Comment by guillaumezin** [comment]
J'ai parcouru le code de Domoticz et le plugin n'est compatible qu'à partir de la version 11070, il faut que je mette à jour le readme

**Comment by busshi** [comment]
> oui bizarre, moi ça a fonctionné, j'ai reçu un mail de enedis :
> 
> Date de la demande	25/08/2020
> Fin du partage	26/08/2023
> Destinataire	Plugin Domoticz ? Linky
> est dans mon log:
> 
> 2020-08-25 17:50:17.899 Error: (Enedis) durant l'étape getdatahours de 2020-08-18 à 2020-08-25 - Pas de données disponibles, avez-vous associé un compteur à votre compte, activé la courbe de charge et demandé la collecte des données par heure sur le site d'Enedis ?
> le tps que enedis fasse le changement je pense

Bonjour,

J’ai le même problème que vous pourtant j’ai bien activé la collecte par heures sur le site d’Enedis. Avez-vous résolu le problème ? Si oui, comment ?

Merci d’avance.

PS : qu’est-ce que la courbe de charge ?

**Comment by guillaumezin** [comment]
La courbe de charge, c'est l'ancien nom sur le site d'Enedis de l'enregistrement de données, c'est désuet, je vais supprimer le terme.

Voici ce que vous devez activer sur votre compte:

![CollecteEnedis](https://user-images.githubusercontent.com/541581/91339599-010f8280-e7d7-11ea-8ea0-e63aeba8fce9.png)

Allez dans "Gérer l'accès à mes données" et activez "Collecte de la consommation horaire" et "Enregistrement de la consommation horaire".

**Comment by Reivax851** [comment]
Bonsoir, oui ces deux options ont été activé hier soir et depuis hier j'ai obtenu des data dans domoticz MAIS j'ai encore de façon régulière le message indiqué plus haut, exactement le même. c'est assez étonnant sachant que le device API LINKY a bien été créé et qu'il contient des données qui correspondent à celle sur mon compte... j'ai le message d'erreur une fois par heure.

**Comment by busshi** [comment]
> La courbe de charge, c'est l'ancien nom sur le site d'Enedis de l'enregistrement de données, c'est désuet, je vais supprimer le terme.
> 
> Voici ce que vous devez activer sur votre compte:
> 
> ![CollecteEnedis](https://user-images.githubusercontent.com/541581/91339599-010f8280-e7d7-11ea-8ea0-e63aeba8fce9.png)
> 
> Allez dans "Gérer l'accès à mes données" et activez "Collecte de la consommation horaire" et "Enregistrement de la consommation horaire".

Merci pour votre réactivité. Les collectes et enregistrements horaires sont bien activés. D’ailleurs j’utilisais l’ancien plugin et je n’avais pas eu de soucis à ce niveau là. Quand je vais sur le site d’Enedis, j’ai bien ma consommation horaire qui s’affiche. Peut-être le problème vient d’autre chose ? Domoticz et plugin à jour...

**Comment by usky73** [comment]
Bon finalement j'ai tout reinstallé...
Et ca marche. 
Encore merci pour ce plugin.

**Comment by Emile06** [comment]
@usky73  heureux pour toi. Merci de me donner ta version de domoticz?

**Comment by FFF3347** [comment]
> Edit : le problème venait du fait que je voulais récupérer 720 jours alors que le compteur n’est en service que depuis 1 an... si ça peut aider quelqu’un dans le même cas que moi...

Bonjour, 
De mon coté, compteur communiquant depuis avril 2019 et même en laissant 720 jours, c'est passé sans souci.

**Comment by usky73** [comment]
> @usky73 heureux pour toi. Merci de me donner ta version de domoticz?

install toute neuve, version 2020.2 et derniere version raspbian

**Comment by Emile06** [comment]
Oui, j'ai résolu mon problème avec la dernière version de domoticz sur rasbian buster. Il faut absolument  buster sans quoi domoticz même avec la dernière version ne redémarre pas ( c'est un pb de format de la base de données )
