### ISSUE TITLE
problème pour démarrer le plugin

### ISSUE THREAD

**Issue by jmcaous** [guillaumezin/DomoticzLinky#63]
Bonjour 

ma configuration : raspbian buster à jour sur raspberry pi 2
Version: 2020.2
Build Hash: b63341bc0
Compile Date: 2020-04-26 13:47:55
dzVents Version: 3.0.2
Python Version: 3.7.3 (default, Jul 25 2020, 13:03:44) [GCC 8.3.0]

je ne parviens pas à démarrer le plugin

020-08-29 15:57:37.199 Error: (linky) failed to load 'plugin.py', Python Path used was '/opt/domoticz/plugins/DomoticzLinky/:/usr/lib/python37.zip:/usr/lib/python3.7:/usr/lib/python3.7/lib-dynload:/usr/local/lib/python3.7/dist-packages:/usr/lib/python3/dist-packages:/usr/lib/python3.7/dist-packages'.
2020-08-29 15:57:37.199 Error: (Linky) Module Import failed, exception: 'ValueError'
2020-08-29 15:57:37.199 Error: (Linky) Error Line details not available. 

désolé si c'est de ma faute ..

**Comment by guillaumezin** [comment]
Sans plus de détail de la part de Domoticz, c'est compliqué. C'est une mise à jour ? Si c'est une mise à jour, essayez de supprimer le dispositif de l'onglet matériel, effacez ou renommez plugin.py, redémarrez Domoticz, remettez plugin.py, redémarrez Domoticz, ajoutez le dispositif dans l'onglet Matériel.

**Comment by jmcaous** [comment]
Merci pour le retour, ça a marché
c'était suite à une mise à jour du plugin
