### ISSUE TITLE
Retry - Trop d'echecs de communication...

### ISSUE THREAD

**Issue by Kirioss** [guillaumezin/DomoticzLinky#67]
Bonjour, 

Plugin : 2.0.7
Domoticz : 2020.2

Le plugin ne récupère pas les données depuis 2 ou 3 jours maintenant. J'avais le message "données manquantes" (elles sont bien sur le site de Enedis) et j'ai maintenant le message "trop d'echecs de communication, le plugin réessaiera plus tard"

En activant le mode debug, je crois voir dans le message HTML 'ReadEvent' une réponse "Too many requests" avec error description "Quota Q4 reached call threshold allowed..."

Y'a-t-il un réglage à faire pour limiter le nombre d'appels ?

Merci

**Comment by Kirioss** [comment]
Je viens de voir que la collecte de la conso horaire s'est désactivée sur le site Enedis. Je l'ai réactivée, je verrai si ca règle le problème de communication

**Comment by guillaumezin** [comment]
Bonjour,
Oui, réactivez et attendez un ou deux jours, par contre, le message "Quota Q4 reached call threshold allowed...", c'est la première fois que je le vois, ce serait bien que vous postiez votre log s'il-vous-plaît.

**Comment by Kirioss** [comment]
Les données sont maintenant bien récupérées, même si je vois encore l'erreur :
2020-09-03 18:37:00.106 Error: (Linky) durant l'étape getdatahours de 2020-08-27 à 2020-09-03 - Données manquantes

Par contre, je ne vois plus l'erreur sur le quota et je ne retrouve pas la log qui la contenait...

**Comment by guillaumezin** [comment]
Ok, je ferme le ticket.
