### ISSUE TITLE
parsedevicecode - Erreur status : 500

### ISSUE THREAD

**Issue by HereComesANewChallenger** [guillaumezin/DomoticzLinky#68]
* Domoticz
** Version: 2020.2 (build 12313)
** Build Hash: b89981a43-modified
** Compile Date: 2020-08-31 09:38:27
** dzVents Version: 3.0.11
** Python Version: 3.7.3 (default, Jul 25 2020, 13:03:44) [GCC 8.3.0]
* Linux raspberrypi 5.4.59-v7l+ #1338 SMP Fri Aug 28 11:55:37 BST 2020 armv7l GNU/Linux
* Raspberry Pi 4

Depuis mercredi je constate un soucis de récupération de données (plus de données depuis mercredi).
Mes données sont visible sans soucis sur le site d'enedis.
Le log d'erreur est:
 * 2020-09-04 09:19:05.967 Error: (Linky) durant l'étape : parsedevicecode - Erreur status : 500 

J'ai essayé de recréer le materiel, voici le log complet (en Debug:Simple):

> 2020-09-04 09:18:36.147 Status: (Linky) Stopping threads.
> 2020-09-04 09:18:36.147 Status: (Linky) Stopped.
> 2020-09-04 09:18:36.147 Status: (Linky) Started.
> 2020-09-04 09:18:36.228 Status: (Linky) Entering work loop.
> 2020-09-04 09:18:36.229 Status: (Linky) Initialized version 2.0.8, author 'Barberousse'
> 2020-09-04 09:18:46.253 (Linky) Etape idle
> 2020-09-04 09:18:46.253 (Linky) Récupération des données...
> 2020-09-04 09:18:46.253 (Linky) Dict details (4):
> 2020-09-04 09:18:46.253 (Linky) --->'Verb':'POST'
> 2020-09-04 09:18:46.253 (Linky) --->'URL':'/device/code'
> 2020-09-04 09:18:46.253 (Linky) --->'Headers (3):
> 2020-09-04 09:18:46.253 (Linky) ------->'Accept':'application/json'
> 2020-09-04 09:18:46.253 (Linky) ------->'Content-Type':'application/x-www-form-urlencoded'
> 2020-09-04 09:18:46.254 (Linky) ------->'Host':'enedis.domoticz.russandol.pro:443'
> 2020-09-04 09:18:46.254 (Linky) --->'Data':'client_id=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
> 2020-09-04 09:18:56.247 (Linky) Etape sending
> 2020-09-04 09:19:05.966 (Linky) Etape parsedevicecode
> 2020-09-04 09:19:05.967 (Linky) Dict details (2):
> 2020-09-04 09:19:05.967 (Linky) --->'Status':'500'
> 2020-09-04 09:19:05.967 (Linky) --->'Headers (5):
> 2020-09-04 09:19:05.967 (Linky) ------->'Content-Length':'0'
> 2020-09-04 09:19:05.967 (Linky) ------->'Content-Type':'text/html; charset=UTF-8'
> 2020-09-04 09:19:05.967 (Linky) ------->'Date':'Fri, 04 Sep 2020 07:18:55 GMT'
> 2020-09-04 09:19:05.967 (Linky) ------->'Server':'Apache/2.4.38 (Debian)'
> 2020-09-04 09:19:05.967 (Linky) ------->'Vary':'Accept-Encoding'
> 2020-09-04 09:19:05.968 (Linky) Prochaine connexion : 2020-09-04 10:56:05
> 2020-09-04 09:19:05.967 Error: (Linky) durant l'étape : parsedevicecode - Erreur status : 500

Il semblerait que le soucis vienne du server enedis.domoticz.russandol.pro ...
Une idée ? Un avis ? Un conseil ?

**Comment by yoztheripper** [comment]
J'ai la même chose ici, plus aucune données, alors que sur le site Enedis, tout est ok

**Comment by patvdp145** [comment]
Bonjour à tous,
même genre d'erreur mais à l'étape "parseaccesstoken".  Token devenu invalide/obsolète?
En tout cas, merci pour le travail réalisé sur ce plugin...


2020-09-04 09:06:01.682 (ENEDIS) Etape getdatahours
2020-09-04 09:06:01.683 (ENEDIS) Dict details (4):
2020-09-04 09:06:01.683 (ENEDIS) --->'Verb':'POST'
2020-09-04 09:06:01.683 (ENEDIS) --->'URL':'/device/proxy'
2020-09-04 09:06:01.683 (ENEDIS) --->'Headers (3):
2020-09-04 09:06:01.683 (ENEDIS) ------->'Accept':'application/json'
2020-09-04 09:06:01.683 (ENEDIS) ------->'Content-Type':'application/x-www-form-urlencoded'
2020-09-04 09:06:01.683 (ENEDIS) ------->'Host':'enedis.domoticz.russandol.pro:443'
2020-09-04 09:06:01.683 (ENEDIS) --->'Data':'grant_type=refresh_token&client_id=xxxxx&refresh_token=XXXXXXXXX'
2020-09-04 09:06:10.566 (ENEDIS) Etape sending
2020-09-04 09:06:15.876 (ENEDIS) Etape parseaccesstoken
2020-09-04 09:06:15.876 (ENEDIS) Dict details (2):
2020-09-04 09:06:15.876 (ENEDIS) --->'Status':'500'
2020-09-04 09:06:15.876 (ENEDIS) --->'Headers (5):
2020-09-04 09:06:15.876 (ENEDIS) ------->'Content-Length':'0'
2020-09-04 09:06:15.876 (ENEDIS) ------->'Content-Type':'text/html; charset=UTF-8'
2020-09-04 09:06:15.876 (ENEDIS) ------->'Date':'Fri, 04 Sep 2020 07:06:05 GMT'
2020-09-04 09:06:15.877 (ENEDIS) ------->'Server':'Apache/2.4.38 (Debian)'
2020-09-04 09:06:15.877 (ENEDIS) ------->'Vary':'Accept-Encoding'
2020-09-04 09:06:30.602 (ENEDIS) Etape retry
2020-09-04 09:06:40.602 (ENEDIS) Etape sending
2020-09-04 09:06:41.805 (ENEDIS) Etape parseaccesstoken 
...

**Comment by yoztheripper** [comment]
Je vois ceci dans les logs

Relancez le en vous rendant dans Configuration/Matériel, en cliquant sur le plugin puis sur Modifier. Surveillez les logs pour obtenir le lien afin de renouveler le consentement pour la récupération des données auprès d'Enedis

Mais je ne vois jamais le lien de consentement...

**Comment by HereComesANewChallenger** [comment]
J'ai relancer la collecte en allant dans "Configuration/Matériel" puis en cliquant sur le plugin puis sur Modifier.
Cette fois ci, cela s'est bien passé.

J'imagine qu'un service a été redémarrer sur le serveur enedis.domoticz.russandol.pro ?

**Comment by yoztheripper** [comment]
Ok pour moi aussi, j'ai réinitialisé le consentement et c'est tout bon de mon côté, j'avais le lien dans les logs ce coup ci

**Comment by guillaumezin** [comment]
Le serveur d'authentification est "tombé" quelques heures, c'est revenu. Par contre il faut que je robustifie le plugin pour que ça n'entraîne pas de devoir redemander le consentement.

**Comment by guillaumezin** [comment]
La version 2.0.9 devrait vous éviter d'avoir à refaire le consentement en cas de panne serveur. Confirmez-vous que ça refonctionne ?

**Comment by HereComesANewChallenger** [comment]
Je viens de tester la version 2.0.9.
Pas de régression à signaler.
Je ferme le ticket.
Je ne pense pas qu'il soit nécessaire de faire un test en arrêtant le service d'authentification ;)

**Comment by guillaumezin** [comment]
@HereComesANewChallenger vous vous moquez, mais nous avons 2 serveurs de tests en plus du serveur de production, justement pour faire des essais :-) Après ce sont des serveurs qui simulent des réponses, on est forcément un peu juge et partie, donc il y a pleins de cas limites que je n'ai découverts qu'en passant en production :-(
