### ISSUE TITLE
Affichage dashboard

### ISSUE THREAD

**Issue by lambertchazal** [guillaumezin/DomoticzLinky#7]
Bonjour,
Le plugin fonctionne très bien mais j'ai un problème d'affichage dans le dashboard (**utilisation:undefined**). Or dans le menu mesure, tout s'affiche correctement en fonction de l'option choisi dans l'Hardware.

![screenshot_20190221_073250](https://user-images.githubusercontent.com/47811411/53148786-18e7c400-35ac-11e9-998a-611993f4323d.jpg)

Version du plugin : 1.1.1
Version de domoticz : 4.10445

Auriez-vous une idée du problème ?

**Comment by guillaumezin** [comment]
Effectivement, j'arrive à reproduire votre problème, je pense que c'est plus dans le code de Domoticz qu'il y a une modification à faire, je m'en chargerai

**Comment by guillaumezin** [comment]
C'était effectivement un bug dans Domoticz et pas dans le plugin lui-même, c'est corrigé à partir de la version 4.10456, pouvez-vous me dire si c'est mieux (pensez à effacer votre cache) ?

**Comment by lambertchazal** [comment]
Bonjour

je viens de faire la mise à jour, le problème est résolu.
merci beaucoup pour la rapidité.
