### ISSUE TITLE
Idée de fonctionnalité 

### ISSUE THREAD

**Issue by djpostka** [guillaumezin/DomoticzLinky#70]
Bonjour,

Pour commencer, merci pour le travail et le temps passé sur le plugin.
Je m'excuse si ce n'est pas le lieu approprié pour soumettre l'idée.

Pensez-vous qu'il soit possible d'ajouter un paramètre "coût du kWh" à renseigner suivant l'abonnement de l'utilisateur, et ainsi, pouvoir afficher un graph avec le montant en euros de la consommation journalière/hebdo et mensuel ?

Encore merci :)

**Comment by macbenoit** [comment]
Tu peux renseigner tes tarifs hc hp dans le menu configuration/paramètres onglet sondes compteur

**Comment by guillaumezin** [comment]
Cf. https://easydomoticz.com/l/ par exemple pour configurer tout ça.

**Comment by djpostka** [comment]
Oups, je n'avais pas bien compris le readme qui explique la manip... Cependant, dans "Configuration / Paramètres / Système / Matériel/dispositifs", j'ai bien le "P1 Smart meter" qui est présent et correspond normalement au plugins Linky, mais je ne peux renseigner mes heures/jours d'heures creuses, uniquement le montant de celle-ci.

![2020-09-07 09_46_16-Domoticz](https://user-images.githubusercontent.com/7514237/92361743-295c8280-f0ef-11ea-914a-800b7371f6df.png)

**Comment by djpostka** [comment]
Je n'ai rien dit, merci pour l'aide, je clos.
