### ISSUE TITLE
Donnation 

### ISSUE THREAD

**Issue by macbenoit** [guillaumezin/DomoticzLinky#72]
Existe t’il un endroit où on peut te faire une donation ? 
Tu fais beaucoup d’efforts pour nous la moindre des choses serait cette possibilité. J’ai passé 3 mois sans ton plugin c’était vraiment la mort ! 
Merci en tout cas ùne question c’est quoi ces colonnes compteur t1 et t2 ? Ça s’enlève pas ?

**Comment by macbenoit** [comment]
Et aussi si tu pouvais ajouter un champ coût abonnement journalier qui s’intègre au rapport de chaque jour ce serait intéressant bon je chipote

**Comment by guillaumezin** [comment]
Bonjour,

Je n'ai pas la main dans le plugin sur la façon dont s'affiche les colonnes, c'est dans le code de Domoticz, et je n'irai pas modifier le code de Domoticz vu le mal que j'ai eu déjà à faire accepter les petites modifications que j'ai proposées (et ce code, c'est le foutoir accessoirement). Par contre Domoticz gère la tarification, vous pouvez établit le coût du kWh dans les paramètres et le résultat apparaît quand vous cliquez sur "Rapport" dans le log du compteur. Regardez comment ils configurent ça ici : https://easydomoticz.com/l/ mais c'est peut-être déjà ce que vous faites.

Pour la donation, j'en avais déjà parlé à Frédéric qui gère l'infrastructure intermédiaire de consentement, il a des coûts récurrents, je vais voir avec lui.

**Comment by macbenoit** [comment]
Oui c’est déjà ce que je fais. Mais on peut pas ajouter le prix de l’abonnement. Bon après c’est pas essentiel non plus. Si ça se trouve je peux créer un script qui calculera mon coût mensuel en cours ! Quelle serait la requête http ou mqqt pour récupérer le prix de la consommation totale mensuelle ?

**Comment by macbenoit** [comment]
J’attend votre réponse je sais que PayPal ne prend pas de r’frais il me semple

**Comment by jpcasta** [comment]
Je suis d'accord pour la donation....., il le mérite bien!

**Comment by s0nik42** [comment]
gitcoin 👍

**Comment by macbenoit** [comment]
Mdr ok dirait une monnaie de forza sur Xbox 360

**Comment by s0nik42** [comment]
c'est plutot cool

**Comment by macbenoit** [comment]
Ça dépend moi je donne pas sur des plateforme chelou, de la vraie tune sur PayPal ça me rassure plus que des kudos lol

**Comment by guillaumezin** [comment]
Je ne suis pas fan des crypto-monnaies, en tout cas tant qu'elles entraînent une consommation aussi monstrueuse. Je vais plutôt vous proposer un Paypal, plutôt pour Frédéric dans ce cas qui a des frais avec l'infrastructure de consentement. Je vois avec lui.

**Comment by macbenoit** [comment]
Je valide PayPal vous le méritez vraiment

**Comment by guillaumezin** [comment]
Bonjour, consultez le readme, c'est ajouté.
