### ISSUE TITLE
formulation double tarif

### ISSUE THREAD

**Issue by dltrainou** [guillaumezin/DomoticzLinky#79]
bonjour
J'ai un doute sur la formulation des plages horaires? dans mon dispositif domoticz , j'ai "invalid"
j'ai 2 compteurs : plA en double tarif plage 23h30-7h30 et un plB en simple tarif.
dois je mettre 
plA 23h30-07h30 plB
ou
23h30-07h30 plA plB 
merci d'avance

**Comment by guillaumezin** [comment]
La philosophie, c'est "CasGeneral CasParticulier", donc vous devez faire:
plA 23h30-07h30
car le cas général, qui se place avant plA, c'est de ne pas définir de plage

**Comment by dltrainou** [comment]
Merci mais j’ai un souci peut être lié sur le compteur plA (double tarif)? Mis en « plA 23h30-07h30 »

Le dispositif est bien créé mais il est marqué « Invalid » et j’ai l’erreur ds le log :

Error: (linky) durant l'étape save de 2020-09-13 à 2020-09-14 - Données manquantes pour mettre à jour le tableau de bord

Et les données s’arrêtent a vendredi, alors que sur le plB elle vont jusqu’à dimanche ??

Une idée ? merci d’avance

De : Guillaume Zin [mailto:notifications@github.com] 
Envoyé : lundi 14 septembre 2020 15:38
À : guillaumezin/DomoticzLinky <DomoticzLinky@noreply.github.com>
Cc : dltrainou <dltrainou@free.fr>; Author <author@noreply.github.com>
Objet : Re: [guillaumezin/DomoticzLinky] formulation double tarif (#79)

 

La philosophie, c'est "CasGeneral CasParticulier", donc vous devez faire:
plA 23h30-07h30
car le cas général, qui se place avant plA, c'est de ne pas définir de plage

**Comment by guillaumezin** [comment]
Si les données s'arrêtent vendredi au lieu d'hier, c'est normal qu'il y ait un problème à mettre à jour le ableau de bord, ça n'a rien à voir avec la tarification, le plugin utilise les données de la veille pour mettre à jour la valeur affichée sur le tableau de bord.

Entre parenthèses, notez que
plA 23h30-07h30
plA 23h30-07h30 plB
plB plA 23h30-07h30
sont équivalents

**Comment by dltrainou** [comment]
Sur le site enedis les données de dimanche sont bien présentes pour ce compteur??

 

De : Guillaume Zin [mailto:notifications@github.com] 
Envoyé : lundi 14 septembre 2020 17:46
À : guillaumezin/DomoticzLinky <DomoticzLinky@noreply.github.com>
Cc : dltrainou <dltrainou@free.fr>; Author <author@noreply.github.com>
Objet : Re: [guillaumezin/DomoticzLinky] formulation double tarif (#79)

 

Si les données s'arrêtent vendredi au lieu d'hier, c'est normal qu'il y ait un problème à mettre à jour le ableau de bord, ça n'a rien à voir avec la tarification, le plugin utilise les données de la veille pour mettre à jour la valeur affichée sur le tableau de bord.

Entre parenthèses, notez que
plA 23h30-07h30
plA 23h30-07h30 plB
plB plA 23h30-07h30
sont équivalents

**Comment by dltrainou** [comment]
Ca doit être du coté enedis, la case conso horaire ne peut pas être cochée sur ce compteur la, sur l’autre pas de pb

La collecte horaire était désactivée depuis vendredi ?? je ne sais pas pourquoi ? je n’ai pas été sur le site.

 

De : Guillaume Zin [mailto:notifications@github.com] 
Envoyé : lundi 14 septembre 2020 17:46
À : guillaumezin/DomoticzLinky <DomoticzLinky@noreply.github.com>
Cc : dltrainou <dltrainou@free.fr>; Author <author@noreply.github.com>
Objet : Re: [guillaumezin/DomoticzLinky] formulation double tarif (#79)

 

Si les données s'arrêtent vendredi au lieu d'hier, c'est normal qu'il y ait un problème à mettre à jour le ableau de bord, ça n'a rien à voir avec la tarification, le plugin utilise les données de la veille pour mettre à jour la valeur affichée sur le tableau de bord.

Entre parenthèses, notez que
plA 23h30-07h30
plA 23h30-07h30 plB
plB plA 23h30-07h30
sont équivalents

**Comment by dltrainou** [comment]
Bonjour
Ça tourne impeccable, je voulais vous remercier pour le boulot.
Merci encore
