### ISSUE TITLE
Uuntu 20.04 - Can't sho the plugin

### ISSUE THREAD

**Issue by gamersalpha** [guillaumezin/DomoticzLinky#82]
Hello à tous, 

so i got a frech ubuntu install 20.04 LTS

so i install domoticz with this : 

`sudo curl -L install.domoticz.com | bash`

so on my web interface i got this : 

![image](https://user-images.githubusercontent.com/32466950/93668522-0afe6b80-fa8d-11ea-8f80-afd523c5e083.png)

but when i put the plugins like this : 

```
cd /home/stagiaire/domoticz/plugins/
git clone https://github.com/guillaumezin/DomoticzLinky
cd /home/stagiaire/domoticz/plugins/DomoticzLinky
sudo chmod ugo+x plugin.py
```

So now i try to add my hardware i can't found the plugin do u know what is wrong please 👍 

![2Zck7McCC2](https://user-images.githubusercontent.com/32466950/93668576-72b4b680-fa8d-11ea-8e05-0e0077e91feb.gif)

thanks all

**Comment by dltrainou** [comment]
bonjour
avez vous redémarré domoticz?

**Comment by guillaumezin** [comment]
Vous avez "Python Version: None", vous devez installer Python 3 et redémarrer Domoticz

**Comment by guillaumezin** [comment]
Cf. https://www.domoticz.com/wiki/Using_Python_plugins#Installing_Python_on_Raspberry_Pi_with_Raspbian_.28should_work_on_any_Debian_system.29

**Comment by gamersalpha** [comment]
Hello so i do all stuff to install python 3 : 



```
stagiaire@domoticz:~/domoticz/plugins$  sudo apt install python3
[sudo] password for stagiaire:
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances
Lecture des informations d'état... Fait
python3 est déjà la version la plus récente (3.8.2-0ubuntu2).
0 mis à jour, 0 nouvellement installés, 0 à enlever et 0 non mis à jour.
stagiaire@domoticz:~/domoticz/plugins$  python3 -V
Python 3.8.2
stagiaire@domoticz:~/domoticz/plugins$  dpkg --get-selections | grep libpython
libpython2-stdlib:amd64                         install
libpython2.7-minimal:amd64                      install
libpython2.7-stdlib:amd64                       install
libpython3-stdlib:amd64                         install
libpython3.8:amd64                              install
libpython3.8-minimal:amd64                      install
libpython3.8-stdlib:amd64                       install
stagiaire@domoticz:~/domoticz/plugins$ sudo service domoticz restart

-bash-5.0$ ls  domoticz/
appveyor.yml    domoticz         extern        License.txt    plugins          tcpserver      webserver
CMakeCache.txt  domoticz.db      getgit.cmake  main           push             tinyxpath      www
CMakeFiles      domoticz.db-shm  hardware      makebeta       README.md        tools
CMakeLists.txt  domoticz.db-wal  History.txt   makerelease    scripts          updatebeta
Config          domoticz.sh      httpclient    msbuild        server_cert.pem  updatedomo
domocookie.txt  dzVents          INSTALL.md    notifications  smtpclient       updaterelease
-bash-5.0$ ls  domoticz/plugins/
AwoxSMP  DomoticzLinky  examples
-bash-5.0$ ls  domoticz/plugins/DomoticzLinky/
plugin.py  readme.md

stagiaire@domoticz:~/domoticz/plugins$ sudo reboot

```


but when i go in interface web i got this : 

![image](https://user-images.githubusercontent.com/32466950/93671042-18712100-faa0-11ea-8f60-0e1c09714ddd.png)

and still no LInky plugin see on domoticz

what is wrong

**Comment by gamersalpha** [comment]
J'ai refait une install propre, et j'ai bien le plugin, 

mais je ne comprend pas ou paramétrer mes identifiants : 

![image](https://user-images.githubusercontent.com/32466950/93671276-ebbe0900-faa1-11ea-8572-b6ba3c2d578a.png)

**Comment by dltrainou** [comment]
Commencez par surveiller votre Configuration / Log. Aux premières connexions, le plugin doit vous donner l'adresse Web https://opensrcdev.alwaysdata.net/domoticzlinkyconnect/device à consulter et un code à y copier/coller pour obtenir le consentement du partage de données d'Enedis vers le plugin.

**Comment by gamersalpha** [comment]
merci çà fonctionne : 

![image](https://user-images.githubusercontent.com/32466950/93671679-5cb2f000-faa5-11ea-9a87-fa2374663a90.png)


^pas facile à activer, mais ça marche, mais j'avoue que j'y comprend rien au graph, comment je sais qu'elle appareille consomme quoi ?

**Comment by guillaumezin** [comment]
Ce n'est pas magique, Enedis n'indique qu'une consommation globale du logement, on déduit des fois quel appareil consomme (par exemple une hausse très forte et très brutale, c'est souvent des plaques à induction), mais en dehors de ça, c'est difficile.
Par contre, en ce qui me concerne, on en déduit facilement quand je suis à la maison ou pas, et donc mes habitudes, c'est important que ces données restent privées.
