### ISSUE TITLE
Too.Many.Requests - Quota.Q4.reached

### ISSUE THREAD

**Issue by r3z3** [guillaumezin/DomoticzLinky#84]
Bonjour,

Conf : Domoticz 2020.2 / Raspberry PI / Plugin DomoticzLinky à jour par git pull
Heure creuses : 22h00-7h00 samedi 07h00-22h00 dimanche 07h00-22h00
Nbre de jours à récupérer vue heures : 7
Nbre de jours à récupérer : 300

Mes données ne se mettent plus à jour depuis le 01/09/2020 avec l'erreur suivante (mode debug)   :

HTTP/1.1.429.**Too.Many.Requests**..Date:.Thu,.24.Sep.2020.09:15:42.GMT..Allow:.GET,.HEAD,.OPTIONS..Connection:.close..Content-Type:.application/json;.charset="UTF-8"..Transfer-Encoding:.chunked....69..{...."error".:."429",...."error_description".:."**Quota.Q4.reached**..Call.threshold.allowed.on.0:-30:-40"

Un quota mis en place côté ENEDIS ??

**Comment by guillaumezin** [comment]
Cf. #83, je pense que c'est la même chose

**Comment by r3z3** [comment]
Peut-être,
Je suis donc passé à 02h00 (récupération vue heures) et 150 jours pour le reste, mais ça ne marche toujours pas...

**Comment by r3z3** [comment]
Je viens de désactiver (passage à "0") la vue par heures et j'ai mis 50 jours à récupérer.
...et ça marche !
Comment identifier la limite max acceptable côté ENEDIS ??

**Comment by guillaumezin** [comment]
Bonne question, mais je ne sais pas y répondre pour le moment...

**Comment by r3z3** [comment]
Bon alors à tâtons :o)
On peut clore l'issue du coup ?
Merci encore

**Comment by guillaumezin** [comment]
Oui, on stabilise mais ça se cherche encore tout ça...
