### ISSUE TITLE
Ajout d'une ligne 'Status' dans le log avec l'information de la date et l'heure du dernier chargement de données

### ISSUE THREAD

**Issue by jpcasta** [guillaumezin/DomoticzLinky#86]
Bonjour,
Ceci est une demande d'amélioration. (Enhancement)
Je pense que vu le nombre d'échecs de communication avec les serveurs Enedis, il serait intéressant de rajouter une ligne 'Status' dans le log de Domoticz avec l'information de la date et l'heure du dernier chargement de données qui a été effectué avec succès.
Ainsi on conserverait l'historique dans l'onglet Statut.
Ex: 2020-09-29 09:45:42.975 Status: (Compteur) Chargement des données Enedis

Peut-être qu'en même temps, on pourrait aussi mettre en tant que Status, l'information de la prochaine connexion?

Merci
Cordialement

**Comment by guillaumezin** [comment]
Effectivement, ces données sont présentes dans le Log, mais vite noyées par le reste des informations, je pense que c'est faisable.

**Comment by guillaumezin** [comment]
Voulez-vous essayer la version 2.2.8 ?

**Comment by jpcasta** [comment]
Super c'est parfait....merci!!
Bonne soirée


Le 01/10/2020 à 19:34, Guillaume Zin a écrit :

**Comment by guillaumezin** [comment]
Ok, alors je clos.
