### ISSUE TITLE
IHM Plugin incomplet

### ISSUE THREAD

**Issue by mkfrcp** [guillaumezin/DomoticzLinky#88]
Bonjour,

Utilisateur de l'ancienne version de Linky, j'attendais avec impatience la mise à jour. J'en ai profité pour refaire une installation propre de Domoticz sur un Rpi 3B+ (dernière version de Raspian disponible sur le site Raspberry)).
J'ai installé la dernière version de Domoticz V2020.2/Build Hash: b63341bc0, Date: 2020-04-26 13:47:55.
J'ai installé le plugin Linky comme indiqué, sans difficulté.
Malheureusement, l'interface du plugin n'est pas complète. Je ne trouve pas les champs pour renseigner l'adresse et MdP du compte Enedis. J'ai refait trois installations en partant de zéro, mais rien n'y fait. Ces champs n'apparaissent toujours pas (voir ci-dessous).
Quelle peut être la cause de ce problème et surtout, comment le résoudre ?

Merci d'avance pour votre aide.

![2020-09-30 10_39_41-Linky](https://user-images.githubusercontent.com/19577023/94663066-853eb380-0309-11eb-8965-7962016f616b.png)

**Comment by guillaumezin** [comment]
Bonjour,
Relisez attentivement le readme de la nouvelle version, le plugin n'utilise plus votre mot de passe directement, mais vous demandera de vous connecter à une page pour donner à Enedis votre consentement pour recueillir les données, surveillez le log.

**Comment by mkfrcp** [comment]
Oups. Je suis confus :) L'habitude a été plus forte que la lecture du read.me, pourtant clair. J'ai accepté à travers le liens et reçu le mail de confirmation d'Enedis. Malheureusement, Dtz n'affiche pas les données. Le log contient le message suivant :  Error: (Linky) durant l'étape getdatahours de 2020-09-23 à 2020-09-30 - Pas de données disponibles, avez-vous associé un compteur à votre compte et demandé l'enregistrement et la collecte des données horaire sur le site d'Enedis (dans "Gérer l'accès à mes données") ? J'avais pourtant fait le nécessaire puisque cela fonctionnait il y a encore quelques mois. Lorsque je vais sur le site Enedis, il est indiqué que le site est momentanément HS...
![image](https://user-images.githubusercontent.com/19577023/94665618-ab198780-030c-11eb-922a-cdb2c52bef60.png)
Je vais donc attendre qu'il soit rétabli pour vérifier que tout est OK dans Dtz.  
Merci encore et bravo pour le travail réalisé !

**Comment by guillaumezin** [comment]
Il faut malgré tout que je reprécise les choses dans le readme, voire que j'ajoute des images.

**Comment by guillaumezin** [comment]
Je clos, j'ai un peu amélioré le readme.

**Comment by mkfrcp** [comment]
C'est en effet très clair maintenant. Encore merci 👍
