### ISSUE TITLE
Consommations incohérentes

### ISSUE THREAD

**Issue by jcsombret** [guillaumezin/DomoticzLinky#89]
Bonjour,

J'ai installé le plugin dès qu'il a été mis à disposition il y a quelques semaines sur raspberry avec domoticz 2020.2 et depuis j'ai très souvent des résultats incohérents.
Il est précisé sur le readme que la demande doit être faite à Enédis d'une collecte toutes les 1/2 heure, c'est une option qui n'est pas disponible me concernant. Selon le site suivant ce n'est pas possible pour les compteur installé depuis 1/07/2018.

https://www.inc-conso.fr/content/compteur-linky-et-donnees-personnelles-du-nouveau-depuis-le-1er-juillet-2018

Peut-être est-ce la raison de mes problèmes ?

Merci pour toutes informations qui me viendraient en aide.

**Comment by guillaumezin** [comment]
Bonjour,
Je n'ai pas la même interprétation du texte que vous, il est indiqué que le consommateur peut choisir d'activer ou non la collecte par demi-heure, et c'est bien le sens du readme.

Dans mon compte, je trouve bien des encarts pour m'opposer à la collecte :

![image](https://user-images.githubusercontent.com/541581/94892946-5437bd80-0486-11eb-9919-e1d7e6acd567.png)

![image](https://user-images.githubusercontent.com/541581/94892969-61ed4300-0486-11eb-95e1-67b5a0d8debb.png)

**Comment by jcsombret** [comment]
Bonjour,

Merci pour votre réponse.

En effet je retrouve bien sur mon compte Enédis les mêmes questions que celles figurant sur la copie d'écran que vous avez jointe à votre message.
Mais la question posée par Enédis est : "Collecte de la consommation horaire" et non pas par tranche de 1/2 heure, d'où mon interrogation sur une possible divergence de traitement sur ce paramètre qui pourrait expliquer les incohérences entre les consommations issues du plugin et les consommations réelles issues du site Enédis.

Avec tous mes remerciements pour ce que vous faites.

Bien cordialement

**Comment by guillaumezin** [comment]
Comme pour #88, il faut que j'améliore le readme

**Comment by guillaumezin** [comment]
Je clos, j'ai amélioré le readme.
