### ISSUE TITLE
Valeur journée précédente sur page accueil erronée

### ISSUE THREAD

**Issue by Scrat95220** [guillaumezin/DomoticzLinky#9]
Version : 1.1.3

La valeur correspondant à la journée précédente sur la page d’accueil est erronée.
Exemple
Valeurs sur la page d'accueil : 18.302 kwh 
Valeur réelle : 16.888 kwh

![Valeur acceuil](https://user-images.githubusercontent.com/33357657/55030630-16461780-500d-11e9-8768-9da4b48405ce.jpg)
![Valeurs réelles](https://user-images.githubusercontent.com/33357657/55030640-1a723500-500d-11e9-9c93-98ccdfd03ae4.jpg)

**Comment by guillaumezin** [comment]
C'est curieux en effet, je ne reproduis pas votre problème. Dans les paramètres du plugin, sur "Consommation à montrer sur le tableau de bord", êtes-vous bien sur "Journée dernière" ?

**Comment by Scrat95220** [comment]
Oui je suis bien sur journée entière : 
![Settings](https://user-images.githubusercontent.com/33357657/55032929-40e69f00-5012-11e9-9458-e80a403422e5.jpg)

**Comment by guillaumezin** [comment]
Et avez-vous des messages d'erreur du plugin dans les logs ?

**Comment by Scrat95220** [comment]
Je n'ai que cette erreur concernant le plugin : 
2019-03-26 06:06:40.281 Error: (Linky): Async Secure Read Exception: 335544539, short read

**Comment by guillaumezin** [comment]
Dans ce cas, c'est un peu lourd, mais pouvez-vous activer le debug et poster le log ? Je ne comprends pas où je pêche cette valeur de 18302. A moins qu'elle ne se mette jamais à jour.

**Comment by Scrat95220** [comment]
Si la valeur change tous les jours mais est erronée.
Je joints les logs
[linky.log](https://github.com/guillaumezin/DomoticzLinky/files/3010386/linky.log)

**Comment by Scrat95220** [comment]
Bonjour,
Pour infos, le rechargement des datas au redémarrage du NAS a résolu le problème tout seul... Pourtant j'avais essayé la réinstallation du plugin et un restart de domoticz sans succès.
Bref problème résolu.

**Comment by guillaumezin** [comment]
Pourtant je vois bien le bug dans votre log :

`2019-03-26 22:02:49.330  (Linky - Linky) Updating device from 0:'-1.0;16888.0' to have values 0:'-1.0;18302.0;2019-02-23'.
2019-03-26 22:02:49.339  (Linky - Linky) Updating device from 0:'-1.0;16888.0' to have values 0:'-1.0;18302.0'.`

Il met la valeur du 23/02...

**Comment by guillaumezin** [comment]
Ok, j'ai compris où était le problème, il ne se produit que si on demande plus de 28 jours de données...

**Comment by guillaumezin** [comment]
Merci d'avoir pris le temps de décrire le problème et d'envoyer les logs. C'est corrigé en version 1.1.4.

**Comment by Scrat95220** [comment]
Super, merci pour la reactivité !!!
