### ISSUE TITLE
Plugin non détecté - Incompatibilités connues ? 

### ISSUE THREAD

**Issue by isis59** [guillaumezin/DomoticzLinky#90]
Bonjour,

Domoticz 2020.2, Rpi 3+ Raspbian 10 (Debian GLIBC 2.28-10+rpi1), j'ai téléchargé le plugin, mis les droits, et impossible de le voir apparaître dans la liste des types de matériels Domoticz. Rédemarrage Domoticz & RPI sans succès. 

Pour info, j'ai également tenté sur un autre Domoticz (v. 410338), et là le plugin apparait bien (mais la version de domoticz est trop ancienne).

**Comment by guillaumezin** [comment]
Je ne sais pas quelle version de Raspbian j'ai, mais ma config ressemble à la vôtre, ça devrait fonctionner. Avez-vous bien mis les droits d'exécution ? Le chemin (domoticz/plugin/DomoticzLinky) a-t-il les droits de lecture et d'éxecution pour chaque sous-répertoire ? Avez-vous installé python 3,cf. https://www.domoticz.com/wiki/Using_Python_plugins ? Il faut redémarrer Domoticz ensuite.

**Comment by isis59** [comment]
Bonjour,

En effet tout était correct côté plugin. J'ai simplement installé libpython3.7-dev et python3.7-dev pour que le plugin apparaisse. 
(Je n'avais pas les version -dev)

**Comment by guillaumezin** [comment]
Super, je vais peut-être insister dans le readme

**Comment by guillaumezin** [comment]
Je clos, j'ai insisté dans le readme.
