### ISSUE TITLE
Reinitialisation -> pas de creation du device

### ISSUE THREAD

**Issue by usky73** [guillaumezin/DomoticzLinky#97]
bonjour, suite à des erreurs récurentes apparues il y a 2 semaines (aucune mesure remontée) j'ai essayé de tout reinstaller...
Mais il y a un truc qui coince, le device ne se cree pas (il me semble que c'était automatique) et j'ai toujours un message dans le log : 
2020-10-11 19:13:29.247 Error: (linky2) durant l'étape : retry - Trop d'échecs de communication, le plugin réessaiera plus tard

Help !

**Comment by guillaumezin** [comment]
Bonjour,
A combien avez-vous mis le paramètre "Nombre de jours à récupérer pour les autres vues"? Si le paramètre est élevé, le risque d'échec est également élevé, et si le processus ne va pas jusqu'au bout, le périphérique n'est pas créé.

**Comment by walawa75** [comment]
Bonsoir,
Personnellement j'ai rentré 182 jours (6 mois) et ça fonctionne mieux avec la création du dispositif. Par contre je pense que ces derniers jours il y avait un gros problème avec les serveurs d'Enedis. Depuis aujourd'hui ça marche nickel (enfin) et je n'ai plus l'erreur Trop d'échecs de communication, le plugin réessaiera plus tard. En plus j'ai enfin les remontées de valeurs réelles de consommation.
Merci @guillaumezin pour le super boulot !!

**Comment by usky73** [comment]
Ok merci j'avais mis 70 jours
C'est reparti mais ca a pris plusieurs jours.
Merci
