### ISSUE TITLE
Problème affichage valeur

### ISSUE THREAD

**Issue by MrJown** [guillaumezin/DomoticzLinky#98]
Bonjour,

Il y a des erreurs d'affichage sur le dispositif : https://ibb.co/D1XTYxM

De plus, il manque certains jours dans la vue journalière alors que c'est bien visible sur le site de Enedis : https://ibb.co/FJk9R3K

Domoticz version : 2020.2
OS : Raspberry OS 10
Matériel : Raspberry Pi 3B+

Merci bien,

**Comment by guillaumezin** [comment]
Bonsoir,
Quelle est votre version de plugin ? Avez-vous essayé de baisser le paramètre "nombre de jours à récupérer pour les autres vues" à 7 ?

**Comment by MrJown** [comment]
Bonjour,

Merci de cette réponse.
Je viens de m'apercevoir que j'avais configuré 0 jour à récupérer pour la vue par heure ..

C'est tout bon du coup, désolé du dérangement
